# Curriculum data, Parts 1-6
PARTS = []
CH = []

def part(pid, title, levels, blurb):
    PARTS.append(dict(id=pid, title=title, levels=levels, blurb=blurb))

def ch(cid, slug, title, level, pages, obj, terms, prereq, diagrams, examples, drill, fwd=None):
    CH.append(dict(id=cid, slug=slug, title=title, level=level, pages=pages, obj=obj,
                   terms=terms, prereq=prereq, diagrams=diagrams, examples=examples,
                   drill=drill, fwd=fwd or []))

# ---------------------------------------------------------------- PART 1
part("01", "Foundations: The Game Beneath the Broadcast", "1",
     "Everything a casual viewer half-knows, made precise: the field, the clock, downs, the 22 players, "
     "and, most importantly, what a 'play' actually is in real life versus a Madden play card. "
     "Ends by starting the reader's prediction log, the course-long habit that every later chapter sharpens.")

ch("01-01", "the-game-in-fifteen-minutes", "The Game in Fifteen Minutes: Field, Scoring, and Clock", 1, 10,
   ["Read every marking on the field: yard lines, numbers, hash marks, goal line, end zone, sidelines.",
    "Explain the wide (field) side vs short (boundary) side and why the ball's hash position changes play design.",
    "Score every way points are made (TD, PAT, two-point try, field goal, safety) and why 7-vs-3 is the game's central tension.",
    "Explain when the game clock runs and stops (incompletions, out of bounds, scores, change of possession, two-minute warning).",
    "Distinguish the game clock from the play clock (40 / 25 seconds).",
    "Describe the shape of a game: kickoff, possessions, quarters, halftime, overtime (details deferred to 10-04)."],
   ["end zone", "goal line", "yard line", "hash marks", "field side (wide side)", "boundary side (short side)",
    "sideline", "touchdown", "extra point (PAT)", "two-point conversion", "field goal", "safety (score)",
    "possession", "quarter", "two-minute warning", "timeout", "game clock", "play clock"],
   [],
   ["S: Full field overhead, every marking labelled; ball on left hash with field/boundary shaded",
    "S: NFL vs college hash width side-by-side (why college has a much bigger wide side)",
    "S: Scoring summary card (6/1/2/3/2 with where each happens)",
    "S: Clock flowchart: 'after this play, does the clock run?'"],
   ["Walk-through of Super Bowl LIX (Eagles 40-22 Chiefs) scoring plays located on the field diagram"],
   "Clock watcher: for one quarter, before each snap say aloud whether the clock is running and why.",
   fwd=["10-04 (overtime and clock strategy in depth)"])

ch("01-02", "downs-distance-and-field-position", "Downs, Distance, and Field Position", 1, 10,
   ["Explain four downs, the line to gain, and why teams usually punt on fourth down.",
    "Read the on-screen down-and-distance graphic and bucket it as short, medium, or long.",
    "Define the line of scrimmage, the spot, and the chain crew / sticks.",
    "Explain turnovers: interception, fumble, turnover on downs.",
    "Treat field position as a currency (preview of Expected Points, 13-02).",
    "Define a drive and the red zone."],
   ["down", "line to gain", "first down", "line of scrimmage", "spot (of the ball)", "the sticks (chains)",
    "turnover", "interception", "fumble", "turnover on downs", "punt", "field position", "drive (possession)", "red zone"],
   ["01-01"],
   ["A: Series of downs: 1st & 10 -> 2nd & 6 -> 3rd & 2 -> first down, chains moving (frame strip)",
    "S: Field-position map: own territory / midfield / opponent territory / red zone",
    "C: League 3rd-down conversion % by yards to go (nflverse, 2016-2025), code folded"],
   ["League-average conversion rates", "A famous 4th-down stop (e.g. Super Bowl XXXIV 'One Yard Short', Titans-Rams)"],
   "Down-and-distance forecaster: before each snap predict run or pass from down & distance alone; tally hit rate. "
   "This baseline accuracy is the first entry in the course-long prediction log.",
   fwd=["13-02 (Expected Points formalises 'field position as currency')"])

ch("01-03", "the-twenty-two", "The Twenty-Two: Every Position and What It Actually Does", 1, 14,
   ["Name the offensive positions and their jobs: QB, RB/HB, FB, WR (X/Z/slot), TE, OL (C, G, T).",
    "Name the defensive positions: DT/NT, DE/edge, LB (Mike, Will, Sam), CB, slot corner, FS, SS.",
    "Name the special-teams specialists: K, P, LS, holder, returner, gunner.",
    "Distinguish eligible from ineligible receivers and the jersey-number convention.",
    "Explain why body types map to jobs (combine data).",
    "Separate position (who you are) from alignment and assignment (what you do this play)."],
   ["quarterback", "running back (halfback)", "fullback", "wide receiver", "tight end", "offensive line",
    "center", "guard", "tackle (position)", "defensive tackle", "nose tackle", "defensive end", "edge rusher",
    "linebacker", "Mike linebacker", "Will linebacker", "Sam linebacker", "cornerback", "slot cornerback (nickel back)",
    "safety (position)", "free safety", "strong safety", "kicker", "punter", "long snapper", "holder", "returner",
    "gunner", "eligible receiver", "ineligible receiver", "skill positions", "front seven", "secondary",
    "alignment", "assignment"],
   ["01-01"],
   ["S: Offense (two-back) vs 4-3 base, every position labelled",
    "S: 11 personnel vs nickel, same labels (teaser for 02-01 / 02-06)",
    "C: Height/weight scatter by position from combine data",
    "S: Jersey-number ranges after the 2021 numbering change"],
   ["Kyle Juszczyk (FB)", "Travis Kelce (TE)", "Penei Sewell (T)", "Aaron Donald (DT)", "T.J. Watt (edge)",
    "Fred Warner (LB)", "Kyle Hamilton (S)"],
   "One-player game: watch only the center for an entire drive and narrate what he did each play.")

ch("01-04", "what-a-play-really-is", "What a Play Really Is (It Isn't Picking a Card in Madden)", 1, 14,
   ["Trace the real chain: call sheet -> coordinator -> helmet radio -> QB / green-dot defender -> huddle or signals -> snap.",
    "Decompose a play call into formation, motion, protection, concept, and tags.",
    "Explain the 40-second play clock, the radio cut-off at 15 seconds, and delay of game.",
    "Explain why both coordinators call blind and simultaneously, and why that creates the pre-snap chess match.",
    "Contrast Madden with reality: 11 people executing rules, reads after the snap, one call = a family of outcomes.",
    "Explain huddle vs no-huddle, wristbands, and sideline signal boards.",
    "Describe what happens in the 3-7 seconds after the snap: assignments, reads, adjustments."],
   ["play call", "call sheet", "helmet radio (coach-to-player communication)", "green dot", "huddle", "no-huddle",
    "wristband", "delay of game", "snap", "read (post-snap)", "verbiage (terminology)", "tag", "playbook", "install"],
   ["01-02", "01-03"],
   ["A: Play-clock timeline: whistle -> call in -> radio cuts at 15 -> huddle break -> set -> snap (frame strip)",
    "S: Communication flow: OC/DC -> QB/green dot -> teammates",
    "S: Anatomy of a play call: one long call split into labelled chunks",
    "S: Madden play art vs a coach's diagram of the same idea (rules, options, reads)",
    "A: One play from huddle break to whistle, every player's assignment highlighted in turn"],
   ["Shanahan/McVay-style long verbal calls vs Erhardt-Perkins one-word concepts (teaser for 04-08)",
    "Peyton Manning's 'Omaha' era", "Chiefs and wristband offenses", "Bills' sugar huddle"],
   "Huddle stopwatch: time whistle-to-snap for several drives; note who huddles, who doesn't, and who snaps with under 5 seconds on the play clock.",
   fwd=["04-08 (play-calling languages)", "08-04 (tempo)"])

ch("01-05", "the-pre-snap-phase", "The Pre-Snap Phase: Shifts, Motion, Cadence, and Audibles", 2, 12,
   ["Define set, shift, and motion and the legal-motion rules (one man moving, not toward the line at the snap; one-second set after a shift).",
    "Explain cadence and hard counts and the penalties they draw (offside, encroachment, neutral zone infraction, false start).",
    "Define audibles, checks, kill calls, and check-with-me systems.",
    "Explain Mike identification and why it sets the protection.",
    "Recognise defensive pre-snap movement: shifting fronts, safeties walking down, linebackers showing blitz.",
    "List what each side is trying to learn before the snap."],
   ["set", "shift", "motion", "false start", "offside", "encroachment", "neutral zone infraction", "illegal motion",
    "cadence (snap count)", "hard count", "silent count", "audible", "check", "kill call", "check-with-me",
    "Mike identification (MIKE ID)", "dummy call"],
   ["01-04"],
   ["S: Legal vs illegal motion side by side",
    "A: Shift: TE crosses formation, everyone resets one second (frame strip)",
    "S: Kill call: two plays called, check made on box count",
    "A: Defense moves pre-snap: safety walks down, linebacker creeps to A-gap"],
   ["Peyton Manning pre-snap theatre", "Aaron Rodgers' hard count free plays", "Eagles' silent count at home vs on the road"],
   "Count the movement: after the huddle breaks, count offensive players who move before the snap and whether any defender moves with them.",
   fwd=["02-05 (motion as a man/zone indicator)", "07-02 (A-gap mugs and protection)"])

ch("01-06", "how-to-watch-a-broadcast", "How to Watch a Broadcast Like You Mean It", 1, 9,
   ["Know what the broadcast camera hides (safeties, receivers downfield) and what replays, skycam, and end-zone angles reveal.",
    "Use the pre-snap pause: read down, distance, clock, score, and timeouts in under five seconds.",
    "Adopt the 'watch one thing' strategy by play type.",
    "Read broadcast graphics: win-probability bars, Next Gen Stats overlays.",
    "Set up the prediction log used for the rest of the course."],
   ["All-22", "end-zone camera", "sideline camera", "skycam", "coaches film", "prediction log"],
   ["01-05"],
   ["S: Broadcast frame vs All-22 frame, field coverage shaded",
    "S: 'Where to look' by phase: pre-snap, first second, ball in air",
    "S: Prediction-log template (paper and a 10-line pandas version)"],
   ["NFL+ Premium (All-22 access)", "Prime Vision alternate broadcast", "Typical replay sequence on a big play"],
   "Prediction log, game 1: for one half log run/pass guess and outcome; compute accuracy (compare to 01-02 baseline).",
   fwd=["15-01 (All-22 film study in depth)"])

# ---------------------------------------------------------------- PART 2
part("02", "Personnel and Formations: Reading the Offense Before the Snap", "1-2",
     "Who is on the field and where they stand. Personnel and formation are the first two clues of every pre-snap read. "
     "The part closes with a deliberately shallow first look at defense (packages, the box, man vs zone, one-high vs two-high) "
     "so Parts 3-4 can talk about defenders without waiting for Parts 5-6.")

ch("02-01", "personnel-groupings", "Personnel: Who's on the Field Before Anything Else", 1, 11,
   ["Decode two-digit personnel (RBs then TEs; WRs = 5 - RB - TE): 11, 12, 21, 13, 22, 10, 20, 00.",
    "Explain why personnel is the first pre-snap clue and how it forces the defense's substitution.",
    "Explain substitution rules: the defense gets to match when the offense subs.",
    "Read league personnel trends 2016-2025 (rise of 11; recent 12/13 and six-OL rebound).",
    "Link personnel to run/pass tendencies with real data."],
   ["personnel grouping", "11 personnel", "12 personnel", "21 personnel", "13 personnel", "22 personnel",
    "10 personnel", "substitution matching", "heavy personnel", "jumbo (six offensive linemen)"],
   ["01-03", "01-06"],
   ["S: Personnel card deck: one neutral-alignment plate per grouping",
    "A: Offense subs in 12; defense swaps a DB for a LB (frame strip)",
    "C: League personnel share by season, 2016-2025",
    "C: Pass rate by personnel grouping (neutral situations)"],
   ["McVay Rams 11 personnel (2017-2019)", "49ers 21 personnel with Juszczyk", "Ravens 2019 heavy sets",
    "Eagles 2024 12 personnel with Saquon Barkley", "Lions six-OL jumbo with an eligible tackle"],
   "Call the personnel: count RBs and TEs before each snap, say the number, then guess run/pass from the personnel chart.")

ch("02-02", "formation-rules-and-vocabulary", "Formation Rules and the Language of Alignment", 2, 12,
   ["Apply formation legality: seven on the line, ends eligible, covered receivers, illegal formation.",
    "Define formation strength and how each side declares it (TE side, receiver side, field side).",
    "Use the receiver labels X, Y, Z, H/F plus slot, wing, flanker, split end, in-line, off-ball.",
    "Describe QB/backfield alignments: under center, shotgun, pistol, offset, sidecar.",
    "Read splits (wide, normal, reduced, tight) and alignment landmarks (the numbers, the hash).",
    "Recognise how the 2015 ineligible-receiver trick produced a rule change."],
   ["on the line / off the line", "covered receiver", "illegal formation", "formation strength", "strong side",
    "weak side", "X receiver (split end)", "Z receiver (flanker)", "Y receiver", "H / F (move player)", "slot",
    "wing", "in-line tight end", "under center", "shotgun", "pistol", "offset back", "split (receiver split)",
    "reduced split", "the numbers (alignment landmark)"],
   ["02-01"],
   ["S: Legal vs illegal (six on the line; TE covered by a WR)",
    "S: Label map: X/Y/Z/H/F on a 2x2 and on a 3x1",
    "S: QB depth comparison: under center / pistol / shotgun with typical depths",
    "S: Split ladder: wide -> numbers -> reduced -> tight",
    "S: Strength declaration examples (TE strength vs passing strength vs field)"],
   ["Patriots' ineligible-receiver formations vs Ravens (2014 season divisional round) and the subsequent rule change"],
   "Strength caller: name the strong side before each snap, then watch which way the defense set its front.")

ch("02-03", "classic-formations", "Classic Formations: I, Power I, Pro Set, Singleback, and Their Ancestors", 2, 11,
   ["Identify I-form, offset I, Power I, pro set (split backs), singleback, ace, T, wishbone, Wing-T, jumbo/goal line.",
    "Explain each formation's purpose: lead blocker, downhill angles, balance, misdirection.",
    "Explain why two-back, under-center formations declined and where they survive (21 personnel, short yardage, play-action).",
    "Match each formation to its typical personnel."],
   ["I-formation", "offset I", "Power I", "pro set (split backs)", "singleback", "ace formation", "T-formation",
    "wishbone", "Wing-T", "goal-line formation", "full house backfield"],
   ["02-02"],
   ["S: Atlas plates for each classic formation (10 plates, consistent style)",
    "C: Under-center vs shotgun share 2006-2025",
    "S: Family tree: T -> wishbone / I / pro set"],
   ["Lombardi Packers pro set", "Joe Gibbs' one-back/ace Redskins", "49ers 21 personnel I-form",
    "Ravens 2024 with Patrick Ricard at FB"],
   "Name that formation: for 10 snaps name the formation, under center or gun, one back or two.")

ch("02-04", "spread-and-modern-formations", "Spread Formations: 2x2, Trips, Bunch, Empty, and the Condensed Revolution", 2, 12,
   ["Identify 2x2 (doubles), 3x1 (trips), empty (3x2), bunch, stack, nub, quads.",
    "Explain why spreading the field forces the defense to declare itself and creates space.",
    "Explain condensed/tight splits and why modern offenses use them (crack blocks, two-way go, rubs).",
    "Recognise specialty looks: wildcat, unbalanced (tackle over), swinging gate."],
   ["2x2 (doubles)", "3x1 (trips)", "empty (3x2)", "bunch", "stack", "nub", "quads", "condensed formation",
    "wildcat", "unbalanced line (tackle over)", "swinging gate"],
   ["02-02"],
   ["S: Atlas plates for each spread formation",
    "S: Wide vs condensed split: same play, space created shaded",
    "C: Formation usage trend (shotgun 2x2 / 3x1 / empty) by season"],
   ["2007 Patriots spread (Brady, Moss, Welker)", "2018 Rams condensed 3x1", "2008 Dolphins Wildcat",
    "Bills empty with Josh Allen", "Chiefs bunch sets"],
   "Formation & leverage: name the formation, then count receivers vs defenders on each side.")

ch("02-05", "motion-and-shifts", "Motion and Shifts as Weapons", 3, 12,
   ["Distinguish jet, orbit, fly, return (yo-yo), zoom, shift-to-bunch, and motion at the snap.",
    "Explain what motion does: reveals man vs zone, changes strength, creates leverage, gives a running start, stresses communication.",
    "Explain the NFL motion-at-the-snap rule vs college/CFL differences.",
    "Describe the 2023-2025 motion boom with data.",
    "Name defensive responses: travel (man), bump/slide (zone), spin (safety rotation)."],
   ["jet motion", "orbit motion", "return motion (yo-yo)", "fly motion", "zoom motion", "motion at the snap",
    "man/zone indicator", "bump (defensive adjustment)", "travel (man defender follows motion)", "spin (safety rotation on motion)"],
   ["02-04", "01-05"],
   ["S: Motion family plate",
    "A: Jet motion vs man: the corner runs across (frame strip)",
    "A: Same jet motion vs zone: defenders bump, safety spins (frame strip)",
    "C: Motion rate by team, 2022-2025 (FTN charting)"],
   ["Mike McDaniel's 2023 Dolphins (Tyreek Hill motion at the snap)", "Shanahan 49ers (Deebo Samuel)",
    "McVay Rams", "Chiefs orbit motion"],
   "Follow the motion: when a receiver motions, watch who follows; call man or zone; check after the play.",
   fwd=["06-06 (disguise defeats the motion indicator)"])

ch("02-06", "a-first-look-at-defense", "A First Look at Defense: Packages, the Box, Man vs Zone, One-High vs Two-High", 2, 12,
   ["Name defensive packages (base 4-3 / 3-4, nickel, dime, quarter, big nickel, goal line) and where 'nickel' and 'dime' come from.",
    "Count the box and explain why box count drives run/pass choices.",
    "Distinguish man and zone coverage at the concept level.",
    "Distinguish one-high and two-high safety shells and what each is good at.",
    "Explain why nickel is the modern NFL base defense.",
    "Signpost what comes later: fronts (Part 5), coverages (Part 6), pressure (Part 7)."],
   ["defensive package", "base defense", "4-3", "3-4", "nickel", "dime", "quarter (dollar)", "big nickel",
    "box", "box count", "light box", "loaded box", "man coverage", "zone coverage", "one-high (single-high)",
    "two-high", "shell (coverage shell)"],
   ["02-01", "01-03"],
   ["S: Package plates: base / nickel / dime vs 11 personnel",
    "S: The box: tackle-to-tackle, ~5-7 yards deep, with counting examples",
    "S: One-high vs two-high silhouettes",
    "A: Same two routes vs man and vs zone (frame strip)",
    "C: Share of defensive snaps in nickel or lighter, by season"],
   ["Belichick dime vs pass-heavy offenses", "Ravens big nickel with Kyle Hamilton", "Lions/Packers nickel as base"],
   "Box and shell: every snap count the box and say one-high or two-high; log alongside run/pass.",
   fwd=["Part 5 (fronts)", "Part 6 (coverages)", "Part 7 (pressure)"])

# ---------------------------------------------------------------- PART 3
part("03", "The Run Game", "2-3",
     "How offenses run the ball: the vocabulary of gaps and blocks, then the two great blocking families (zone and gap), "
     "option football, and misdirection. Defensive front names appear in diagrams with forward references to Part 5.")

ch("03-01", "run-game-language", "The Language of the Run Game: Gaps, Techniques, and Blocks", 2, 13,
   ["Label gaps A-D and the common hole-numbering system.",
    "Describe defensive alignments with technique numbers (0, 1, 2i, 2, 3, 4i, 4, 5, 6, 7, 9).",
    "Define the core blocks: drive, down, reach, cut-off, combo, pull, kick-out, log, lead, cut, seal, crack.",
    "Use covered/uncovered linemen and 'hat on a hat' arithmetic.",
    "Explain why a non-running QB leaves the offense a defender short.",
    "Contrast zone and gap philosophies at a high level."],
   ["gap (A, B, C, D)", "hole numbering", "technique (alignment number)", "shade", "head-up", "drive block",
    "down block", "reach block", "cut-off block", "combo block (double team)", "pull", "kick-out", "log block (wrap)",
    "lead block", "cut block", "seal block", "crack block", "covered / uncovered lineman", "point of attack",
    "playside / backside", "hat math (numbers advantage)"],
   ["02-03", "02-06"],
   ["S: Master gap & technique chart",
    "S: Block library plate (one mini-diagram per block)",
    "S: Hat math: seven in the box vs six blockers + RB",
    "A: Combo block: guard and center double the 1-tech, one climbs to the Mike (frame strip)"],
   ["Joe Gibbs' Hogs", "Jason Kelce as a climbing/pulling center", "Lions OL (Sewell, Ragnow)"],
   "Find the hole: predict the gap from the RB's first step; afterwards name the gap he actually hit.",
   fwd=["05-01 (technique numbers from the defense's side)"])

ch("03-02", "zone-running", "Zone Running: Inside Zone, Outside Zone, and the Cutback", 3, 16,
   ["Explain zone rules: step playside, covered/uncovered, combo to the second level.",
    "Distinguish inside zone, outside (wide) zone, and stretch by aiming point and intent.",
    "Explain the RB's bang-bend-bounce read and the one-cut style.",
    "Explain the cutback and the backside cut-off (and why cut blocks are controversial).",
    "Show why wide zone pairs with bootleg play-action.",
    "Evaluate zone efficiency with nflverse rushing EPA by run location."],
   ["zone blocking", "inside zone", "outside zone (wide zone)", "stretch", "aiming point", "bang-bend-bounce",
    "cutback", "backside cut-off", "one-cut runner", "reach-and-overtake"],
   ["03-01"],
   ["S: Inside zone vs an even (4-3 Over) front",
    "A: Outside zone vs an even front, all 11 assignments (frame strip, 6-8 frames)",
    "S: Same outside zone vs an odd front: the rules adapt",
    "S: RB decision tree: bang / bend / bounce",
    "C: EPA per rush by run location, 49ers vs league, 2019-2025"],
   ["Alex Gibbs & Mike Shanahan's Broncos (Terrell Davis, 1996-98)", "Kyle Shanahan's 49ers (Christian McCaffrey 2023)",
    "McVay Rams", "LaFleur Packers", "Klint Kubiak's 2025 Seahawks"],
   "Bang, bend, bounce: on every zone run, call which option the RB took and where the backside end was.",
   fwd=["05-02 (front names)", "04-05 (bootleg play-action)", "12-03 (Shanahan case study)"])

ch("03-03", "gap-and-power-runs", "Gap Schemes: Power, Counter, Duo, Trap, and Iso", 3, 15,
   ["Explain gap schemes: down blocks, pullers, kick-outs, and wraps.",
    "Diagram power, counter, duo, trap, iso, toss/sweep, pin-and-pull.",
    "Explain how gap schemes manufacture extra blockers at the point of attack.",
    "Know when coaches choose gap vs zone (front, personnel, OL body types).",
    "Spot pre-snap tells of a pulling lineman."],
   ["gap scheme (man/power blocking)", "power (Power O)", "counter (counter trey / GT counter)", "duo", "trap",
    "iso (isolation)", "toss / sweep", "pin-and-pull", "puller"],
   ["03-01"],
   ["S: Power vs 4-3 Over",
    "A: Counter (GT) vs even front, guard kicks out and tackle wraps (frame strip)",
    "S: Duo vs two-high", "S: Trap vs a 3-technique", "S: Iso vs 4-3", "S: Pin-and-pull vs wide front"],
   ["Gibbs Redskins counter trey (John Riggins era)", "Lombardi's power sweep as ancestor of pin-and-pull",
    "Titans Derrick Henry duo/power", "Ravens 2019 gap game", "Eagles 2024 with Saquon Barkley"],
   "Follow the guard: watch the backside guard; if he pulls, call gap scheme and its direction.",
   fwd=["05-05 (how defenses fit gap runs)"])

ch("03-04", "option-football", "Option Football: Reading Defenders Instead of Blocking Them", 3, 15,
   ["Explain the option principle: leave a defender unblocked, read him, gain a man.",
    "Diagram zone read, inverted veer (power read), speed option, triple option, midline.",
    "Explain dive / keep / pitch roles and the QB's read key.",
    "Explain designed QB runs (QB power, QB counter, QB draw) as blocker-count changers.",
    "Name defensive answers (scrape exchange, gap exchange) with a forward reference to 05-05.",
    "Explain the NFL's on-and-off relationship with option (2012 wave, fade, Lamar/Hurts/Allen era)."],
   ["option", "read key (read defender)", "zone read", "give / keep", "inverted veer (power read)", "speed option",
    "triple option", "dive", "pitch", "midline option", "veer", "QB power", "QB counter", "QB draw", "scrape exchange"],
   ["03-02", "03-03"],
   ["A: Zone read, two branches: end crashes (keep) vs end stays (give) (frame strips)",
    "S: Triple option from flexbone", "S: Inverted veer", "S: Speed option",
    "S: QB power with RB as lead blocker",
    "C: Designed QB run EPA vs RB run EPA, 2016-2025"],
   ["2012 Washington (RGIII, pistol zone read)", "Kaepernick 49ers", "Ravens 2019 rushing record with Lamar",
    "Jalen Hurts' Eagles", "Navy / Georgia Tech flexbone", "Nevada pistol (Chris Ault)"],
   "Find the read key: on read looks, locate the unblocked end-man-on-line and predict give/keep from his first step.",
   fwd=["05-05 (defending option)", "11-03 (college origins)", "12-05 (Ravens case study)"])

ch("03-05", "perimeter-and-misdirection", "Perimeter Runs and Misdirection: Jet Sweeps, Reverses, and the Wing-T's Children", 3, 12,
   ["Explain jet sweep, end-around, reverse, crack-toss, and buck sweep and how each punishes over-pursuit.",
    "Understand the Wing-T's series logic (buck sweep, trap, belly, waggle) and its NFL descendants.",
    "Explain 'eye candy': motion and backfield action that freeze linebackers.",
    "Connect misdirection to constraint theory (forward reference 08-02)."],
   ["jet sweep", "end-around", "reverse", "crack-toss", "buck sweep", "series football", "misdirection",
    "eye candy", "waggle"],
   ["03-03", "02-05"],
   ["S: Wing-T buck sweep", "A: Jet sweep with LB flow shown (frame strip)", "S: Crack-toss", "S: Reverse",
    "A: Eye candy: jet fake freezes the Mike for 0.5s, inside run hits (frame strip)"],
   ["Delaware Wing-T (Tubby Raymond)", "Gus Malzahn", "2018 Rams jet motion", "49ers Deebo Samuel", "Chiefs shovel/jet packages"],
   "Watch the second level: on jet motion, watch the linebackers' eyes and feet. Did they chase?",
   fwd=["08-02 (constraint theory)", "04-05 (waggle -> bootleg)"])

# ---------------------------------------------------------------- PART 4
part("04", "The Passing Game", "2-4",
     "Routes, timing, protection, the major concept families, play-action and screens, RPOs, quarterback play, and "
     "the systems/languages coaches use. Concepts are taught as stretches of generic defenders; the explicit "
     "'what beats what' matrix waits until coverages are taught (08-01).")

ch("04-01", "passing-fundamentals", "Passing Game Fundamentals: Routes, Timing, and Reads", 2, 14,
   ["Use the numbered route tree and common non-tree routes (seam, wheel, whip, option, sluggo).",
    "Link drop depth to route depth (3/5/7-step under center; 1/3/5 from shotgun) and timing.",
    "Distinguish progression reads from defender reads; full-field vs half-field.",
    "Explain vertical (high-low) and horizontal stretches of a single defender.",
    "Define air yards, YAC, and average depth of target."],
   ["route tree", "flat route", "slant", "hitch (curl)", "out", "dig (in)", "corner route", "post", "go (fly / 9)",
    "comeback", "wheel", "seam", "option route", "whip", "sluggo", "drop (3/5/7-step)", "timing route",
    "progression", "high-low read (vertical stretch)", "horizontal stretch", "conflict defender", "air yards",
    "YAC (yards after catch)", "aDOT (average depth of target)"],
   ["02-04", "02-06"],
   ["S: Route tree with numbers", "S: Drop-to-route timing chart",
    "A: High-low stretch of a flat defender, both branches (frame strip)", "S: Horizontal stretch of a hook defender",
    "C: Completion % and EPA by target depth"],
   ["Coryell numbering of the tree", "Walsh timing passing", "Mahomes off-platform vs Brady rhythm"],
   "Route caller: on replays, name every receiver's route.",
   fwd=["06-01 (zones the routes attack)", "08-01 (what beats what)"])

ch("04-02", "pass-protection", "Pass Protection: Slides, Man Schemes, and Who Blocks the Extra Guy", 3, 14,
   ["Explain five-, six-, and seven-man protections; slide, man (BOB), half-slide, max protect.",
    "Define RB/TE protection roles: check-release, chip.",
    "Explain hot routes and sight adjustments when rushers outnumber blockers.",
    "Connect Mike ID to the protection call.",
    "Describe pocket geometry: depth, launch point, step-up; vertical vs jump sets.",
    "Read protection metrics: pressure rate, time to throw."],
   ["slide protection", "man protection (BOB)", "half-slide", "max protect", "chip", "check-release", "hot route",
    "sight adjust", "free rusher", "pocket", "launch point", "vertical set", "jump set", "time to throw", "pressure rate"],
   ["04-01", "03-01", "01-05"],
   ["S: Half-slide vs four-man rush",
    "A: Six-man protection; RB picks up a blitzing LB (frame strip)",
    "S: Five blockers vs six rushers -> hot throw",
    "T: Pocket shape over time from tracking data (convex hull of OL), frame strip",
    "C: Sack rate vs time to throw, team-season scatter"],
   ["Patriots protection calls", "2022 Bengals OL vs Chiefs", "Eagles OL (Kelce, Johnson)"],
   "Rushers vs blockers: right after the snap count rushers and blockers; if one came free, guess who owned him.",
   fwd=["07-01 / 07-02 (rush and blitz from the defense's side)"])

ch("04-03", "quick-game", "The Quick Game: Slant-Flat, Stick, Snag, and Getting the Ball Out", 3, 12,
   ["Explain why quick game exists: beats pressure, keeps the offense on schedule, extends the run game.",
    "Diagram slant-flat, stick, snag, spacing, speed out, double slants, hitch-seam.",
    "Use receiver leverage (inside/outside) to make a pre-snap decision.",
    "Recognise quick game as the answer to press and blitz."],
   ["quick game", "slant-flat", "stick", "snag", "spacing", "speed out", "double slants", "hitch-seam",
    "leverage (inside / outside)", "pre-snap read", "rhythm throw"],
   ["04-01", "04-02"],
   ["S: Stick vs the flat defender", "A: Slant-flat high-low read (frame strip)", "S: Snag triangle",
    "S: Speed out", "A: Quick game vs a five-man pressure, ball out in 2.1s (frame strip)"],
   ["Walsh 49ers", "Brady Patriots", "Payton/Brees Saints", "Chiefs Kelce/quick game 2022-24"],
   "One-two-throw: stopwatch time to throw on quick game; under ~2.5s?")

ch("04-04", "dropback-concepts", "Dropback Concepts: Smash, Flood, Mesh, Levels, Dagger, and Four Verticals", 3, 18,
   ["Diagram and explain smash, flood (sail), levels, mesh, drive, shallow cross, curl-flat, dagger, Y-cross, four verticals, post-wheel, yankee.",
    "Classify each as vertical stretch, horizontal stretch, triangle, or man-beater.",
    "Walk the QB's progression for each.",
    "Explain tags and route conversions (break differently vs man and zone).",
    "Forward-reference the coverage matchups (08-01)."],
   ["pass concept", "smash", "flood (sail)", "levels", "mesh", "drive (concept)", "shallow cross", "curl-flat", "dagger",
    "Y-cross", "four verticals", "post-wheel", "yankee", "man-beater", "route conversion", "triangle read"],
   ["04-03"],
   ["S: Concept plates (12) in consistent style with numbered progressions",
    "A: Four verticals vs generic deep defenders (frame strip)",
    "A: Mesh vs man: the rub (frame strip)",
    "C: Pass EPA heatmap by target depth x field width"],
   ["Air Raid mesh and Y-cross (Leach)", "Patriots option/choice concepts", "McVay yankee", "Chiefs four verts variants"],
   "Name the concept: on replays, find two-receiver combinations and name the stretch.",
   fwd=["08-01 (concept vs coverage)", "06-03 (four verts vs Cover 3)"])

ch("04-05", "play-action-boots-screens", "Play-Action, Bootlegs, and Screens", 3, 14,
   ["Explain why play-action works (run-fit triggers) and the data finding that it does not require a successful run game.",
    "Distinguish under-center vs shotgun play-action, boot, naked, keeper, leak, shot plays.",
    "Diagram RB slow screen, bubble, tunnel, jailbreak, TE screen, middle screen.",
    "Explain screen timing, OL release, and why screens punish pressure.",
    "Compare team play-action rates and efficiency with data."],
   ["play-action", "bootleg", "naked bootleg", "keeper", "leak", "shot play", "screen", "slow screen (RB screen)",
    "bubble screen", "tunnel screen", "jailbreak screen", "swing route"],
   ["04-04", "03-02"],
   ["A: Wide-zone play-action boot: LBs step up, crosser opens (frame strip)", "S: Naked boot",
    "S: RB slow screen", "S: Tunnel screen", "S: Bubble screen",
    "C: EPA/dropback with vs without play-action by team (FTN/nflverse)"],
   ["2018 Rams (Goff play-action)", "Kubiak/Shanahan boots", "Chiefs screen game",
    "Ben Baldwin's play-action research"],
   "Watch the linebackers' feet: on play-action, did they step forward? How many yards did the crosser gain?")

ch("04-06", "rpos", "Run-Pass Options: Plays That Are Two Plays", 3, 13,
   ["Define the RPO and distinguish it from play-action and from the option.",
    "Diagram pre-snap (box-count) and post-snap (read-a-defender) RPOs: bubble, glance, stick, slant, pop pass.",
    "Explain the NFL ineligible-downfield rule and how it limits RPOs vs college.",
    "Identify the apex/overhang defender as the usual read.",
    "Preview defensive answers."],
   ["RPO (run-pass option)", "pre-snap RPO", "post-snap RPO", "apex (overhang) defender", "glance RPO",
    "bubble RPO", "illegal man downfield", "pop pass", "packaged play"],
   ["04-05", "03-04"],
   ["A: Inside zone + glance RPO reading the LB, both branches (frame strips)",
    "S: Bubble RPO by box count", "S: Slant RPO",
    "S: Ineligible-downfield limit: NFL 1 yard vs college"],
   ["2017 Eagles (Foles, Super Bowl LII)", "Chiefs RPOs", "Oregon / Auburn / Baylor college roots", "Jalen Hurts' Eagles"],
   "Is he reading you? At the mesh point, find the defender the QB is looking at.",
   fwd=["05-05 (fits vs RPO)", "08-02 (RPOs as constraints)", "11-03 (college lineage)"])

ch("04-07", "quarterback-play", "Quarterback Play: Progressions, Eyes, the Pocket, and the Scramble Drill", 4, 15,
   ["Map the QB's process: ID, protection, shell -> key -> progression.",
    "Explain eye manipulation of safeties (look-offs).",
    "Describe pocket movement: climb, slide, escape, throwaway.",
    "Explain scramble-drill rules and off-script play.",
    "Profile QB styles using time to throw, aDOT, CPOE, and EPA.",
    "Explain why QBs dominate value (forward ref 14-01)."],
   ["look-off", "climbing the pocket", "throwaway", "scramble drill", "off-script (off-schedule) play",
    "anticipation throw", "checkdown", "CPOE (completion % over expected)"],
   ["04-04", "04-02"],
   ["A: Progression read with numbered reads lighting up (frame strip)",
    "A: Safety look-off: QB eyes hold the safety, throws opposite (frame strip)",
    "S: Scramble-drill rules plate",
    "C: QB style map: time to throw vs aDOT, coloured by EPA/dropback"],
   ["Tom Brady", "Peyton Manning", "Patrick Mahomes (off-script)", "Josh Allen", "Joe Burrow", "Brock Purdy (system QB debate)"],
   "Watch the eyes: on replays count how many reads the QB got through before throwing.",
   fwd=["06-06 (reading disguise)", "14-01 (QB value)"])

ch("04-08", "offensive-systems-and-languages", "Offensive Systems and Play-Calling Languages", 4, 14,
   ["Distinguish the major families: West Coast, Air Coryell, Erhardt-Perkins, run-and-shoot, Air Raid, Shanahan/McVay, spread-option.",
    "Explain how each names plays and why that matters for installation and tempo.",
    "Map coaching trees onto 2025 NFL staffs.",
    "Recognise a system's fingerprints on film."],
   ["offensive system", "West Coast offense", "Air Coryell", "Erhardt-Perkins", "run-and-shoot", "choice route",
    "Air Raid", "concept-based terminology", "coaching tree"],
   ["04-07"],
   ["S: One concept named three ways (WCO / Coryell / EP)",
    "S: Coaching-tree network, 1970-2025",
    "S: Run-and-shoot base with choice routes",
    "S: Air Raid mesh and Y-cross from 2x2"],
   ["Walsh", "Coryell", "Erhardt/Perkins -> Parcells -> Belichick/Weis/McDaniels", "Mouse Davis & June Jones",
    "Mumme & Leach", "Shanahan -> McVay / LaFleur / McDaniel / Kubiak"],
   "Fingerprint the system: chart under-center %, motion, condensed sets, empty for one team; guess its tree.",
   fwd=["11-02 / 11-03 (history of these systems)", "Part 12 (case studies)"])

# ---------------------------------------------------------------- PART 5
part("05", "Defensive Fronts and Run Defense", "3-4",
     "The defense's side of Part 3: how linemen align and play, the even and odd front families, linebackers, and the "
     "integrated system of run fits that makes every gap someone's job.")

ch("05-01", "dl-techniques-and-gap-control", "Defensive Line Play: Techniques, One-Gap and Two-Gap", 3, 12,
   ["Map DL roles to techniques: nose (0/1), 3-technique, 4i, 5-technique, wide-9, edge.",
    "Distinguish one-gap (penetrate) and two-gap (control and read) play.",
    "Explain reactions to down blocks, reaches, and double teams.",
    "Define setting the edge and contain.",
    "Describe line movement: slants and angles."],
   ["one-gap", "two-gap", "3-technique", "4i technique", "5-technique", "wide-9", "set the edge", "contain",
    "penetration", "slant (line movement)", "angle (line movement)"],
   ["03-01", "02-06"],
   ["S: Technique map with archetype silhouettes",
    "A: Two-gap nose controls the center then sheds either way (frame strip)",
    "A: One-gap 3-tech penetrates (frame strip)", "S: Slant and angle movements"],
   ["Vince Wilfork (two-gap nose)", "Warren Sapp / Aaron Donald (3-tech)", "Reggie White", "Wide-9 under Jim Washburn / Jim Schwartz"],
   "Find the 3-technique: before the snap find the DT outside the guard; which way did the run go?")

ch("05-02", "even-fronts", "Even Fronts: 4-3 Over, Under, Wide-9, and the 46 Bear", 3, 13,
   ["Diagram 4-3 Over and Under and their strength rules.",
    "Explain the wide-9 trade-off (pass rush for run lanes).",
    "Diagram the 46 / bear front and why covering the center and both guards wrecks blocking schemes.",
    "Show how even fronts adjust from 21 to 11 personnel.",
    "Identify the front from the broadcast angle."],
   ["even front", "4-3 Over", "4-3 Under", "46 defense", "bear front"],
   ["05-01"],
   ["S: 4-3 Over and Under plates",
    "A: Bear front vs I-form: nobody left to block the backers (frame strip)",
    "S: Wide-9 rush lanes", "S: Under front vs 11 personnel"],
   ["Buddy Ryan's 1985 Bears", "Pete Carroll's Seattle Under", "Jim Schwartz's 2017 Eagles", "Lovie Smith's Bears"],
   "Over or under? Find the 3-tech relative to the TE before each snap.")

ch("05-03", "odd-and-hybrid-fronts", "Odd and Hybrid Fronts: 3-4, Okie, Tite, and Modern Nickel Fronts", 3, 14,
   ["Diagram the 3-4 Okie and contrast two-gap vs one-gap 3-4s.",
    "Explain the tite (mint) front and why it walls off inside runs vs spread offenses.",
    "Diagram nickel fronts: 4-2-5, 3-3-5, 2-4-5.",
    "Explain why front labels blur (stand-up edges, 'multiple' defenses).",
    "Show how a front chooses to defend inside vs outside zone."],
   ["odd front", "3-4 Okie", "tite front (mint)", "4-2-5", "3-3-5", "2-4-5", "stand-up edge (outside linebacker)",
    "multiple (hybrid) defense", "reduced front"],
   ["05-02"],
   ["S: Okie plate", "A: Tite front vs inside zone (frame strip)", "S: 4-2-5 vs 2x2", "S: 2-4-5",
    "A: Same personnel, two fronts: stand-up edge puts hand down (frame strip)"],
   ["Bum Phillips / Fritz Shurmur early 3-4", "Wade Phillips one-gap 3-4 (J.J. Watt Texans, 2015 Broncos)",
    "Fangio tite (2018 Bears, 2024 Eagles)", "Kirby Smart's Georgia"],
   "Count the hands down: three, four, or five? Who is standing on the edge?",
   fwd=["11-01 / 11-02 (3-4 history)"])

ch("05-04", "linebackers-and-second-level", "Linebackers: Keys, Flow, and the Hardest Job on the Field", 3, 12,
   ["Explain alignments (stack, apex, walk-out) and keys (guards, near back).",
    "Explain flow (fast, slow) and fit actions: fill, scrape, plug, run-through.",
    "Describe LB coverage jobs (hook/curl, man on backs, rat/hole) and pressure roles.",
    "Explain the decline of the Sam and the rise of safety-sized linebackers.",
    "Describe the green-dot communicator's job."],
   ["stack alignment", "apex alignment", "walk-out", "key (read key, defense)", "flow (fast / slow)", "fill",
    "scrape", "plug", "run-through", "hook / curl defender"],
   ["05-02", "04-05"],
   ["A: LB key read: guard pulls, Mike flows (frame strip)", "S: Apex alignment vs 2x2",
    "S: Scrape vs zone read", "A: LB conflict on play-action, revisited from 04-05 (frame strip)"],
   ["Ray Lewis", "Luke Kuechly", "Bobby Wagner", "Fred Warner", "Roquan Smith"],
   "Mirror the Mike: watch only the Mike for 10 snaps. First step forward or back?")

ch("05-05", "run-fits-and-box-math", "Run Fits: Gap Integrity, Force, Spill, and Box Math", 4, 15,
   ["Explain run fits and gap integrity: every gap owned.",
    "Distinguish force/contain, spill vs box (squeeze), and the alley player.",
    "Explain the plus-one principle and how safety rotation adds a fitter.",
    "Show fits vs zone, power, and zone read (gap exchange).",
    "Explain two-high light-box run defense and its costs.",
    "Evaluate box count vs EPA with data."],
   ["run fit", "gap integrity", "force (defender)", "spill", "box technique (squeeze)", "alley player",
    "plus-one", "gap exchange", "overhang defender"],
   ["05-04", "03-04"],
   ["S: Full 11-man fit chart vs power", "A: Spill vs box comparison on the same kick-out (frame strips)",
    "S: Plus-one with a rotated safety", "A: Scrape exchange vs zone read (frame strip)",
    "C: EPA/rush by defenders in the box"],
   ["Fangio light-box philosophy", "Ravens 2019 vs light boxes", "2024 Eagles run game vs two-high"],
   "Who's the force? Find the outermost defender each side pre-snap; did the run bounce?")

# ---------------------------------------------------------------- PART 6
part("06", "Pass Coverage", "3-5",
     "From zone vocabulary to the modern disguise game. Each coverage chapter has the same spine: structure, strengths, "
     "holes, pre-snap tells, post-snap tells, and which teams made it famous.")

ch("06-01", "coverage-fundamentals", "Coverage Fundamentals: Zones, Leverage, and Reading the Shell", 3, 14,
   ["Name the zones: flat, curl, hook, hole, deep third, deep half, deep quarter.",
    "Define press, off, bail, cushion, trail, and eye discipline.",
    "Distinguish spot-drop zone, pattern-match, and man.",
    "Read the shell: MOFC vs MOFO, safety depth and width tells.",
    "Decode the Cover 0-6 numbering and its inconsistencies across teams.",
    "Connect coverage rules to the 5-yard contact rule (forward ref 09-03)."],
   ["flat zone", "curl zone", "hook zone", "hole (rat) zone", "deep third", "deep half", "deep quarter", "press",
    "off coverage", "bail", "cushion", "trail technique", "landmark", "spot-drop zone", "pattern matching",
    "MOFC (middle of field closed)", "MOFO (middle of field open)", "coverage numbering (Cover 0-6)"],
   ["04-04", "02-06"],
   ["S: Zone map grid", "S: Press vs off vs bail alignment", "S: MOFC vs MOFO plates",
    "A: Spot-drop vs pattern-match vs the same routes, side by side (frame strips)"],
   ["Seattle press Cover 3", "Tampa 2 Bucs", "Fangio quarters"],
   "One or two? At the snap call MOFC or MOFO; one second later say whether it stayed.",
   fwd=["09-03 (contact rules)"])

ch("06-02", "man-coverage", "Man Coverage: Cover 0, Cover 1, Robbers, and Brackets", 3, 13,
   ["Diagram Cover 1 (man-free), Cover 1 robber/rat, and Cover 0.",
    "Explain man techniques (press-man, off-man, trail) and inside help.",
    "Explain banjo/combo vs stacks and bunches; brackets on stars; shadow corners.",
    "Explain when defenses prefer man (third down, red zone, talent).",
    "Revisit man-beaters (mesh, rubs, slants, double moves)."],
   ["Cover 1 (man-free)", "Cover 0", "robber", "lurk", "banjo", "combo coverage", "bracket", "shadow corner",
    "inside help"],
   ["06-01"],
   ["S: Cover 1 vs 2x2", "S: Cover 0 vs empty", "A: Banjo vs stack release (frame strip)",
    "S: Bracket on #1 in 3x1", "A: Cover 1 rat robbing a dig (frame strip)"],
   ["Patriots Cover 1 & brackets (Ty Law, Stephon Gilmore)", "Spagnuolo's Cover 0", "Darrelle Revis", "Seattle's Richard Sherman (contrast: zone corner)"],
   "Who's facing the QB? Man defenders turn to the receiver; zone defenders read the QB.")

ch("06-03", "cover-3-family", "Cover 3: Sky, Buzz, Cloud, and Seattle's Match Version", 3, 13,
   ["Diagram Cover 3 base (three deep, four under) and the sky, buzz, cloud rotations.",
    "Explain Cover 3's strengths (eight-man front) and holes (seams, curl-flat, flood).",
    "Explain Cover 3 match and how it handles four verticals.",
    "Recognise Cover 3 pre-snap and post-snap."],
   ["Cover 3", "sky rotation", "buzz rotation", "cloud (corner) rotation", "seam-flat defender",
    "curl-flat defender", "Cover 3 match"],
   ["06-01"],
   ["S: Cover 3 sky vs 2x2", "S: Buzz", "S: Cloud",
    "A: Four verticals vs spot-drop Cover 3: the seam opens (frame strip)",
    "A: Four verticals vs Cover 3 match: seam carried (frame strip)"],
   ["Pete Carroll's 2012-2015 Seahawks (Sherman, Thomas, Chancellor)", "Gus Bradley", "Dan Quinn"],
   "Count deep defenders one second after the snap: three means a Cover 3 family call.")

ch("06-04", "cover-2-and-tampa-2", "Cover 2 and Tampa 2", 3, 12,
   ["Diagram Cover 2 zone (two halves, five under) and hard/squat corners.",
    "Explain Tampa 2 (Mike runs the deep middle) and why it existed.",
    "Diagram 2-Man (two-deep, man under).",
    "Locate Cover 2's holes: hole shot, smash corner, deep middle, sideline hole.",
    "Explain why classic Tampa 2 faded and what survived."],
   ["Cover 2", "hard (squat) corner", "hole shot", "Tampa 2", "2-Man (Cover 5)"],
   ["06-03"],
   ["S: Cover 2 vs 2x2", "A: Tampa 2: Mike carries the seam (frame strip)", "S: 2-Man",
    "A: Smash vs Cover 2 (frame strip)"],
   ["Tony Dungy / Monte Kiffin 2002 Bucs", "Dungy's 2006 Colts", "Lovie Smith's 2006 Bears", "Bud Carson's 1970s Steelers Cover 2"],
   "Squat-corner spotter: corners at 5-7 yards, outside leverage, not bailing -> think Cover 2.")

ch("06-05", "quarters-and-match", "Quarters and the Two-High Match Family: Cover 4, Cover 6, Palms", 4, 16,
   ["Diagram Cover 4 (quarters) and its run support (safeties fit off #2).",
    "Explain match rules: MOD, MEG, read-the-#2 safety.",
    "Diagram Cover 6 (quarter-quarter-half) and Palms / 2-read (trap).",
    "Explain why two-high match coverage spread through the NFL 2019-2023.",
    "Identify the weaknesses: light-box runs, flood from boot, RB wheel."],
   ["quarters (Cover 4)", "Cover 6", "Palms (2-read, trap)", "MOD (man only deep)", "MEG (man everywhere he goes)",
    "read safety"],
   ["06-04", "05-05"],
   ["S: Cover 4 vs 2x2 with match responsibilities", "A: Quarters safety fits the run (frame strip)",
    "S: Cover 6 vs 3x1", "A: Palms: corner traps the out (frame strip)",
    "C: League two-high rate by season (charting data where available)"],
   ["Saban/Belichick rip-liz match", "Fangio 2018 Bears", "Brandon Staley 2020 Rams", "Fangio 2024 Eagles",
    "Michigan State / Iowa quarters"],
   "Two-high, now what? Watch both safeties' first steps: backpedal, downhill, or rotate?",
   fwd=["12-08 (Fangio case study)"])

ch("06-06", "disguise-rotation-and-split-field", "Disguise, Rotation, and Split-Field Coverage", 5, 16,
   ["Explain disguise and post-snap rotation (two-high to one-high, one-high to two-high).",
    "List tells: safety depth/width, corner leverage, weight, timing of movement.",
    "Explain split-field coverage and 3x1 checks (poach, solo, stubbie).",
    "Explain how late rotation forces post-snap reading and how offenses respond (motion, tempo, hard counts).",
    "Measure safety movement around the snap with tracking data."],
   ["disguise", "post-snap rotation", "split-field coverage", "Cover 7 (match family)", "poach", "3x1 check (solo / stubbie)",
    "late rotation"],
   ["06-05", "02-05"],
   ["A: Two-high shell rotates to Cover 3 robber at the snap (frame strip)",
    "A: One-high spins to Cover 2 (frame strip)",
    "S: Split-field Cover 6 vs 2x2", "S: Poach vs 3x1",
    "T: Safety depth and lateral position from snap-30 to snap+20 frames (BDB tracking)",
    "C: Pre-snap shell vs post-snap coverage agreement rate by team"],
   ["Fangio 2024 Eagles", "Mike Macdonald 2023 Ravens / 2024-25 Seahawks", "Brian Flores Vikings"],
   "Call it twice: name the coverage pre-snap and again one second after; log how often the defense lied.",
   fwd=["13-05 (tracking data)", "12-08 (Macdonald case study)"])
