# Curriculum data, Parts 1-6
#
# Term syntax: "name | alias | alias". The first part is the glossary headword; every alias gets its
# own "see ..." entry and anchor in the term index (and in the glossary via `aliases:`, AUTHORING §3).
# Parentheses are kept for disambiguators that are not aliases, e.g. "safety (score)".
PARTS = []
CH = []

def part(pid, title, levels, blurb):
    PARTS.append(dict(id=pid, title=title, levels=levels, blurb=blurb))

def ch(cid, slug, title, level, pages, obj, terms, prereq, diagrams, examples, drill, fwd=None,
       notes=None, see=None):
    """pages = planning size unit (rendered as ~375 words each); see = related case-study chapter IDs."""
    CH.append(dict(id=cid, slug=slug, title=title, level=level, pages=pages, obj=obj,
                   terms=terms, prereq=prereq, diagrams=diagrams, examples=examples,
                   drill=drill, fwd=fwd or [], notes=notes or [], see=see or []))

# ---------------------------------------------------------------- PART 1
part("01", "Foundations: The Game Beneath the Broadcast", "1",
     "Everything a casual viewer half-knows, made precise: the field, the clock, downs, the 22 players, "
     "who calls the plays, and, most importantly, what a 'play' actually is in real life versus a Madden play card. "
     "01-02 takes a first baseline guess; 01-06 starts the formal prediction log, the course-long habit that every later chapter sharpens.")

ch("01-01", "the-game-in-fifteen-minutes", "The Game in Fifteen Minutes: Field, Scoring, and Clock", 1, 10,
   ["Read every marking on the field: yard lines, numbers, hash marks, goal line, end zone, sidelines.",
    "Explain the wide (field) side vs short (boundary) side and why the ball's hash position changes play design.",
    "Score every way points are made (TD, PAT, two-point try, field goal, safety) and why 7-vs-3 is the game's central tension.",
    "Explain when the game clock runs and stops (incompletions, out of bounds, scores, change of possession, two-minute warning); "
    "note that out of bounds stops it only briefly except late in each half (full rule in 10-04).",
    "Distinguish the game clock from the play clock (40 / 25 seconds).",
    "Describe the shape of a game: kickoff, possessions, quarters, halftime, overtime (details deferred to 10-04)."],
   ["end zone", "goal line", "yard line", "hash marks", "field side | wide side", "boundary side | short side",
    "sideline", "touchdown", "extra point | PAT", "two-point conversion", "field goal", "safety (score)",
    "possession", "quarter", "two-minute warning", "timeout", "game clock", "play clock"],
   [],
   ["S: Full field overhead, every marking labelled; ball on left hash with field/boundary shaded",
    "S: NFL vs college hash width side-by-side (why college has a much bigger wide side)",
    "S: Scoring summary card (6/1/2/3/2 with where each happens)",
    "S: Clock flowchart: 'after this play, does the clock run?'"],
   ["Walk-through of Super Bowl LIX (Eagles 40-22 Chiefs) scoring plays located on the field diagram"],
   "Clock watcher: for one quarter, before each snap say aloud whether the clock is running and why.",
   fwd=["10-04 (overtime, the out-of-bounds clock rule, and clock strategy in depth)"])

ch("01-02", "downs-distance-and-field-position", "Downs, Distance, and Field Position", 1, 11,
   ["Explain four downs, the line to gain, and why teams usually punt on fourth down.",
    "Read the on-screen down-and-distance graphic and bucket it as short, medium, or long.",
    "Define the line of scrimmage, the spot, and the chain crew / sticks (chains are now a backup to the 2025 virtual measurement, 09-04).",
    "Explain turnovers (interception, fumble, turnover on downs) and the sack.",
    "Treat field position as a currency: expected points (EP) as the value of a down, distance, and yard line.",
    "Read EPA and success rate as a per-play scorecard: what the number means, not how it is modelled.",
    "Define a drive and the red zone."],
   ["down", "line to gain", "first down", "line of scrimmage", "spot (of the ball)", "the sticks | chains",
    "turnover", "interception", "fumble", "turnover on downs", "sack", "punt", "field position",
    "expected points | EP", "EPA | expected points added", "success rate", "drive (possession)", "red zone"],
   ["01-01"],
   ["A: Series of downs: 1st & 10 -> 2nd & 6 -> 3rd & 2 -> first down, chains moving (frame strip)",
    "S: Field-position map: own territory / midfield / opponent territory / red zone",
    "S: EPA scorecard: one real drive, EP before and after each play, EPA and success marked",
    "C: League 3rd-down conversion % by yards to go (nflverse, 2016-2025), code folded"],
   ["League-average conversion rates",
    "Super Bowl XXXIV 'One Yard Short' (Titans-Rams) as a last-play stop, not a 4th-down stop: 6 seconds left, ball at the Rams 10, Kevin Dyson tackled at the 1",
    "A true 4th-down stop, e.g. the Super Bowl XLVII goal-line stand (verify first)"],
   "Down-and-distance forecaster: before each snap predict run or pass from down & distance alone; tally hit rate. "
   "This is your baseline; the formal prediction log starts in 01-06.",
   fwd=["13-02 (the EP model, its stability, and selection-effect caveats)", "09-04 (virtual measurement)"],
   notes=["EPA primer only (audit M2): define EP, EPA, and success rate in plain words with one worked drive; no model. "
          "Every later EPA chart (03-02, 03-04, 04-01, 04-04, 04-05, 05-05, 07-02, 10-01, ...) leans on this section."])

ch("01-03", "the-twenty-two", "The Twenty-Two: Every Position and What It Actually Does", 1, 14,
   ["Name the offensive positions and their jobs: QB, RB/HB, FB, WR (X/Z/slot), TE, OL (C, G, T).",
    "Name the defensive positions: DT/NT, DE/edge, LB (Mike, Will, Sam), CB, slot corner, FS, SS.",
    "Name the special-teams specialists: K, P, LS, holder, returner, gunner.",
    "Distinguish eligible from ineligible receivers and the jersey-number convention (2021 change; #0 and wider ranges from 2023).",
    "Explain why body types map to jobs (combine data).",
    "Separate position (who you are) from alignment and assignment (what you do this play)."],
   ["quarterback", "running back | halfback", "fullback", "wide receiver", "tight end", "offensive line",
    "center", "guard", "tackle (position)", "defensive tackle", "nose tackle", "defensive end", "edge rusher",
    "linebacker", "Mike linebacker", "Will linebacker", "Sam linebacker", "cornerback", "slot cornerback | nickel back",
    "safety (position)", "free safety", "strong safety", "kicker", "punter", "long snapper", "holder", "returner",
    "gunner", "eligible receiver", "ineligible receiver", "skill positions", "front seven", "secondary",
    "alignment", "assignment"],
   ["01-01"],
   ["S: Offense (two-back) vs a base 4-3 defense, every position labelled",
    "S: 11 personnel vs nickel, same labels (teaser for 02-01 / 02-05)",
    "C: Height/weight scatter by position from combine data",
    "S: Jersey-number ranges after the 2021 and 2023 numbering changes"],
   ["Kyle Juszczyk (FB)", "Travis Kelce (TE)", "Penei Sewell (T)", "Aaron Donald (DT; retired after 2023, used as an archetype)",
    "T.J. Watt (edge)", "Fred Warner (LB)", "Kyle Hamilton (S)"],
   "One-player game: watch only the center for an entire drive and narrate what he did each play.",
   fwd=["02-01 (personnel labels such as '11')", "02-05 (packages: base 4-3, nickel)"])

ch("01-04", "what-a-play-really-is", "What a Play Really Is (It Isn't Picking a Card in Madden)", 1, 15,
   ["Trace the real chain: call sheet -> play-caller -> helmet radio -> QB / green-dot defender -> huddle or signals -> snap.",
    "Map the staff: who calls plays (head coach as caller vs coordinator), booth vs sideline, position coaches, QC and analytics staff.",
    "Decompose a play call into formation, motion, protection, concept, and tags.",
    "Explain the 40-second play clock, the radio cut-off at 15 seconds, and delay of game.",
    "Explain why both play-callers call blind and simultaneously, and why that creates the pre-snap contest.",
    "Contrast Madden with reality: 11 people executing rules, reads after the snap, one call = a family of outcomes.",
    "Explain huddle vs no-huddle, wristbands, and sideline signal boards.",
    "Describe what happens in the 3-7 seconds after the snap: assignments, reads, adjustments."],
   ["play call", "call sheet", "head coach", "offensive coordinator | OC", "defensive coordinator | DC",
    "special teams coordinator", "play-caller", "position coach", "quality control coach | QC coach",
    "analytics staff | game-management staff",
    "helmet radio (coach-to-player communication)", "green dot", "huddle", "no-huddle",
    "wristband", "delay of game", "snap", "read (post-snap)", "verbiage | terminology", "tag", "playbook", "install"],
   ["01-02", "01-03"],
   ["A: Play-clock timeline: whistle -> call in -> radio cuts at 15 -> huddle break -> set -> snap (frame strip)",
    "S: The staff map: HC, coordinators, booth vs sideline, position coaches, QC, analytics",
    "S: Communication flow: play-caller -> QB/green dot -> teammates",
    "S: Anatomy of a play call: one long call split into labelled chunks",
    "S: Madden play art vs a coach's diagram of the same idea (rules, options, reads)",
    "A: One play from huddle break to whistle, every player's assignment highlighted in turn"],
   ["Shanahan/McVay-style long verbal calls vs Erhardt-Perkins one-word concepts (teaser for 04-08)",
    "Who calls plays, labelled by season: Kyle Shanahan (49ers) and Ben Johnson (Bears, 2025-) call their own; "
    "Dan Campbell took over Lions play-calling midway through 2025 (FACTS-current §9)",
    "Peyton Manning's 'Omaha' era", "Chiefs and wristband offenses", "Bills' sugar huddle"],
   "Huddle stopwatch: time whistle-to-snap for several drives; note who huddles, who doesn't, and who snaps with under 5 seconds on the play clock.",
   fwd=["04-02 (protection)", "04-04 (pass concepts)", "04-08 (play-calling languages)", "08-03 (the staff's week)",
        "08-04 (tempo; the sugar huddle)"],
   notes=["Pilot chapter. Jargon test: protection, concept, tag, tempo, and green dot each get a one-line gloss and a forward link.",
          "Use the 'Madden vs. real life' callout for who calls the play."])

ch("01-05", "the-pre-snap-phase", "The Pre-Snap Phase: Shifts, Motion, Cadence, and Audibles", 2, 12,
   ["Define set, shift, and motion and the legal-motion rules (one man moving, not toward the line at the snap; one-second set after a shift).",
    "Explain cadence and hard counts and the penalties they draw (offside, encroachment, neutral zone infraction, false start).",
    "Define audibles, checks, kill calls, and check-with-me systems.",
    "Know that the offense names a reference defender before the snap so everyone blocks the same men (full treatment in 04-02).",
    "Recognise defensive pre-snap movement: shifting fronts, safeties walking down, linebackers showing blitz (gloss: more than four rushers; defined in 02-05).",
    "List what each side is trying to learn before the snap."],
   ["set", "shift", "motion", "false start", "offside", "encroachment", "neutral zone infraction", "illegal motion",
    "cadence | snap count", "hard count", "silent count", "audible", "check", "kill call", "check-with-me",
    "dummy call"],
   ["01-04"],
   ["S: Legal vs illegal motion side by side",
    "A: Shift: TE crosses formation, everyone resets one second (frame strip)",
    "S: Kill call: two plays called; the QB picks one after counting the defenders near the line",
    "A: Defense moves pre-snap: safety walks down, linebacker walks into the gap between center and guard"],
   ["Peyton Manning pre-snap theatre", "Aaron Rodgers' hard count free plays", "Eagles' silent count at home vs on the road"],
   "Count the movement: after the huddle breaks, count offensive players who move before the snap and whether any defender moves with them.",
   fwd=["02-05 (blitz; counting the box)", "02-06 (motion as a man/zone indicator)", "03-01 (gap names such as the A-gap)",
        "04-02 (Mike identification and protection)", "07-02 (A-gap mugs and protection)"])

ch("01-06", "how-to-watch-a-broadcast", "How to Watch a Broadcast Like You Mean It", 1, 10,
   ["Know what the broadcast camera hides (safeties, receivers downfield) and what replays, skycam, and end-zone angles reveal.",
    "Use the pre-snap pause: read down, distance, clock, score, and timeouts in under five seconds.",
    "Adopt the 'watch one thing' strategy by play type.",
    "Read broadcast graphics (win-probability bars, Next Gen Stats overlays) as glossed numbers; the models come in 13-03 and 13-05.",
    "Start a tells catalogue: stance, RB depth and offset, receiver splits, safety depth (each a clue, never a guarantee).",
    "Set up the formal prediction log used for the rest of the course (01-02's tally was the baseline)."],
   ["All-22", "end-zone camera", "sideline camera", "skycam", "coaches film", "tell", "stance (two-point / three-point)",
    "heavy hand | heavy stance", "prediction log"],
   ["01-05"],
   ["S: Broadcast frame vs All-22 frame, field coverage shaded",
    "S: 'Where to look' by phase: pre-snap, first second, ball in air",
    "S: Tells starter card: stance, RB depth/offset, splits, safety depth",
    "S: Prediction-log template (paper and a 10-line pandas version)"],
   ["NFL+ Premium (All-22 access)", "Prime Vision alternate broadcast", "Typical replay sequence on a big play"],
   "Prediction log, game 1: for one half log run/pass guess and outcome; compute accuracy (compare to the 01-02 baseline).",
   fwd=["13-03 (win probability)", "13-05 (Next Gen Stats and tracking)", "15-01 (the full tells catalogue)",
        "15-02 (All-22 film study in depth)"])

# ---------------------------------------------------------------- PART 2
part("02", "Personnel and Formations: Reading the Offense Before the Snap", "1-3",
     "Who is on the field and where they stand. Personnel and formation are the first two clues of every pre-snap read. "
     "A deliberately shallow first look at defense (packages, the box, man vs zone, one-high vs two-high, the blitz) comes "
     "before motion, because motion's job is to make the defense reveal those things; it also lets Parts 3-4 talk about "
     "defenders without waiting for Parts 5-6.")

ch("02-01", "personnel-groupings", "Personnel: Who's on the Field Before Anything Else", 1, 11,
   ["Decode two-digit personnel (RBs then TEs; WRs = 5 - RB - TE): 11, 12, 21, 13, 22, 10, 20, 00.",
    "Explain why personnel is the first pre-snap clue and how it forces the defense's substitution.",
    "Explain substitution rules: the defense gets to match when the offense subs.",
    "Read league personnel trends 2016-2025 (rise of 11; in 2025 11 fell to a decade low and 12 rose to a decade high).",
    "Link personnel to run/pass tendencies with real data."],
   ["personnel grouping", "11 personnel", "12 personnel", "21 personnel", "13 personnel", "22 personnel",
    "10 personnel", "substitution matching", "heavy personnel", "jumbo (six offensive linemen)"],
   ["01-03", "01-06"],
   ["S: Personnel card deck: one neutral-alignment plate per grouping",
    "A: Offense subs in 12; defense swaps a DB for a LB (frame strip)",
    "C: League personnel share by season, 2016-2025",
    "C: Pass rate by personnel grouping (neutral situations: glossed here as 'not late, not lopsided'; defined in 13-04)"],
   ["McVay Rams 11 personnel (2017-2019)", "49ers 21 personnel with Juszczyk", "Ravens 2019 heavy sets",
    "Eagles 2024 12 personnel with Saquon Barkley", "Lions six-OL jumbo with an eligible tackle (2022-2024)"],
   "Call the personnel: count RBs and TEs before each snap, say the number, then guess run/pass from the personnel chart.",
   fwd=["02-02 (reporting eligible: the eligible tackle)", "13-04 (neutral situations)"],
   notes=["Trend numbers with sources (FACTS-current §10): nflverse 11-personnel share 58.8% in 2025 (decade low), "
          "12 personnel 24.4% (decade high); NGS: fewer than three WRs on 41.7% of 2025 plays; defenses in base 29.7% (2025) vs 20.5% (2023). "
          "Never put NGS and nflverse series on one axis.",
          "Participation personnel strings change format in 2023 (NGS -> FTN source break); normalise before charting."])

ch("02-02", "formation-rules-and-vocabulary", "Formation Rules and the Language of Alignment", 2, 12,
   ["Apply formation legality: seven on the line, ends eligible, covered receivers, illegal formation.",
    "Define formation strength and how each side declares it (TE side, receiver side, field side).",
    "Use the receiver labels X, Y, Z, H/F plus slot, wing, flanker, split end, in-line, off-ball.",
    "Describe QB/backfield alignments: under center, shotgun, pistol, offset, sidecar.",
    "Read splits (wide, normal, reduced, tight) and alignment landmarks (the numbers, the hash).",
    "Explain how an ineligible-numbered player reports eligible, the Patriots' January 2015 trick, and the 2015 reporting rule."],
   ["on the line / off the line", "covered receiver", "illegal formation", "formation strength", "strong side",
    "weak side", "X receiver | split end", "Z receiver | flanker", "Y receiver", "H / F (move player)", "slot",
    "wing", "in-line tight end", "under center", "shotgun", "pistol", "offset back", "split (receiver split)",
    "reduced split", "the numbers (alignment landmark)", "reporting eligible", "eligible tackle | tackle-eligible"],
   ["02-01"],
   ["S: Legal vs illegal (six on the line; TE covered by a WR)",
    "S: Label map: X/Y/Z/H/F on a 2x2 and on a 3x1",
    "S: QB depth comparison: under center / pistol / shotgun with typical depths",
    "S: Split ladder: wide -> numbers -> reduced -> tight",
    "S: Strength declaration examples (TE strength vs passing strength vs field)",
    "S: Reporting eligible: a lineman reports to the referee and lines up at the end of the line"],
   ["Patriots' ineligible-receiver formations vs Ravens (Jan 10, 2015, the 2014-season divisional round) and the rule change for the 2015 season",
    "Lions jumbo with an eligible tackle (Ben Johnson era)"],
   "Strength caller: name the strong side before each snap, then watch which way the defense set its front.",
   notes=["Keep the season (2014) and the calendar year of the game (January 2015) distinct."])

ch("02-03", "classic-formations", "Classic Formations: I, Power I, Pro Set, Singleback, and Their Ancestors", 2, 11,
   ["Identify I-form, offset I, Power I, pro set (split backs), singleback, ace, T, wishbone, flexbone, Wing-T, jumbo/goal line.",
    "Explain each formation's purpose: lead blocker, downhill angles, balance, misdirection.",
    "Explain why two-back, under-center formations declined and where they survive (21 personnel, short yardage, play-action).",
    "Match each formation to its typical personnel."],
   ["I-formation", "offset I", "Power I", "pro set | split backs", "singleback", "ace formation", "T-formation",
    "wishbone", "flexbone", "Wing-T", "goal-line formation", "full house backfield"],
   ["02-02"],
   ["S: Atlas plates for each classic formation (11 plates, consistent style)",
    "C: Under-center vs shotgun share 2006-2025",
    "S: Family tree: T -> wishbone / flexbone / I / pro set"],
   ["Lombardi Packers pro set", "Joe Gibbs' one-back/ace Redskins", "49ers 21 personnel I-form",
    "Ravens 2024 with Patrick Ricard at FB", "Navy / Georgia Tech flexbone"],
   "Name that formation: for 10 snaps name the formation, under center or gun, one back or two.",
   fwd=["11-03 (the wishbone and flexbone lineage)"],
   notes=["Under-center share: FTN qb_location == 'U' was 31.6% (2022) -> 33.6% (2025); pbp shotgun share fell from 72.2% (2023) "
          "to 66.2% (2025) (FACTS-current §10). Reproduce in 13-01 code; don't hard-code."])

ch("02-04", "spread-and-modern-formations", "Spread Formations: 2x2, Trips, Bunch, Empty, and the Condensed Revolution", 2, 12,
   ["Identify 2x2 (doubles), 3x1 (trips), empty (3x2), bunch, stack, nub, quads.",
    "Explain why spreading the field forces the defense to declare itself and creates space.",
    "Explain condensed/tight splits and why modern offenses use them (crack blocks, a two-way go for the receiver, rubs).",
    "Recognise specialty looks: wildcat, unbalanced (tackle over), swinging gate."],
   ["2x2 | doubles", "3x1 | trips", "empty | 3x2", "bunch", "stack", "nub", "quads", "condensed formation",
    "two-way go", "wildcat", "unbalanced line | tackle over", "swinging gate"],
   ["02-02"],
   ["S: Atlas plates for each spread formation",
    "S: Wide vs condensed split: same play, space created shaded",
    "S: Two-way go: a receiver with room to break inside or outside",
    "C: Formation usage trend (shotgun 2x2 / 3x1 / empty) by season"],
   ["2007 Patriots spread (Brady, Moss, Welker)", "2018 Rams condensed 3x1", "2008 Dolphins Wildcat",
    "Bills empty with Josh Allen", "Chiefs bunch sets"],
   "Formation & leverage: name the formation, then count receivers vs defenders on each side.",
   fwd=["03-05 (crack blocks)", "04-04 (rub routes)"],
   notes=["Formation labels in participation data change at the 2022/2023 source break (2023+: only SHOTGUN, UNDER CENTER, PISTOL). "
          "Build the 2x2/3x1/empty trend from FTN or BDB fields, not offense_formation."])

ch("02-05", "a-first-look-at-defense", "A First Look at Defense: Packages, the Box, Man vs Zone, One-High vs Two-High, and the Blitz", 2, 13,
   ["Name defensive packages (base 4-3 / 3-4, nickel, dime, quarter/dollar, big nickel, goal line) and where 'nickel' and 'dime' come from.",
    "Count the box, explain why box count drives run/pass choices, and name the apex/overhang defender who stands between the box and a slot receiver.",
    "Distinguish man and zone coverage at the concept level.",
    "Distinguish one-high and two-high safety shells and what each is good at.",
    "Define a blitz (5+ rushers) vs a four-man rush; preview Part 7.",
    "Explain why nickel is the modern NFL base defense.",
    "Signpost what comes later: fronts (Part 5), coverages (Part 6), pressure (Part 7)."],
   ["defensive package", "base defense", "4-3", "3-4", "nickel", "dime", "quarter (package) | dollar", "big nickel",
    "box", "box count", "light box", "loaded box", "apex | apex alignment", "overhang defender | overhanger",
    "man coverage", "zone coverage", "one-high | single-high", "two-high | split-safety", "shell (coverage shell)",
    "blitz", "four-man rush"],
   ["02-01", "01-03"],
   ["S: Package plates: base / nickel / dime vs 11 personnel",
    "S: The box: tackle-to-tackle, ~5-7 yards deep, with counting examples; the apex defender between box and slot",
    "S: One-high vs two-high silhouettes",
    "A: Same two routes vs man and vs zone (frame strip)",
    "S: Four-man rush vs a five-man blitz, same look",
    "C: Share of defensive snaps in nickel or lighter, by season"],
   ["Belichick dime vs pass-heavy offenses", "Ravens big nickel with Kyle Hamilton", "Lions/Packers nickel as base",
    "Base defense rebounded to 29.7% of snaps in 2025 from a 20.5% low in 2023 (NGS; FACTS-current §10)"],
   "Box and shell: every snap count the box and say one-high or two-high; log alongside run/pass.",
   fwd=["Part 5 (fronts)", "Part 6 (coverages)", "Part 7 (pressure)",
        "05-02 / 05-03 (what 4-3 and 3-4 really mean; Appendix C comparison card)"],
   notes=["Single home for apex and overhang (audit M19): 04-06 uses them as the RPO read; 05-04/05-05 deepen without redefining."])

ch("02-06", "motion-and-shifts", "Motion and Shifts as Weapons", 3, 13,
   ["Distinguish jet, orbit, fly, return (yo-yo), zoom, glide, trade, short (rip/liz) and rocket motion, shift-to-bunch, and motion at the snap.",
    "Explain what motion does: reveals man vs zone, changes strength, creates leverage, gives a running start, stresses communication.",
    "Explain the NFL motion-at-the-snap rule vs college/CFL differences.",
    "Describe the 2023-2025 motion boom with data, and why motion series disagree (PFF shift/motion vs FTN is_motion vs ESPN motion at the snap).",
    "Name defensive responses: travel (man), bump/slide (zone), spin (safety rotation).",
    "Checklist so far (Parts 1-2): situation -> personnel -> formation/strength -> motion response -> box -> shell."],
   ["jet motion", "orbit motion", "return motion | yo-yo motion | yo-yo", "fly motion", "zoom motion", "glide motion",
    "trade (TE trade)", "short motion | rip/liz motion", "rocket motion | rock motion", "motion at the snap",
    "man/zone indicator", "bump (defensive adjustment)", "travel (man defender follows motion)", "spin (safety rotation on motion)"],
   ["02-04", "01-05", "02-05"],
   ["S: Motion family plate (jet, orbit, fly, return, zoom, glide, trade, short, rocket)",
    "A: Jet motion vs man: the corner runs across (frame strip)",
    "A: Same jet motion vs zone: defenders bump, safety spins (frame strip)",
    "C: Motion rate by team, 2022-2025 (FTN is_motion)",
    "S: Checklist-so-far card (Parts 1-2)"],
   ["Mike McDaniel's 2023 Dolphins (Tyreek Hill motion at the snap)", "Shanahan 49ers (Deebo Samuel)",
    "McVay Rams", "Chiefs orbit motion"],
   "Follow the motion: when a receiver motions, watch who follows; call man or zone; check after the play.",
   fwd=["06-06 (disguise defeats the motion indicator)", "13-04 (measuring motion tendencies)"],
   notes=["FTN is_motion means 'motion occurred before or at the snap': not motion-at-the-snap only, and not PFF's shift/motion rate. "
          "FTN 2022-2025: 37.6%, 45.2%, 49.3%, 55.1%. PFF shift/motion 2025: 63.9%. ESPN motion at the snap ~4% (2017) -> ~25% (2024) is LIKELY; "
          "re-check before quoting (FACTS-current §10). Never mix series on one axis.",
          "Part-end card (audit S8): close the chapter with the 'checklist so far' card; it grows at the end of Parts 4, 6, and 7."])

# ---------------------------------------------------------------- PART 3
part("03", "The Run Game", "2-3",
     "How offenses run the ball: the vocabulary of gaps and blocks, then the two great blocking families (zone and gap), "
     "option football, and misdirection. Defensive front names appear in diagrams with forward references to Part 5. "
     "Less common blocks (log, cut, seal, crack) arrive as 'new block' boxes in the chapter that first needs them.")

ch("03-01", "run-game-language", "The Language of the Run Game: Gaps, Techniques, and Blocks", 2, 13,
   ["Label gaps A-D and the common hole-numbering system.",
    "Describe defensive alignments with technique numbers (0, 1, 2i, 2, 3, 4i, 4, 5, 6, 7, 9), including the 3-, 4i- and 5-technique.",
    "Define the core blocks: drive, down, reach, cut-off, combo, pull, kick-out, lead (log, cut, seal, and crack come later as 'new block' boxes).",
    "Use covered/uncovered linemen and 'hat on a hat' arithmetic.",
    "Explain why a non-running QB leaves the offense a defender short.",
    "Contrast zone and gap philosophies at a high level."],
   ["gap (A, B, C, D)", "hole numbering", "technique (alignment number)", "shade", "head-up", "3-technique",
    "4i technique", "5-technique", "drive block", "down block", "reach block", "cut-off block", "combo block | double team",
    "pull", "kick-out", "lead block", "covered / uncovered lineman", "point of attack",
    "playside / backside", "hat math (numbers advantage)"],
   ["02-03", "02-05"],
   ["S: Master gap & technique chart",
    "S: Block library plate (the eight core blocks, one mini-diagram each)",
    "S: Hat math: seven in the box vs six blockers + RB",
    "A: Combo block: guard and center double the 1-tech, one climbs to the Mike (frame strip)"],
   ["Joe Gibbs' Hogs", "Jason Kelce as a climbing/pulling center", "Lions OL (Sewell, Ragnow)"],
   "Find the hole: predict the gap from the RB's first step; afterwards name the gap he actually hit.",
   fwd=["05-01 (technique numbers from the defense's side)"],
   see=["12-06"])

ch("03-02", "zone-running", "Zone Running: Inside Zone, Outside Zone, Split Zone, and the Cutback", 3, 17,
   ["Explain zone rules: step playside, covered/uncovered, combo to the second level.",
    "Distinguish inside zone, outside (wide) zone, stretch, and split zone (inside zone with a backside kick by the H/TE) by aiming point and intent.",
    "Add the common zone tags: bash, insert, arc.",
    "Explain the RB's bang-bend-bounce read and the one-cut style.",
    "Explain the cutback and the backside cut-off (new block: the cut block, and why it is controversial).",
    "Show why wide zone pairs with bootleg play-action.",
    "Evaluate zone efficiency with nflverse rushing EPA by run location (EPA as defined in 01-02)."],
   ["zone blocking", "inside zone", "outside zone | wide zone", "stretch", "split zone", "bash", "insert (zone insert)",
    "arc block", "aiming point", "bang-bend-bounce", "cutback", "backside cut-off", "cut block", "one-cut runner",
    "reach-and-overtake"],
   ["03-01"],
   ["S: Inside zone vs an even front (generic label; front name in 05-02)",
    "A: Outside zone vs an even front, all 11 assignments (frame strip, 6-8 frames)",
    "S: Same outside zone vs an odd front: the rules adapt",
    "S: Split zone: the H kicks the backside end",
    "S: Zone tags: bash, insert, arc",
    "S: RB decision tree: bang / bend / bounce",
    "C: EPA per rush by run location, 49ers vs league, 2019-2025"],
   ["Alex Gibbs & Mike Shanahan's Broncos (Terrell Davis, 1996-98)", "Kyle Shanahan's 49ers (Christian McCaffrey 2023)",
    "McVay Rams", "LaFleur Packers", "Klint Kubiak's 2025 Seahawks (a single season: Kubiak became Raiders head coach in 2026)"],
   "Bang, bend, bounce: on every zone run, call which option the RB took and where the backside end was.",
   fwd=["05-02 (front names)", "04-05 (bootleg play-action)", "09-03 (chop and cut-block legality)", "12-03 (Shanahan case study)"],
   notes=["Pilot chapter. Its EPA chart depends on the 01-02 EPA primer."],
   see=["12-03"])

ch("03-03", "gap-and-power-runs", "Gap Schemes: Power, Counter, Duo, Trap, Wham, Iso, and the Draw", 3, 16,
   ["Explain gap schemes: down blocks, pullers, kick-outs, and wraps (new block: the log).",
    "Diagram power, counter, duo, trap, wham, iso, toss/sweep, pin-and-pull, and the draw.",
    "Explain how gap schemes manufacture extra blockers at the point of attack.",
    "Know when coaches choose gap vs zone (front, personnel, OL body types).",
    "Spot pre-snap tells of a pulling lineman."],
   ["gap scheme | man/power blocking", "power | Power O", "counter | counter trey | GT counter", "duo", "trap", "wham",
    "iso | isolation", "toss / sweep", "pin-and-pull", "puller", "log block | wrap", "draw play | draw"],
   ["03-01"],
   ["S: Power vs 4-3 Over",
    "A: Counter (GT) vs even front, guard kicks out and tackle wraps (frame strip)",
    "S: Duo vs two-high", "S: Trap vs a 3-technique", "S: Wham: the TE/H blocks the 3-technique from the side",
    "S: Iso vs 4-3", "S: Pin-and-pull vs wide front", "S: Draw vs a four-man pass rush"],
   ["Gibbs Redskins counter trey (John Riggins era)", "Lombardi's power sweep as ancestor of pin-and-pull",
    "Titans Derrick Henry duo/power", "Ravens 2019 gap game", "Eagles 2024 with Saquon Barkley"],
   "Follow the guard: watch the backside guard; if he pulls, call gap scheme and its direction.",
   fwd=["05-05 (how defenses fit gap runs)"],
   see=["12-05", "12-06"])

ch("03-04", "option-football", "Option Football: Reading Defenders Instead of Blocking Them", 3, 15,
   ["Explain the option principle: leave the end man on the line of scrimmage (EMOLOS) unblocked, read him, gain a man.",
    "Diagram zone read, inverted veer (power read), speed option, triple option, midline.",
    "Explain dive / keep / pitch roles and the QB's read key.",
    "Explain designed QB runs (QB power, QB counter, QB draw, QB sweep) as blocker-count changers.",
    "Name defensive answers (scrape exchange, gap exchange) with a forward reference to 05-05.",
    "Explain the NFL's on-and-off relationship with option (2012 wave, fade, Lamar/Hurts/Allen era)."],
   ["option", "end man on the line of scrimmage | EMOLOS | EMOL", "read key | read defender", "zone read", "give / keep",
    "inverted veer | power read", "speed option", "triple option", "dive", "pitch", "midline option", "veer",
    "QB power", "QB counter", "QB draw", "QB sweep", "scrape exchange"],
   ["03-02", "03-03"],
   ["A: Zone read, two branches: end crashes (keep) vs end stays (give) (frame strips)",
    "S: Triple option from the flexbone (formation from 02-03)", "S: Inverted veer", "S: Speed option",
    "S: QB power with RB as lead blocker",
    "C: Designed QB run EPA vs RB run EPA, 2016-2025"],
   ["2012 Washington (RGIII, pistol zone read)", "Kaepernick 49ers", "Ravens 2019 rushing record with Lamar",
    "Jalen Hurts' Eagles", "Navy / Georgia Tech flexbone", "Nevada pistol (Chris Ault)"],
   "Find the read key: on read looks, locate the EMOLOS and predict give/keep from his first step.",
   fwd=["05-05 (defending option)", "11-03 (college origins)", "12-05 (Ravens case study)"],
   see=["12-05", "12-06"])

ch("03-05", "perimeter-and-misdirection", "Perimeter Runs and Misdirection: Jet Sweeps, Reverses, and the Wing-T's Children", 3, 12,
   ["Explain jet sweep, end-around, reverse, crack-toss, and buck sweep and how each punishes over-pursuit.",
    "Use the perimeter blocks (new blocks: crack and seal) that make outside runs work.",
    "Understand the Wing-T's series logic (buck sweep, trap, belly, waggle) and its NFL descendants.",
    "Explain 'eye candy': motion and backfield action that freeze linebackers.",
    "Connect misdirection to constraint theory (forward reference 08-02)."],
   ["jet sweep", "end-around", "reverse", "crack-toss", "crack block", "seal block", "buck sweep", "series football",
    "misdirection", "eye candy", "waggle"],
   ["03-03", "02-06"],
   ["S: Wing-T buck sweep", "A: Jet sweep with LB flow shown (frame strip)", "S: Crack-toss: the crack and the seal",
    "S: Reverse",
    "A: Eye candy: jet fake freezes the Mike for 0.5s, inside run hits (frame strip)"],
   ["Delaware Wing-T (Tubby Raymond)", "Gus Malzahn", "2018 Rams jet motion", "49ers Deebo Samuel", "Chiefs shovel/jet packages"],
   "Watch the second level: on jet motion, watch the linebackers' eyes and feet. Did they chase?",
   fwd=["08-02 (constraint theory)", "04-05 (waggle -> bootleg)"],
   see=["12-03", "12-04"])

# ---------------------------------------------------------------- PART 4
part("04", "The Passing Game", "2-4",
     "Routes, timing, protection, the major concept families, play-action and screens, RPOs, quarterback play, and "
     "the languages coaches use. Concepts are taught as stretches of generic defenders; the explicit "
     "'what beats what' matrix, and how the quarterback reads coverage, wait until coverages are taught (08-01).")

ch("04-01", "passing-fundamentals", "Passing Game Fundamentals: Routes, Timing, and Reads", 2, 14,
   ["Use the numbered route tree and common non-tree routes (seam, wheel, whip, option/choice, sluggo).",
    "Link drop depth to route depth (3/5/7-step under center; 1/3/5 from shotgun) and timing.",
    "Distinguish progression reads from defender reads; full-field vs half-field.",
    "Explain vertical (high-low) and horizontal stretches of a single defender.",
    "Define air yards, YAC, and average depth of target."],
   ["route tree", "flat route", "slant", "hitch | curl route", "out", "dig | in route", "corner route", "post",
    "go route | fly route | 9 route", "comeback", "wheel", "seam", "option route | choice route", "whip", "sluggo",
    "drop (3/5/7-step)", "timing route", "progression", "high-low read | vertical stretch", "horizontal stretch",
    "conflict defender", "air yards", "YAC | yards after catch", "aDOT | average depth of target"],
   ["02-04", "02-05"],
   ["S: Route tree with numbers", "S: Drop-to-route timing chart",
    "A: High-low stretch of a flat defender, both branches (frame strip)", "S: Horizontal stretch of a hook defender",
    "C: Completion % and EPA by target depth"],
   ["Route-tree numbering, popularized by the Gillman-Coryell lineage (numbering varies by system)", "Walsh timing passing",
    "Mahomes off-platform vs Brady rhythm"],
   "Route caller: on replays, name every receiver's route.",
   fwd=["06-01 (zones the routes attack)", "08-01 (what beats what)"],
   see=["12-01"])

ch("04-02", "pass-protection", "Pass Protection: Slides, Man Schemes, and Who Blocks the Extra Guy", 3, 16,
   ["Explain five-, six-, and seven-man protections: slide, man (BOB), half-slide, max protect, scat (six with a free-releasing back), and empty (five-man).",
    "Define RB/TE protection roles: check-release, chip.",
    "Explain hot routes and sight adjustments when rushers outnumber blockers.",
    "Explain Mike identification: why naming a reference defender sets every blocker's assignment.",
    "Describe pocket geometry and OL technique: depth, launch point, step-up; kick slide, vertical vs jump sets, punch and anchor.",
    "Explain how linemen pass off stunts and twists (switch vs stay).",
    "Read protection metrics: pressure (and QB hits/hurries), pressure rate, time to throw, sack rate."],
   ["slide protection", "man protection | BOB | big-on-big", "half-slide", "max protect", "scat protection",
    "empty protection (five-man)", "chip", "check-release", "hot route", "sight adjust", "free rusher",
    "Mike identification | MIKE ID", "pocket", "launch point", "kick slide", "vertical set", "jump set", "punch", "anchor",
    "pass-off (switch vs stay)", "pressure", "QB hit / hurry", "time to throw", "pressure rate"],
   ["04-01", "03-01", "01-05"],
   ["S: Half-slide vs four-man rush",
    "A: Six-man protection; RB picks up a blitzing LB (frame strip)",
    "S: Five blockers vs six rushers -> hot throw",
    "A: Pass-off: guard and tackle switch on a T-E stunt (frame strip)",
    "T: Pocket shape over time from tracking data (convex hull of OL), frame strip",
    "C: Sack rate vs time to throw, team-season scatter"],
   ["Patriots protection calls",
    "Bengals OL vs Chiefs in the 2022-season AFC Championship (Jan 29, 2023), the first year after the OL rebuild (confirm the game before use)",
    "Eagles OL (Kelce, Johnson; Jeff Stoutland, OL coach through 2025)"],
   "Rushers vs blockers: right after the snap count rushers and blockers; if one came free, guess who owned him.",
   fwd=["07-01 / 07-02 (rush and blitz from the defense's side)"],
   see=["12-08"])

ch("04-03", "quick-game", "The Quick Game: Slant-Flat, Stick, Snag, Quick Screens, and Beating Press", 3, 14,
   ["Explain why quick game exists: beats pressure, keeps the offense on schedule, extends the run game.",
    "Diagram slant-flat, stick, snag, spacing, speed out, double slants, hitch-seam.",
    "Use receiver leverage (inside/outside) to make a pre-snap decision.",
    "Beat press from the receiver's side: release moves, stem, stacking the defender, the break, the catch point, and the double move.",
    "Treat now/smoke and bubble screens as the quick game's cousins: throws that punish soft or overloaded alignments.",
    "Recognise quick game as the answer to press and blitz."],
   ["quick game", "slant-flat", "stick", "snag", "spacing", "speed out", "double slants", "hitch-seam",
    "leverage (inside / outside)", "pre-snap read", "rhythm throw", "release (vs press)", "stem",
    "stacking (a defender)", "contested catch", "double move", "now screen | smoke screen | quick screen", "bubble screen"],
   ["04-01", "04-02"],
   ["S: Stick vs the flat defender", "A: Slant-flat high-low read (frame strip)", "S: Snag triangle",
    "S: Speed out", "S: Release moves vs press (the receiver's side)", "S: Now/smoke screen vs off coverage",
    "S: Bubble screen", "A: Quick game vs a five-man pressure, ball out in 2.1s (frame strip)"],
   ["Walsh 49ers", "Brady Patriots", "Payton/Brees Saints", "Chiefs Kelce/quick game 2022-24"],
   "One-two-throw: stopwatch time to throw on quick game; under ~2.5s?",
   fwd=["06-01 (press and off coverage from the DB's side)", "07-02 (blitz math and families)"],
   see=["12-01", "12-04"])

ch("04-04", "dropback-concepts", "Dropback Concepts: Smash, Flood, Mesh, Levels, Dagger, and Four Verticals", 3, 18,
   ["Diagram and explain smash, flood (sail), levels, mesh, drive, shallow cross, curl-flat, dagger, Y-cross, four verticals, "
    "post-wheel, yankee, angle (Texas), and scissors.",
    "Classify each as vertical stretch, horizontal stretch, triangle, or man-beater.",
    "Define the rub (pick) route and its legality limit (enforcement in 09-03).",
    "Walk the QB's progression for each.",
    "Explain tags and route conversions (break differently vs man and zone); the choice route is the option route of 04-01.",
    "Forward-reference the coverage matchups (08-01)."],
   ["pass concept", "smash", "flood | sail", "levels", "mesh", "rub route | pick route", "drive (concept)", "shallow cross",
    "curl-flat", "dagger", "Y-cross", "four verticals", "post-wheel", "yankee", "angle route | Texas route", "scissors",
    "man-beater", "route conversion", "triangle read"],
   ["04-03"],
   ["S: Concept plates (14) in consistent style with numbered progressions",
    "A: Four verticals vs generic deep defenders (frame strip)",
    "A: Mesh vs man: the rub (frame strip)",
    "C: Pass EPA heatmap by target depth x field width"],
   ["Air Raid mesh and Y-cross (Leach)", "Patriots option/choice concepts", "McVay yankee", "Chiefs four verts variants"],
   "Name the concept: on replays, find two-receiver combinations and name the stretch.",
   fwd=["08-01 (concept vs coverage)", "06-03 (four verts vs Cover 3)", "09-03 (pick-play legality)"],
   notes=["Signature-diagram home for Air Raid mesh and Y-cross (audit S21); 04-08 and 11-03 link here instead of redrawing."],
   see=["12-01"])

ch("04-05", "play-action-boots-screens", "Play-Action, Bootlegs, and Screens", 3, 13,
   ["Explain why play-action works (run-fit triggers: glossed here, built in 05-05) and the data finding that it does not require a successful run game.",
    "Distinguish under-center vs shotgun play-action, boot, naked, keeper, leak, shot plays.",
    "Diagram RB slow screen, tunnel, jailbreak, TE screen, middle screen; contrast a screen with an RB swing or flare.",
    "Explain screen timing, OL release, and why screens punish pressure.",
    "Compare team play-action rates and efficiency with data."],
   ["play-action", "bootleg", "naked bootleg", "keeper", "leak", "shot play", "screen", "slow screen | RB screen",
    "tunnel screen", "jailbreak screen", "swing route", "flare"],
   ["04-04", "03-02"],
   ["A: Wide-zone play-action boot: LBs step up, crosser opens (frame strip)", "S: Naked boot",
    "S: RB slow screen", "S: Tunnel screen", "S: RB swing/flare vs RB screen",
    "C: EPA/dropback with vs without play-action by team (FTN is_play_action / nflverse)"],
   ["2018 Rams (Goff play-action)", "Kubiak/Shanahan boots", "Chiefs screen game",
    "Ben Baldwin's play-action research"],
   "Watch the linebackers' feet: on play-action, did they step forward? How many yards did the crosser gain?",
   fwd=["05-05 (run-fit triggers)"],
   notes=["WR quick screens (now/smoke, bubble) moved to 04-03 to de-crowd this chapter (audit S19)."],
   see=["12-03"])

ch("04-06", "rpos", "Run-Pass Options: Plays That Are Two Plays", 3, 13,
   ["Define the RPO and distinguish it from play-action and from the option.",
    "Diagram pre-snap (box-count) and post-snap (read-a-defender) RPOs: bubble, glance, stick, slant, pop pass.",
    "Explain the NFL ineligible-downfield rule (1 yard) and how it limits RPOs vs college (still 3 yards).",
    "Identify the apex/overhang defender (02-05) as the usual read.",
    "Preview defensive answers."],
   ["RPO | run-pass option", "pre-snap RPO", "post-snap RPO", "glance RPO",
    "bubble RPO", "illegal man downfield | ineligible downfield", "pop pass", "packaged play"],
   ["04-05", "03-04"],
   ["A: Inside zone + glance RPO reading the LB, both branches (frame strips)",
    "S: Bubble RPO by box count", "S: Slant RPO",
    "S: Ineligible-downfield limit: NFL 1 yard vs college 3 yards"],
   ["2017 Eagles (Foles, Super Bowl LII)", "Chiefs RPOs", "Oregon / Auburn / Baylor college roots", "Jalen Hurts' Eagles"],
   "Is he reading you? At the mesh point, find the defender the QB is looking at.",
   fwd=["05-05 (fits vs RPO)", "08-02 (RPOs as constraints)", "11-03 (college lineage)"],
   see=["12-04", "12-06"])

ch("04-07", "quarterback-play", "Quarterback Play: Progressions, the Pocket, and Off-Script Football", 4, 14,
   ["Map the QB's process after the snap: protection check, progression, timing, and when to leave the pocket "
    "(how he reads coverage comes in 08-01, once coverages are taught).",
    "Describe pocket movement: climb, slide, escape, throwaway (and why a throwaway must avoid intentional grounding).",
    "Explain scramble-drill rules and off-script play.",
    "Explain anticipation throws and the checkdown as risk management.",
    "Profile QB styles using time to throw, aDOT, CPOE, and EPA.",
    "Explain why QBs dominate value (forward ref 14-01)."],
   ["climbing the pocket", "throwaway", "scramble drill", "off-script play | off-schedule play",
    "anticipation throw", "checkdown", "CPOE | completion percentage over expected"],
   ["04-04", "04-02"],
   ["A: Progression read with numbered reads lighting up (frame strip)",
    "S: Pocket movement: climb, slide, and escape lanes",
    "S: Scramble-drill rules plate",
    "C: QB style map: time to throw vs aDOT, coloured by EPA/dropback"],
   ["Tom Brady", "Peyton Manning", "Patrick Mahomes (off-script)", "Josh Allen", "Joe Burrow", "Brock Purdy (system QB debate)"],
   "Watch the eyes: on replays count how many reads the QB got through before throwing.",
   fwd=["08-01 (how the QB reads coverage; look-offs)", "06-06 (reading disguise)",
        "09-04 (intentional grounding and the tackle box)", "14-01 (QB value)"],
   see=["12-04"])

ch("04-08", "offensive-systems-and-languages", "Offensive Systems and Play-Calling Languages", 4, 12,
   ["Distinguish how the major families name plays: West Coast, Air Coryell, Erhardt-Perkins, run-and-shoot, Air Raid, Shanahan/McVay, spread-option.",
    "Explain why naming matters for installation, tempo, and in-game adjustment.",
    "Explain how a system is installed: base plays, tags, weekly game-plan packages.",
    "Recognise a system's fingerprints on film.",
    "Checklist so far (Parts 1-4): add run/pass and concept-family clues to the Part 2 card."],
   ["offensive system", "West Coast offense | WCO", "Air Coryell", "digit system (route numbering)", "Erhardt-Perkins",
    "run-and-shoot", "Air Raid", "concept-based terminology"],
   ["04-07"],
   ["S: One concept named three ways (WCO / Coryell / EP)",
    "S: Run-and-shoot base with choice routes",
    "S: Install map: base plays -> tags -> weekly packages",
    "S: Checklist-so-far card (Parts 1-4)"],
   ["Walsh/Holmgren WCO verbiage", "Coryell digit calls", "Erhardt/Perkins concept names (Parcells -> Belichick/McDaniels Patriots)",
    "Mouse Davis & June Jones run-and-shoot", "Mumme & Leach Air Raid (mesh and Y-cross are drawn in 04-04)",
    "Shanahan/McVay long verbal calls"],
   "Fingerprint the system: chart under-center %, motion, condensed sets, empty for one team; guess its family.",
   fwd=["11-02 / 11-03 (where these systems came from)", "12-01 (WCO deep dive)", "Appendix E (coaching trees)"],
   notes=["Naming and installing only (audit S22): origin stories live in 11-02/11-03, the WCO deep dive in 12-01, "
          "and coaching-tree maps in 12-01, 12-03, and Appendix E.",
          "Part-end card (audit S8): close with the 'checklist so far' card."],
   see=["12-01", "12-03"])

# ---------------------------------------------------------------- PART 5
part("05", "Defensive Fronts and Run Defense", "3-4",
     "The defense's side of Part 3: how linemen align and play, the even and odd front families, linebackers, tackling, and the "
     "integrated system of run fits that makes every gap someone's job.")

ch("05-01", "dl-techniques-and-gap-control", "Defensive Line Play: Techniques, One-Gap and Two-Gap", 3, 12,
   ["Map DL roles to the technique numbers from 03-01: nose (0/1), 3-technique, 4i, 5-technique, wide-9, edge, and the body type each wants.",
    "Distinguish one-gap (penetrate) and two-gap (control and read) play.",
    "Explain reactions to down blocks, reaches, and double teams.",
    "Define setting the edge and contain.",
    "Describe line movement: slants and angles."],
   ["one-gap", "two-gap", "wide-9", "set the edge", "contain",
    "penetration", "slant (line movement)", "angle (line movement)"],
   ["03-01", "02-05"],
   ["S: Technique map with archetype silhouettes",
    "A: Two-gap nose controls the center then sheds either way (frame strip)",
    "A: One-gap 3-tech penetrates (frame strip)", "S: Slant and angle movements"],
   ["Vince Wilfork (two-gap nose)", "Warren Sapp / Aaron Donald (3-tech)", "Reggie White", "Wide-9 under Jim Washburn / Jim Schwartz"],
   "Find the 3-technique: before the snap find the DT outside the guard; which way did the run go?",
   see=["12-08"])

ch("05-02", "even-fronts", "Even Fronts: 4-3 Over, Under, Wide-9, and the 46 Bear", 3, 13,
   ["Diagram 4-3 Over and Under and their strength rules.",
    "Explain the wide-9 trade-off (pass rush for run lanes).",
    "Diagram the 46 / bear front and why covering the center and both guards wrecks blocking schemes.",
    "Show how even fronts adjust from 21 to 11 personnel.",
    "Identify the front from the broadcast angle."],
   ["even front", "4-3 Over", "4-3 Under", "46 defense", "bear front"],
   ["05-01"],
   ["S: 4-3 Over and Under plates",
    "A: Bear front vs I-form: nobody left to block the backers (frame strip)",
    "S: Wide-9 rush lanes", "S: Under front vs 11 personnel"],
   ["Buddy Ryan's 1985 Bears", "Pete Carroll's Seattle Under", "Jim Schwartz's 2017 Eagles", "Lovie Smith's Bears"],
   "Over or under? Find the 3-tech relative to the TE before each snap.",
   see=["12-08"])

ch("05-03", "odd-and-hybrid-fronts", "Odd and Hybrid Fronts: 3-4, Okie, Tite, and Modern Nickel Fronts", 3, 14,
   ["Diagram the 3-4 Okie and contrast two-gap vs one-gap 3-4s.",
    "Explain the tite (mint) front and why it walls off inside runs vs spread offenses.",
    "Diagram nickel fronts: 4-2-5, 3-3-5, 2-4-5.",
    "Explain why front labels blur (stand-up edges, 'multiple' defenses), with the Eagle and G fronts as dialect notes.",
    "Show how a front chooses to defend inside vs outside zone."],
   ["odd front", "3-4 Okie", "tite front | mint front", "4-2-5", "3-3-5", "2-4-5", "stand-up edge | outside linebacker (3-4)",
    "multiple defense | hybrid defense", "reduced front", "Eagle front", "G front"],
   ["05-02"],
   ["S: Okie plate", "A: Tite front vs inside zone (frame strip)", "S: 4-2-5 vs 2x2", "S: 2-4-5",
    "A: Same personnel, two fronts: stand-up edge puts hand down (frame strip)",
    "S: Dialect note: Eagle and G fronts against the Okie"],
   ["3-4 origins, presented as disputed: Bill Arnsparger's '53' (1972 Dolphins), Chuck Fairbanks (1974 Patriots), "
    "Bum Phillips (1974 Oilers); Fritz Shurmur's 'Eagle' work is 1980s Rams (verify each)",
    "Wade Phillips one-gap 3-4 (J.J. Watt Texans, 2015 Broncos)",
    "Fangio tite (2018 Bears, 2024 Eagles)", "Kirby Smart's Georgia"],
   "Count the hands down: three, four, or five? Who is standing on the edge?",
   fwd=["11-01 / 11-02 (3-4 history)"],
   see=["12-08"])

ch("05-04", "linebackers-and-second-level", "Linebackers: Keys, Flow, Tackling, and the Hardest Job on the Field", 3, 13,
   ["Explain alignments (stack, apex, walk-out) and keys (guards, near back).",
    "Explain flow (fast, slow) and fit actions: fill, scrape, plug, run-through.",
    "Explain pursuit angles, leverage tackling, and why missed tackles cluster at the second level.",
    "Describe LB coverage jobs (hook/curl, man on backs, rat/hole) and pressure roles.",
    "Explain the decline of the Sam and the rise of safety-sized linebackers.",
    "Describe the green-dot communicator's job."],
   ["stack alignment", "walk-out", "key (read key, defense)", "flow (fast / slow)", "fill",
    "scrape", "plug", "run-through", "pursuit angle", "leverage tackling", "hook / curl defender"],
   ["05-02", "04-05"],
   ["A: LB key read: guard pulls, Mike flows (frame strip)", "S: Apex alignment vs 2x2",
    "S: Pursuit angles: the leverage player and the inside-out tackle", "S: Scrape vs zone read",
    "A: LB conflict on play-action, revisited from 04-05 (frame strip)"],
   ["Ray Lewis", "Luke Kuechly", "Bobby Wagner", "Fred Warner", "Roquan Smith"],
   "Mirror the Mike: watch only the Mike for 10 snaps. First step forward or back?",
   see=["12-05"])

ch("05-05", "run-fits-and-box-math", "Run Fits: Gap Integrity, Force, Spill, and Box Math", 4, 15,
   ["Explain run fits and gap integrity: every gap owned.",
    "Distinguish force/contain, spill vs box (squeeze), and the alley player.",
    "Explain the plus-one principle and how safety rotation adds a fitter.",
    "Show fits vs zone, power, and zone read (gap exchange).",
    "Explain two-high light-box run defense and its costs.",
    "Evaluate box count vs EPA with data."],
   ["run fit", "gap integrity", "force (defender)", "spill", "box technique | squeeze", "alley player",
    "plus-one", "gap exchange"],
   ["05-04", "03-04"],
   ["S: Full 11-man fit chart vs power", "A: Spill vs box comparison on the same kick-out (frame strips)",
    "S: Plus-one with a rotated safety", "A: Scrape exchange vs zone read (frame strip)",
    "C: EPA/rush by defenders in the box"],
   ["Fangio light-box philosophy", "Ravens 2019 vs light boxes", "2024 Eagles run game vs two-high"],
   "Who's the force? Find the outermost defender each side pre-snap; did the run bounce?",
   see=["12-05", "12-08"])

# ---------------------------------------------------------------- PART 6
part("06", "Pass Coverage", "3-5",
     "From zone vocabulary to the modern disguise game. Each coverage chapter has the same spine: structure, strengths, "
     "holes, pre-snap tells, post-snap tells, and which teams made it famous.")

ch("06-01", "coverage-fundamentals", "Coverage Fundamentals: Zones, Leverage, and Reading the Shell", 3, 14,
   ["Name the zones: flat, curl, hook, hole, deep third, deep half, deep quarter.",
    "Define press, off, bail, cushion, trail, and eye discipline.",
    "Distinguish spot-drop zone, pattern-match, and man.",
    "Read the shell: MOFC vs MOFO, safety depth and width tells.",
    "Decode the Cover 0-9 numbering and its dialects: Cover 7 (match or split-field in some dialects), Cover 8 (rare), "
    "Cover 9 (often Cover 3 match or a split-field call, depending on the team); see Appendix D's dialect table.",
    "Connect coverage rules to the 5-yard contact rule (forward ref 09-03)."],
   ["flat zone", "curl zone", "hook zone", "hole zone | rat zone", "deep third", "deep half", "deep quarter", "press",
    "off coverage", "bail", "cushion", "trail technique", "landmark", "spot-drop zone", "pattern matching",
    "MOFC | middle of field closed", "MOFO | middle of field open", "coverage numbering (Cover 0-9)", "Cover 8", "Cover 9"],
   ["04-04", "02-05"],
   ["S: Zone map grid", "S: Press vs off vs bail alignment", "S: MOFC vs MOFO plates",
    "A: Spot-drop vs pattern-match vs the same routes, side by side (frame strips)",
    "S: Coverage-number dialect strip (Cover 0-9; links to Appendix D)"],
   ["Seattle press Cover 3", "Tampa 2 Bucs", "Fangio quarters"],
   "One or two? At the snap call MOFC or MOFO; one second later say whether it stayed.",
   fwd=["06-06 (Cover 7 and split-field coverage)", "09-03 (contact rules)"],
   notes=["Coverage data: participation labels exist 2018-2025 only (none for 2016-17); COVER_9 appears only from 2023 (FTN side of the "
          "source break). Say so when citing Cover 9 frequency (FACTS-current §7)."],
   see=["12-08"])

ch("06-02", "man-coverage", "Man Coverage: Cover 0, Cover 1, Robbers, and Brackets", 3, 13,
   ["Diagram Cover 1 (man-free), Cover 1 robber/rat, and Cover 0.",
    "Explain man techniques (press-man, off-man, trail) and inside help.",
    "Explain banjo/combo vs stacks and bunches; brackets on stars; shadow corners.",
    "Explain when defenses prefer man (third down, red zone, talent).",
    "Revisit man-beaters (mesh and rubs from 04-04; slants and double moves from 04-03)."],
   ["Cover 1 | man-free", "Cover 0", "robber | rat", "lurk", "banjo", "combo coverage", "bracket", "shadow corner",
    "inside help"],
   ["06-01"],
   ["S: Cover 1 vs 2x2", "S: Cover 0 vs empty", "A: Banjo vs stack release (frame strip)",
    "S: Bracket on #1 in 3x1", "A: Cover 1 rat robbing a dig (frame strip)"],
   ["Patriots Cover 1 & brackets (Ty Law, Stephon Gilmore)", "Spagnuolo's Cover 0", "Darrelle Revis", "Seattle's Richard Sherman (contrast: zone corner)"],
   "Who's facing the QB? Man defenders turn to the receiver; zone defenders read the QB.",
   notes=["nflverse man/zone shares jump across 2022 -> 2025 (28.8%, 41.2%, 48.3%, 30.8%), a coding artefact of the source break. "
          "Do not chart a man-coverage trend across those seasons without a caveat (FACTS-current §7)."],
   see=["12-02", "12-04"])

ch("06-03", "cover-3-family", "Cover 3: Sky, Buzz, Cloud, and Seattle's Match Version", 3, 13,
   ["Diagram Cover 3 base (three deep, four under) and the sky, buzz, cloud rotations.",
    "Explain Cover 3's strengths (eight-man front) and holes (seams, curl-flat, flood).",
    "Explain Cover 3 match and how it handles four verticals.",
    "Recognise Cover 3 pre-snap and post-snap."],
   ["Cover 3", "sky rotation", "buzz rotation", "cloud rotation | corner rotation", "seam-flat defender",
    "curl-flat defender", "Cover 3 match"],
   ["06-01"],
   ["S: Cover 3 sky vs 2x2", "S: Buzz", "S: Cloud",
    "A: Four verticals vs spot-drop Cover 3: the seam opens (frame strip)",
    "A: Four verticals vs Cover 3 match: seam carried (frame strip)"],
   ["Pete Carroll's 2012-2015 Seahawks (Sherman, Thomas, Chancellor)", "Gus Bradley", "Dan Quinn"],
   "Count deep defenders one second after the snap: three means a Cover 3 family call.")

ch("06-04", "cover-2-and-tampa-2", "Cover 2 and Tampa 2", 3, 12,
   ["Diagram Cover 2 zone (two halves, five under) and hard/squat corners.",
    "Explain Tampa 2 (Mike runs the deep middle) and why it existed.",
    "Diagram 2-Man (two-deep, man under).",
    "Locate Cover 2's holes: hole shot, smash corner, deep middle, sideline hole.",
    "Explain why classic Tampa 2 faded and what survived."],
   ["Cover 2", "hard corner | squat corner", "hole shot", "Tampa 2", "2-Man | Cover 5"],
   ["06-03"],
   ["S: Cover 2 vs 2x2", "A: Tampa 2: Mike carries the seam (frame strip)", "S: 2-Man",
    "A: Smash vs Cover 2 (frame strip)"],
   ["Tony Dungy / Monte Kiffin 2002 Bucs", "Dungy's 2006 Colts", "Lovie Smith's 2006 Bears", "Bud Carson's 1970s Steelers Cover 2"],
   "Squat-corner spotter: corners at 5-7 yards, outside leverage, not bailing -> think Cover 2.",
   notes=["Signature-diagram home for 'smash vs Cover 2'; 08-01 recaps it as a static plate."])

ch("06-05", "quarters-and-match", "Quarters and the Two-High Match Family: Cover 4, Cover 6, Palms", 4, 16,
   ["Diagram Cover 4 (quarters) and its run support (safeties fit off #2).",
    "Explain match rules: MOD, MEG, read-the-#2 safety.",
    "Diagram Cover 6 (quarter-quarter-half) and Palms / 2-read (trap).",
    "Explain why two-high match coverage spread through the NFL 2018-2025 (NGS split-safety rate 32.9% in 2018 -> 42.0% in 2025).",
    "Identify the weaknesses: light-box runs, flood from boot, RB wheel."],
   ["quarters | Cover 4", "Cover 6", "Palms | 2-read | trap coverage", "MOD | man only deep", "MEG | man everywhere he goes",
    "read safety"],
   ["06-04", "05-05"],
   ["S: Cover 4 vs 2x2 with match responsibilities", "A: Quarters safety fits the run (frame strip)",
    "S: Cover 6 vs 3x1", "A: Palms: corner traps the out (frame strip)",
    "C: League two-high rate by season, 2018-2025 (participation labels; mark the 2022 NGS -> 2023 FTN source break)"],
   ["Saban/Belichick rip-liz match", "Brandon Staley's 2020 Rams", "Ejiro Evero (2022 Broncos, then Panthers)",
    "Michigan State / Iowa college quarters"],
   "Two-high, now what? Watch both safeties' first steps: backpedal, downhill, or rotate?",
   fwd=["12-08 (Fangio case study)"],
   notes=["Film-room examples avoid Fangio and Macdonald so 12-08 stays fresh (audit S23).",
          "Trend numbers (FACTS-current §10): NGS split-safety 32.9% (2018), 37.8% (2021), 40.4% (2024), 42.0% (2025); Cover 4 17.2% in 2025. "
          "Do not mix with the TruMedia/538 early-down series. Coverage labels start in 2018 (none 2016-17)."],
   see=["12-08"])

ch("06-06", "disguise-rotation-and-split-field", "Disguise, Rotation, and Split-Field Coverage", 5, 16,
   ["Explain disguise and post-snap rotation (two-high to one-high, one-high to two-high).",
    "List tells: safety depth/width, corner leverage, weight, timing of movement.",
    "Explain split-field coverage and 3x1 checks (poach, solo, stubbie).",
    "Explain how late rotation forces post-snap reading and how offenses respond (motion, tempo, hard counts).",
    "Measure safety movement around the snap with tracking data (result shown here; built in 13-05).",
    "Checklist so far (Parts 1-6): add shell -> rotation -> leverage to the card."],
   ["disguise", "post-snap rotation", "split-field coverage", "Cover 7 (match family)", "poach", "3x1 check (solo / stubbie)",
    "late rotation"],
   ["06-05", "02-06"],
   ["A: Two-high shell rotates to Cover 3 robber at the snap (frame strip)",
    "A: One-high spins to Cover 2 (frame strip)",
    "S: Split-field Cover 6 vs 2x2", "S: Poach vs 3x1",
    "T: Safety depth and lateral position from snap-30 to snap+20 frames (BDB tracking; the result of the 13-05 build)",
    "T: Pre-snap shell (BDB 2025 pre-snap tracking, 2022 Weeks 1-9) vs labelled post-snap coverage: agreement rate by team",
    "S: Checklist-so-far card (Parts 1-6)"],
   ["Brian Flores' Vikings (2023-2025)", "Brandon Staley's 2020 Rams", "Ejiro Evero's split-field looks", "Iowa split-field quarters"],
   "Call it twice: name the coverage pre-snap and again one second after; log how often the defense lied.",
   fwd=["13-05 (tracking data; builds the safety-rotation figure)", "12-08 (Fangio and Macdonald case study)"],
   notes=["Pilot chapter. Its 'You'll need' recap box is part of the pilot test: it must summarise roughly 15 prerequisite chapters.",
          "Signature-figure home for safety rotation is 13-05 (built there); this chapter shows the result; 12-08 links (audit S21).",
          "Film-room examples avoid Fangio and Macdonald so 12-08 stays fresh (audit S23).",
          "Pre-snap shell is not in nflverse; the agreement figure must come from BDB 2025 tracking (FACTS-current §8).",
          "Part-end card (audit S8)."],
   see=["12-08"])
