"""Render planning/CURRICULUM.md from data1.py/data2.py (+ tail.md) and validate the plan.

Usage: python gen.py <output.md>

Validation (exit 1 on any error):
- chapter IDs unique; every prerequisite exists and comes earlier;
- every term name AND alias has exactly one home (case-insensitive);
- 3-8 objectives per chapter; at most 4 animations per chapter (AUTHORING §4);
- every chapter ID mentioned in objectives, notes, forward refs, see-also, diagrams, and drills exists.
"""
import sys, re, collections
from data1 import PARTS, CH
import data2  # noqa: registers parts 7-15

OUT = sys.argv[1]
WORDS_PER_UNIT = 375  # 'pages' in the data are a planning size unit; rendered as words (AUTHORING §2 governs length)

ids = [c["id"] for c in CH]
assert len(ids) == len(set(ids)), "dup ids"
order = {cid: i for i, cid in enumerate(ids)}
byid = {c["id"]: c for c in CH}


def split_term(t):
    """'quarters | Cover 4' -> ('quarters', ['Cover 4'])."""
    parts = [p.strip() for p in t.split("|")]
    return parts[0], [p for p in parts[1:] if p]


def words(units):
    return int(round(units * WORDS_PER_UNIT / 500.0)) * 500


def fmt_words(n):
    return f"{n:,}"


# ---- validation
errs = []
term_home = {}   # lower name -> (cid, name, aliases)
alias_home = {}  # lower alias -> (cid, alias, name)
seen = {}        # lower name-or-alias -> description, for collision checks
IDREF = re.compile(r"(?<![\d-])((?:0[1-9]|1[0-5])-\d{2})(?![\d-])")
for c in CH:
    for p in c["prereq"]:
        if p not in order:
            errs.append(f"{c['id']}: unknown prereq {p}")
        elif order[p] >= order[c["id"]]:
            errs.append(f"{c['id']}: prereq {p} not earlier")
    for t in c["terms"]:
        name, aliases = split_term(t)
        for label, kind in [(name, "term")] + [(a, "alias") for a in aliases]:
            k = label.lower()
            if k in seen:
                errs.append(f"dup {kind} '{label}' in {c['id']} (already {seen[k]})")
            seen[k] = f"{kind} in {c['id']}"
        term_home[name.lower()] = (c["id"], name, aliases)
        for a in aliases:
            alias_home[a.lower()] = (c["id"], a, name)
    if not (3 <= len(c["obj"]) <= 8):
        errs.append(f"{c['id']}: {len(c['obj'])} objectives")
    n_anim = sum(1 for d in c["diagrams"] if d.startswith("A:"))
    if n_anim > 4:
        errs.append(f"{c['id']}: {n_anim} animations (AUTHORING §4 caps at ~4)")
    for s in c["see"]:
        if s not in order:
            errs.append(f"{c['id']}: unknown see-also {s}")
    texts = c["obj"] + c["notes"] + c["fwd"] + c["diagrams"] + [c["drill"]]
    for txt in texts:
        for ref in IDREF.findall(txt):
            if ref not in order:
                errs.append(f"{c['id']}: text mentions unknown chapter {ref}: {txt[:70]}")
if errs:
    print("\n".join(errs)); sys.exit(1)

TAG = {"S": "Static", "A": "Animation + PDF frame strip", "C": "Data chart (nflverse)", "T": "Tracking-data plot/animation"}
dcount = collections.Counter(d.split(":")[0] for c in CH for d in c["diagrams"])
total_words = sum(words(c["pages"]) for c in CH)


def term_display(t):
    name, aliases = split_term(t)
    return f"{name} (also: {', '.join(aliases)})" if aliases else name


L = []
w = L.append

w("# Reading the Game: Curriculum")
w("")
w("_Planning document for the Quarto book **Reading the Game**. Curriculum only; no chapter prose. Prepared October 2026; "
  "content current through the 2025 NFL season, with changes made for 2026 (rules, staffs) flagged and labelled. "
  "Generated by `planning/curriculum-src/gen.py`: edit the data files there, not this file._")
w("")
w("**This file vs `planning/AUTHORING.md`:** AUTHORING.md is the authoring contract and wins any conflict. This file says "
  "*what* each chapter teaches (objectives, terms, prerequisites, diagrams, examples); AUTHORING.md says *how* every chapter "
  "is written. Current facts (Super Bowl results, 2026 rules, 2026 staffs, data caveats, trend numbers) are in "
  "`planning/FACTS-current.md`.")
w("")
w(f"**Size:** {len(PARTS)} parts, {len(CH)} chapters, 7 reference appendices (A-G). "
  f"Planned length roughly {fmt_words(total_words)} words of chapters (a planning estimate, not a limit), plus the atlas and glossary.")
w("")
w(f"**Diagram inventory (chapters only):** {dcount['S']} static, {dcount['A']} animations (each also rendered as a PDF frame strip), "
  f"{dcount['C']} nflverse data charts, {dcount['T']} tracking-data figures.")
w("")
w("## Contents")
w("")
w("1. Design principles")
w("2. The chapter template")
w("3. Part and chapter overview")
w("4. Chapter specifications")
w("5. Reference appendices (the atlas)")
w("6. Master term index (glossary ownership plan)")
w("7. Pilot chapters")
w("8. Diagram library requirements")
w("9. Fact-check flags and open questions")
w("")

# ---- 1 design principles
w("## 1. Design principles")
w("")
for p in [
    "**Every concept answers 'why does this exist?'** Each formation, coverage, and scheme is taught as a solution to a problem, "
    "and the problem it creates for the other side is named. The arms race is the course's narrative spine, not just Part 11.",
    "**Never use a concept before it is taught** (AUTHORING §3). Every chapter lists its prerequisites; the build order below satisfies them "
    "(validated by the generator). Where a chapter must use a term it does not own yet, it gives a one-line gloss and a forward link; "
    "those cases are listed as 'Forward references' in Section 4. Diagrams that need a not-yet-taught name are labelled generically.",
    "**Spiral, then deepen.** A deliberately shallow first look at defense (02-05) lets the offense parts mention defenders. "
    "Technique numbers are owned by 03-01 and deepened in 05-01; disguise is hinted at in 02-06 and fully taught in 06-06; "
    "EPA is introduced as a scorecard in 01-02 and modelled in 13-02.",
    "**One home per term, per diagram, per story.** Each term has one owning chapter (Section 6). Each signature diagram is built once "
    "and linked elsewhere. Offensive systems are named and installed in 04-08, their origins told in Part 11, their best teams in Part 12.",
    "**Pictures first, words second.** Every chapter has diagrams in one consistent visual language (Section 8 and AUTHORING §4). Movement is shown "
    "as animation in HTML and as a numbered frame strip in PDF, so nothing depends on the format. At most ~4 animations per chapter.",
    "**Real teams, real plays, real data.** Every scheme is anchored to teams that did it well, labelled with seasons. Charts use nflverse "
    "data; Parts 1-12 fold the code and Part 13 shows it and teaches the reader to build them.",
    "**Check current facts first.** Before writing, read `planning/FACTS-current.md`: Super Bowl LX, 2026 kickoff and replay rules, "
    "2026 coaching staffs (label every staff and play-caller with its season), and the data caveats: coverage type exists only for "
    "2018-2025, participation switches from NGS (2016-2022) to FTN (2023+) with different labels, FTN `is_motion` means motion before "
    "*or at* the snap, and there is no tush-push flag (use `is_qb_sneak`). Every trend number carries its source; never mix series.",
    "**Watching is the goal.** Every chapter has a 'Watch for it on Sunday' drill (AUTHORING §2). 01-02 takes a baseline guess; the formal "
    "prediction log starts in 01-06 and is scored in 15-02. A 'checklist so far' card closes Parts 2, 4, 6, and 7 and grows into the "
    "master checklist of 15-01.",
    "**Two ways in: learn and look up.** The narrative path (Parts 1-15) teaches; the atlas appendices (A-E, G) and glossary (F) give "
    "one-page reference cards with consistent fields, each linking back to the teaching chapter. Every alias (Cover 4, wide zone, BOB, creeper) "
    "is its own lookup entry.",
    "**Honest about uncertainty.** Coverage names differ by team; charting data has errors; 'beaters' are probabilistic; disputed origins are "
    "presented as disputed. The book says so instead of presenting one dialect as truth.",
    "**Levels are stated.** Level 1 = casual-fan basics; 3 = what a well-informed analyst knows; 5 = coach/film-room level. "
    "Every Level 3+ chapter opens with a short 'You'll need' recap box (AUTHORING §2).",
]:
    w(f"- {p}")
w("")

# ---- 2 template
w("## 2. The chapter template")
w("")
w("The template is defined in `planning/AUTHORING.md` §2-§3, which wins any conflict. Summary, in order:")
w("")
for i, s in enumerate([
    "**Front matter:** `title`, `subtitle`, `description`, and a `glossary:` map with every term this chapter owns per Section 6 "
    "(aliases as `aliases:`; AUTHORING §3). The glossary page is generated from chapter front matter.",
    "**Opening hook (the question):** a concrete broadcast moment the chapter explains. One short paragraph.",
    "**You'll be able to...:** 3-6 observable skills (drawn from the objectives in Section 4). Level 3+ chapters follow it with a "
    "**You'll need** box: one line of recap and a link per prerequisite.",
    "**Body in small steps:** one idea per `##` section, shown with a diagram, then why it exists and what it gives up.",
    "**History where it explains the present:** who, when, and what problem they faced; verified (AUTHORING §6).",
    "**Film room:** at least one real team/play example (team, season, ideally game and situation); candidates are the "
    "'Team / era examples' in Section 4.",
    "**Watch for it on Sunday:** the chapter's drill from Section 4, plus what to record in the prediction log.",
    "**Predict the play:** 1-3 drills: a pre-snap picture, the question, the answer in a collapsed callout.",
    "**Takeaways:** 3-6 bullets, written last.",
    "**Connections:** builds on / sets up (links), case-study 'see also' links from Section 4, and 'If you want to go deeper'.",
], 1):
    w(f"{i}. {s}")
w("")
w("Length: whatever the concept needs; most chapters land at 3,000-7,000 words. The word targets in Sections 3-4 are planning "
  "estimates, not limits. Callout titles follow AUTHORING §3 ('Madden vs. real life', 'Watch for it', 'Why it exists', "
  "'Film room: <team> <season>', 'Common misconception', 'Predict the play', 'Go deeper', 'You'll need').")
w("")
w("Case-study chapters (Part 12) keep this shape and organise the body as: the problem -> the scheme answer -> signature plays -> "
  "data fingerprint -> how opponents responded -> what survives.")
w("")

# ---- 3 overview
w("## 3. Part and chapter overview")
w("")
w("| Part | Title | Levels | Chapters | Est. words |")
w("|---|---|---|---|---|")
for p in PARTS:
    cs = [c for c in CH if c["id"].startswith(p["id"] + "-")]
    w(f"| {p['id']} | {p['title']} | {p['levels']} | {len(cs)} | {fmt_words(sum(words(c['pages']) for c in cs))} |")
w(f"| | **Total** | | **{len(CH)}** | **{fmt_words(total_words)}** |")
w("")
w("Full chapter list:")
w("")
w("| ID | Slug (filename) | Title | Level | Est. words | Prerequisites |")
w("|---|---|---|---|---|---|")
for c in CH:
    w(f"| {c['id']} | `{c['id']}-{c['slug']}.qmd` | {c['title']} | {c['level']} | {fmt_words(words(c['pages']))} | {', '.join(c['prereq']) or 'none'} |")
w("")
w("**Reading-order note:** the order above satisfies every prerequisite. Sanctioned shortcuts: 13-01 (nflverse in Python) can be "
  "read any time after Part 2; 09-01 (kicking and punting) any time after Part 1 and 09-02 (kickoffs) any time after 03-01, which helps "
  "linear readers who would otherwise drop from Level 4-5 material in Part 8 back to Level 2 in Part 9; Part 11 (history) can be read any "
  "time after Part 7 by readers who prefer the story first, skipping the few references to situational and special-teams material.")
w("")

# ---- 4 chapters
w("## 4. Chapter specifications")
w("")
w("Diagram tags: **[S]** static; **[A]** animation, also rendered as a numbered frame strip in PDF; **[C]** nflverse data chart; "
  "**[T]** tracking-data figure (Big Data Bowl / NGS). Key terms list the glossary headword first and its aliases after 'also:'.")
w("")
for p in PARTS:
    w(f"### Part {p['id']}: {p['title']}")
    w("")
    w(f"_Levels {p['levels']}._ {p['blurb']}")
    w("")
    for c in [c for c in CH if c["id"].startswith(p["id"] + "-")]:
        w(f"#### {c['id']} {c['title']}")
        w("")
        w(f"- **Slug:** `{c['id']}-{c['slug']}` | **Level:** {c['level']} | **Target length:** ~{fmt_words(words(c['pages']))} words")
        w(f"- **Prerequisites:** {', '.join(c['prereq']) or 'none'}")
        if c["fwd"]:
            w(f"- **Forward references (gloss + link in text):** {'; '.join(c['fwd'])}")
        if c["see"]:
            w(f"- **See also (case studies):** {', '.join(c['see'])}")
        w("- **Learning objectives:**")
        for o in c["obj"]:
            w(f"  - {o}")
        w(f"- **Key terms introduced:** {'; '.join(term_display(t) for t in c['terms']) if c['terms'] else 'none new (uses terms from prerequisites)'}")
        w("- **Diagrams:**")
        for d in c["diagrams"]:
            tag, txt = d.split(":", 1)
            w(f"  - [{tag}] {txt.strip()}")
        w(f"- **Team / era examples:** {'; '.join(c['examples'])}")
        w(f"- **Watch for it on Sunday:** {c['drill']}")
        if c["notes"]:
            w("- **Notes for the writer:**")
            for n in c["notes"]:
                w(f"  - {n}")
        w("")

# ---- 5 appendices
w("## 5. Reference appendices (the atlas)")
w("")
w("The atlas is built from the same diagram source as the chapters (one plate definition, rendered in both places). "
  "Every scheme atlas card (A-D) has the same fields: **name and aliases | diagram | what it is (2-3 sentences) | why it exists | "
  "strong against / weak against | pre-snap tells | post-snap tells (safety first step, corner bail vs squat, who drops) | "
  "teams known for it (with seasons) | taught in (chapter link) | see also (related cards and case studies)**. "
  "Cards are one per half-page in PDF, searchable in HTML. Comparison pages sit at the front of their appendix.")
w("")
appx = [
    ("A", "offense-atlas", "Offensive Atlas: Personnel and Formations",
     "Comparison page first: **Positions and labels** (X/Y/Z/H/F, Mike/Will/Sam, nickel/star/money, and technique numbers on one diagram). "
     "Then all personnel groupings (02-01); classic and spread formations (02-03, 02-04); backfield alignments (02-02); motion family "
     "(02-06); specialty looks. ~46 cards."),
    ("B", "concept-atlas", "Concept Atlas: Runs, Passes, Screens, RPOs",
     "Run concepts (zone, gap, option, perimeter; 03-02 to 03-05); route tree (04-01); quick game and quick screens (04-03), dropback (04-04), "
     "play-action and screens (04-05), RPO concepts (04-06); red-zone, two-point, and short-yardage concepts (10-03). ~65 cards."),
    ("C", "defense-atlas", "Defensive Atlas: Packages, Techniques, and Fronts",
     "Comparison page first: **4-3 vs 3-4 vs nickel** (hands down, who two-gaps, who the edge players are, body types, and why the labels "
     "blur; links 02-05, 05-02, 05-03, 11-01, 11-02). Then packages (02-05); technique chart (03-01/05-01); even, odd, hybrid, nickel, "
     "and goal-line fronts with Eagle/G dialect notes (05-02, 05-03, 10-03); run-fit cheat sheet (05-05). ~32 cards."),
    ("D", "coverage-pressure-atlas", "Coverage and Pressure Atlas",
     "Comparison page first: **coverage family table, Cover 0-9** (deep defenders, under defenders, man/zone/match, strength, weakness, "
     "pre-snap tell, post-snap tell, chapter). Then Cover 0, 1 (robber/rat), 2, Tampa 2, 2-Man, 3 (sky/buzz/cloud/match), 4, 6, Palms, "
     "7/split-field, 8, 9, poach (Part 6); fire zones, sim pressures, overloads, mugs, blitz families (Part 7); the concept x coverage matrix "
     "(08-01); and a **coverage dialects** table mapping teams' names for the same call (Cover 5 = 2-Man; Cover 2 invert; Cover 3 "
     "'Mable' and rip-liz naming; 2-read vs Palms naming; the Cover 7/8/9 variants). ~44 cards."),
    ("E", "rules-timeline-trees", "Rules, Timeline, and Coaching Trees",
     "Penalty quick-reference table (yardage, auto first down, enforcement spot); officiating crew and replay summary (09-04); "
     "kickoff/punt/OT rule summaries **current as of the 2026 season**; a **'Rule changes since the 2025 season' box** (2026: onside "
     "declarable any time; 5 receiving players on the restraining line with a floater; kickoff-from-the-50 spotting fix; replay consult "
     "on ejections; three-strike suspension policy); a **college vs NFL rules table** owned by 11-03 (hash width; one foot vs two in "
     "bounds; ineligible downfield 3 yards vs 1; DPI spot foul vs 15-yard cap; OPI 10 yards in college from 2026; the college clock; "
     "overtime; targeting; kickoff fair catch and the 2026 college fair-catch kick; motion; two-minute timeouts; helmet communication); "
     "rule-change timeline 1906-2026 with each change's strategic effect; Super Bowl results through LX with a one-line scheme note each; "
     "coaching-tree diagrams with 2025 and 2026 staffs labelled separately."),
    ("F", "glossary", "Glossary",
     "Alphabetical; generated from chapter front matter (`glossary:` entries, AUTHORING §3), so key terms and the glossary never drift. "
     "Each entry has a one-sentence definition and a link to the owning chapter; each alias (e.g. 'Cover 4', 'wide zone', 'BOB', "
     "'creeper') gets its own anchor and a 'see ...' entry. Section 6 is the ownership plan the chapters follow."),
    ("G", "metrics-data-atlas", "Metrics and Data Atlas",
     "One card per metric: EPA, success rate, CPOE, aDOT, YAC/YACOE, RYOE, PROE/xpass, time to throw, pressure rate, PRWR/RSWR, YPRR, "
     "target share, WP/WPA, DVOA, PFF grade, passer rating/QBR/ANY/A. Fields: **definition | scale and a 'good' range | source "
     "(nflverse / NGS / FTN / proprietary) | stability | caveats | taught in**. Plus a **data-availability table** (pbp 1999+, "
     "participation 2016+, coverage labels 2018-2025 only, FTN charting 2022+, the 2022/2023 NGS-to-FTN source break, current-season "
     "participation only after the season ends). ~18 cards."),
]
w("| Appendix | Slug | Title | Contents |")
w("|---|---|---|---|")
for a in appx:
    w(f"| {a[0]} | `appendix-{a[0].lower()}-{a[1]}.qmd` | {a[2]} | {a[3]} |")
w("")
w("Front matter (unnumbered `index.qmd`): how to use the book, the level system, the diagram notation key, and how to set up the Python environment.")
w("")

# ---- 6 term index
w("## 6. Master term index (glossary ownership plan)")
w("")
w(f"{len(term_home)} terms plus {len(alias_home)} aliases. Each term and each alias has exactly one home chapter (validated by the generator). "
  "Later chapters may deepen a term; the glossary links to the owning chapter. Glossary entries themselves are written in each owning chapter's "
  "front matter (AUTHORING §3); this index is the plan for which chapter owns which term. Alias entries read 'see <headword>'.")
w("")
def sortkey(t):
    s = t.lower()
    s = re.sub(r"^[^a-z0-9]+", "", s)
    return s
entries = [(name, cid, aliases, None) for (cid, name, aliases) in term_home.values()] + \
          [(a, cid, [], head) for (cid, a, head) in alias_home.values()]
groups = collections.OrderedDict()
for name, cid, aliases, head in sorted(entries, key=lambda e: sortkey(e[0])):
    first = sortkey(name)[0].upper()
    if first.isdigit():
        first = "0-9"
    groups.setdefault(first, []).append((name, cid, aliases, head))
for g, items in groups.items():
    w(f"**{g}**")
    w("")
    for name, cid, aliases, head in items:
        if head:
            w(f"- {name}: see *{head}* -> {cid}")
        elif aliases:
            w(f"- {name} (also: {', '.join(aliases)}) -> {cid}")
        else:
            w(f"- {name} -> {cid}")
    w("")

# ---- 7-9 (static text appended)
with open("tail.md") as f:
    tail = f.read()
tail = tail.replace("{{NS}}", str(dcount['S'])).replace("{{NA}}", str(dcount['A'])) \
           .replace("{{NC}}", str(dcount['C'])).replace("{{NT}}", str(dcount['T']))
L.append(tail)

open(OUT, "w").write("\n".join(L))
print("chapters", len(CH), "terms", len(term_home), "aliases", len(alias_home), "words", total_words, dict(dcount))
lv = collections.Counter(c["level"] for c in CH); print("levels", sorted(lv.items()))
