{
  "hash": "2a6372de0b22d36d36ae4279bfc83a02",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Expected Points, EPA, and Success Rate: The Model, the Noise, and the Broadcast Metrics\"\nsubtitle: \"Where the numbers behind 'EPA per play' come from, how far to trust them, and how they compare to the stats on your screen\"\ndescription: \"Build an expected-points model from nflverse play-by-play, work a play's EPA by hand, compare run and pass honestly, separate signal from noise (sample size, year-over-year stability, opponent adjustment, turnover luck), use CPOE and RYOE for players, and place passer rating, QBR, ANY/A, DVOA, PFF grades, ESPN win rates and explosive play rate on one map.\"\nexecute:\n  echo: true\ncode-fold: false\nglossary:\n  \"RYOE\": {def: \"Rush yards over expected: a runner's actual rushing yards minus the yards a tracking-data model expected from where the blockers and defenders were when he took the handoff.\", aliases: [\"Rush yards over expected\"]}\n  \"Year-over-year stability\": \"How well a statistic in one season predicts the same statistic for the same team or player the next season, usually measured as a correlation; high stability points to skill, low stability to noise or changed circumstances.\"\n  \"Opponent adjustment\": \"Correcting a team's or player's numbers for the strength of the opponents faced, so that a good day against a strong defense counts for more than the same day against a weak one.\"\n  \"Turnover luck (fumble-recovery rate)\": \"The part of a team's turnover record that is chance rather than skill, clearest in fumble recoveries: who falls on a loose ball is close to a coin flip, so a team's recovery rate swings at random from year to year.\"\n  \"Passer rating\": \"The NFL's official passing formula since 1973: completion rate, yards per attempt, touchdown rate and interception rate, each capped and combined onto a scale from 0 to 158.3.\"\n  \"QBR\": {def: \"ESPN's proprietary quarterback rating (0 to 100, with 50 about average), built on expected points and win probability and crediting the quarterback's share of every play, including runs, sacks and penalties.\", aliases: [\"Total QBR\"]}\n  \"ANY/A\": {def: \"Adjusted net yards per attempt: passing yards plus 20 per touchdown pass, minus 45 per interception and minus yards lost on sacks, divided by pass attempts plus sacks.\", aliases: [\"Adjusted net yards per attempt\"]}\n  \"DVOA\": \"Defense-adjusted Value Over Average: a proprietary efficiency rating created by Aaron Schatz at Football Outsiders (now published by FTN) that scores every play against a league baseline for its situation and adjusts for the opponent; 0% is average.\"\n  \"PFF grade\": \"Pro Football Focus's proprietary player grade: analysts watch every snap, score each player's performance on it, and scale the season's scores to 0-100.\"\n  \"Run stop win rate\": {def: \"ESPN's tracking-based rate of how often a defender beats his block quickly on run plays; the run-defense companion to pass rush win rate.\", aliases: [\"RSWR\"]}\n  \"Explosive play rate\": \"The share of a team's plays that gain a big chunk. Coaching staffs often count runs of 12+ yards and passes of 16+; analysts often use 10+ and 20+ (definitions vary by source).\"\n---\n\nSuper Bowl LX, third quarter. Seattle faces third-and-12 at its own 19. Sam Darnold finds Cooper\nKupp over the middle for 8 yards, and the box score adds 8 to Darnold's passing total. Seattle\npunts on the next snap. Eight yards, and yet the expected-points ledger scores that completion as a\nsmall *loss*. In the fourth quarter New England's Drake Maye throws an interception that gains no\nyards at all, and the same ledger charges it with almost ten points.[^lx] If you have read the EPA\nprimer in [Downs, Distance, and Field Position](../01-foundations/01-02-downs-distance-and-field-position.qmd)\nyou know what those numbers mean. This chapter opens the hood: where expected points come from,\nhow to compute them yourself, how much one game, one season or one fumble can fool you, and how\nthe stats the broadcast quotes (passer rating, QBR, DVOA, PFF grades) relate to the expected-points\nscorecard.\n\n**You'll be able to:**\n\n- Explain how an expected-points model turns down, distance and yard line into a point value,\n  and fit a small one yourself from play-by-play data.\n- Work any play's EPA by hand, compute EPA per play and success rate for teams and players, and\n  say why EPA is a better yardstick than yards.\n- Compare running and passing honestly, naming the selection effects that make raw averages\n  misleading.\n- Judge whether a number is signal or noise using sample size, year-over-year stability,\n  opponent adjustment and turnover luck.\n- Use CPOE and RYOE to separate a player from his surroundings.\n- Place passer rating, QBR, ANY/A, DVOA, PFF grades, ESPN's win rates and explosive play rate\n  relative to EPA: what each measures, whether you can rebuild it, and when to distrust it.\n\n::: {.callout-note title=\"You'll need\"}\n- **[Downs, Distance, and Field Position](../01-foundations/01-02-downs-distance-and-field-position.qmd)**:\n  [**expected points**](../../appendices/glossary.qmd#gl-expected-points) (EP, the average number of points\n  a situation is worth to the team with the ball), [**EPA**](../../appendices/glossary.qmd#gl-epa)\n  (expected points added: EP after a play minus EP before it), and\n  [**success rate**](../../appendices/glossary.qmd#gl-success-rate) (the share of plays with positive EPA).\n  This chapter deepens those three terms; it does not redefine them.\n- **[Working with nflverse Data in Python](13-01-nflverse-in-python.qmd)**: loading\n  [play-by-play](../../appendices/glossary.qmd#gl-play-by-play) data with\n  [nflreadpy](../../appendices/glossary.qmd#gl-nflreadpy), the\n  [yardline_100](../../appendices/glossary.qmd#gl-yardline-100) column (yards from the opponent's end\n  zone), and the [garbage-time filter](../../appendices/glossary.qmd#gl-garbage-time-filter) that drops\n  plays whose result was no longer in doubt.\n:::\n\n## The data this chapter uses\n\nEvery number in this chapter comes from code you can run. Part 13 shows its code (other parts fold\nit), so read the cells as part of the text. The course's `gridiron.data` module wraps\n[nflreadpy](../../appendices/glossary.qmd#gl-nflreadpy) and caches each season under `data/cache/`, so\nthe ten seasons below download once.\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom IPython.display import Markdown\nfrom gridiron import style\nfrom gridiron.data import pbp, nfl\n\nstyle.apply()\nSEASONS = range(2016, 2026)   # ten completed seasons, 2016-2025\nCOLS = [\"season\", \"season_type\", \"week\", \"game_id\", \"play_id\", \"game_half\", \"qtr\",\n        \"posteam\", \"defteam\", \"home_team\", \"away_team\", \"home_score\", \"away_score\",\n        \"down\", \"ydstogo\", \"yardline_100\", \"goal_to_go\", \"half_seconds_remaining\",\n        \"play_type\", \"pass\", \"rush\", \"qb_scramble\", \"sack\", \"interception\",\n        \"fumble\", \"fumble_recovery_1_team\", \"td_team\", \"field_goal_result\", \"safety\",\n        \"yards_gained\", \"ep\", \"epa\", \"success\", \"wp\", \"cpoe\",\n        \"passer\", \"passer_id\", \"pass_attempt\", \"complete_pass\", \"passing_yards\",\n        \"pass_touchdown\", \"penalty_type\", \"first_down\"]\nraw = pbp(SEASONS, columns=COLS)\nreg = raw[raw.season_type == \"REG\"]          # regular season only\n\n# Scrimmage plays: every dropback (including sacks and scrambles) and every designed run.\n# Kneels, spikes, kicks and penalties that wipe out the play are left out.\nplays = reg[reg.play_type.isin([\"pass\", \"run\"])\n            & ((reg[\"pass\"] == 1) | (reg[\"rush\"] == 1))\n            & reg.epa.notna() & reg.down.notna()].copy()\nplays[\"kind\"] = np.where(plays[\"pass\"] == 1, \"Dropback\", \"Designed run\")\n\n# Garbage-time filter (13-01): win probability 10-90% and outside the last two minutes\n# of each half. The plays that survive are what this chapter calls \"neutral\".\nneutral = plays[plays.wp.between(0.10, 0.90) & (plays.half_seconds_remaining > 120)]\n\n\ndef md_table(df, digits=2):\n    \"\"\"Show a small DataFrame as a Markdown table (presentation plumbing, not football).\"\"\"\n    out = df.copy()\n    for c in out.select_dtypes(\"number\"):\n        whole = (out[c].dropna() % 1 == 0).all()                # downs, yard lines, counts\n        sep = \"\" if c in (\"season\", \"week\") else \",\"             # 2025, not 2,025\n        out[c] = out[c].map(lambda v: f\"{v:{sep}.{0 if whole else digits}f}\")\n    align = [\"---:\" if pd.api.types.is_numeric_dtype(df[c]) else \":---\" for c in df]\n    rows = [list(out.columns), align] + out.astype(str).values.tolist()\n    return Markdown(\"\\n\".join(\"| \" + \" | \".join(map(str, r)) + \" |\" for r in rows))\n```\n:::\n\n\nFour choices in that cell matter for everything that follows. **Regular season only**, because\nplayoff games are few and played by the best teams. **Dropbacks versus designed runs**, not \"pass\nplays versus run plays\": a sack or a scramble starts as a pass call, so nflverse files it under\n`pass`, while a designed quarterback run counts as a run.\n\n**Snaps wiped out by a penalty are dropped.** nflverse marks them `no_play`, and the filter above\nremoves them. That is the usual choice for \"EPA per play,\" but it is a choice, and it shades the\nrun-pass comparison:\n\n::: {#penalty-snaps .cell execution_count=2}\n``` {.python .cell-code}\nflagged = reg[(reg.season == 2025) & (reg.play_type == \"no_play\") & reg.epa.notna()\n              & ((reg[\"pass\"] == 1) | (reg[\"rush\"] == 1))]\ndpi = flagged[flagged.penalty_type == \"Defensive Pass Interference\"]\nhold = flagged[flagged.penalty_type == \"Offensive Holding\"]\nboth = reg[(reg.season == 2025) & reg.epa.notna() & reg.down.notna()\n           & reg.play_type.isin([\"pass\", \"run\", \"no_play\"])\n           & ((reg[\"pass\"] == 1) | (reg[\"rush\"] == 1))]\nwith_pen = both.groupby(np.where(both[\"pass\"] == 1, \"Dropback\", \"Designed run\")).epa.mean()\nwithout = plays[plays.season == 2025].groupby(\"kind\").epa.mean()\nprint(f\"2025 snaps wiped out by a penalty: {len(flagged):,}; \"\n      f\"defensive pass interference {len(dpi)} (mean EPA {dpi.epa.mean():+.2f}), \"\n      f\"offensive holding {len(hold)} (mean EPA {hold.epa.mean():+.2f})\")\nprint(f\"Dropback EPA/play {without['Dropback']:+.3f} without penalty snaps, \"\n      f\"{with_pen['Dropback']:+.3f} with them; designed runs \"\n      f\"{without['Designed run']:+.3f} vs {with_pen['Designed run']:+.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2025 snaps wiped out by a penalty: 1,488; defensive pass interference 279 (mean EPA +1.73), offensive holding 374 (mean EPA -1.06)\nDropback EPA/play +0.043 without penalty snaps, +0.063 with them; designed runs -0.046 vs -0.060\n```\n:::\n:::\n\n\nA coach would say that drawing a pass interference flag on a go route, or getting a hold called, is\npart of what a play call produces. Pass interference is mostly a deep-ball outcome, so leaving those\nsnaps out makes passing look a little *worse* than it is. It is also why EPA per play in this book\nwill not always match other sites: nflfastR's own beginner's guide filters on `pass == 1 | rush == 1`,\nwhich keeps penalty snaps, and says to drop `play_type == \"no_play\"` only when you want to match\nofficial statistics.[^nflfastr-guide]\n\nLast, the **garbage-time filter** for team numbers, because a defense protecting a 24-point lead in\nthe fourth quarter is playing a different game. It keeps plays where the offense's\n[**win probability**](../../appendices/glossary.qmd#gl-win-probability) (the model's chance that it\nwins the game from here, the subject of [Win Probability and Decision\nAnalysis](13-03-win-probability-and-fourth-down.qmd)) is between 10% and 90%, outside the last two\nminutes of each half. The plays that survive are what analysts call\n[**neutral situations**](../../appendices/glossary.qmd#gl-neutral-situation), and every team number\nin this chapter uses them. [Tendencies: PROE, Personnel, Motion, and\nCoverage](13-04-tendencies-proe-and-charting.qmd) formalises the idea.[^nflverse]\n\n## What expected points actually estimates\n\nThe primer in 01-02 described EP as \"what a situation is worth.\" The precise version is narrower\nand more useful: **EP is the average value of the *next score* in the same half, from the point of\nview of the team that has the ball.** The next score can be the offense's touchdown (+7), field goal\n(+3) or safety (+2, when its own defense later tackles the opponent in their end zone), the\nopponent's touchdown (−7), field goal (−3) or safety (−2), or nothing at all before halftime or the\nend of the game (0).\n\nWhy the *next* score, and not \"points on this drive\"? Because a drive that ends in a punt still\nmatters. Punting the opponent back to their own 5 makes their next score less likely and yours more\nlikely, and a model that only counted points on the current drive would score every punt as a\nzero. Counting through to the next score lets field position, punts and turnovers all carry value.\n\nWhy an *average*? Because the model knows nothing about who is playing. EP describes an average NFL\noffense against an average NFL defense in that situation. That is a feature: it gives every play the\nsame yardstick, so you can ask how much better than average a team, a quarterback or a play call was.\n\nThe simplest expected-points model is no model at all: take every first-and-10 from the same yard\nline and average what happened next. The cell below finds the next score for every play in ten\nseasons.\n\n::: {#next-score .cell execution_count=3}\n``` {.python .cell-code}\nd = reg.sort_values([\"game_id\", \"play_id\"]).copy()\n# Mark scoring plays: who scored and how many points (touchdowns count as 7).\nd[\"s_pts\"] = np.select([d.td_team.notna(), d.field_goal_result.eq(\"made\"), d.safety.eq(1)],\n                       [7, 3, 2], np.nan)\nd[\"s_team\"] = np.where(d.td_team.notna(), d.td_team,\n                       np.where(d.safety.eq(1), d.defteam, d.posteam))\nd.loc[d.s_pts.isna(), \"s_team\"] = None\n# Fill each play with the NEXT scoring play in the same game and half.\nnxt = d.groupby([\"game_id\", \"game_half\"])[[\"s_pts\", \"s_team\"]].bfill()\nd[\"next_score\"] = np.where(nxt.s_pts.isna(), 0,\n                           np.where(nxt.s_team == d.posteam, nxt.s_pts, -nxt.s_pts))\n\n# Situations the model learns from: snaps with a down (runs, passes, punts, field goals).\nsit = d[d.play_type.isin([\"pass\", \"run\", \"punt\", \"field_goal\"]) & d.down.notna()].copy()\nfirst10 = sit[(sit.down == 1) & ((sit.ydstogo == 10) | (sit.goal_to_go == 1))]\nby_yard = first10.groupby(\"yardline_100\").agg(n=(\"next_score\", \"size\"),\n                                              empirical=(\"next_score\", \"mean\"),\n                                              nflverse_ep=(\"ep\", \"mean\"))\nprint(f\"{len(sit):,} situations; {len(first10):,} first downs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n359,991 situations; 138,873 first downs\n```\n:::\n:::\n\n\n::: {#cell-fig-ep-empirical .cell execution_count=4}\n``` {.python .cell-code}\nbins = (by_yard.reset_index()\n        .assign(bin=lambda t: (t.yardline_100 - 1) // 5 * 5 + 3)\n        .groupby(\"bin\")\n        .apply(lambda g: pd.Series({\"emp\": np.average(g.empirical, weights=g.n),\n                                    \"n\": g.n.sum()}), include_groups=False))\nfig, ax = plt.subplots(figsize=(6.5, 3.6))\nax.plot(by_yard.index, by_yard.nflverse_ep, color=style.SERIES[0], lw=2,\n        label=\"nflverse model EP\")\nax.scatter(bins.index, bins.emp, s=26, color=style.SERIES[1], zorder=3,\n           edgecolor=style.SURFACE, linewidth=1, label=\"Actual average next score\")\nax.axhline(0, color=style.BASELINE, lw=1)\nax.set_xlim(100, 0)\nax.set_xticks([99, 90, 80, 70, 60, 50, 40, 30, 20, 10, 1],\n              [\"Own 1\", \"10\", \"20\", \"30\", \"40\", \"50\", \"40\", \"30\", \"20\", \"10\", \"Opp 1\"])\nax.set_xlabel(\"Ball on (offense moving right)\")\nax.set_ylabel(\"Points\")\nax.set_title(\"First-and-10: what happened next, on average\")\nax.legend(loc=\"upper left\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The expected-points idea is an average. Dots: the actual average next score after first-and-10 (first-and-goal inside the 10) at each yard line, 2016-2025, in 5-yard bins. Line: nflverse's model EP for the same plays. They agree almost everywhere; the model's job is to smooth the noise and fill the gaps.](13-02-expected-points-and-success-rate_files/figure-html/fig-ep-empirical-output-1.svg){#fig-ep-empirical}\n:::\n:::\n\n\nRead the chart from left to right as a drive moves downfield. Pinned at your own 1, the next score\nis slightly more likely to be the *opponent's*: you will probably punt from your end zone and hand\nthem good field position, and a safety is a real risk. By your own 25, for decades the spot after a\nkickoff touchback (it moved to the 30 in 2024 and the 35 in 2025),[^touchback] first-and-10 is worth\nabout 1\\.1 points. Midfield is worth about\n2\\.6; the opponent's 20, the edge of the\n[red zone](../../appendices/glossary.qmd#gl-red-zone), about 4\\.5;\nfirst-and-goal at the 1, about 6\\.3. These values\ncome back at the end of the chapter as the anchors for keeping EPA in your head.\n\n::: {.callout-important title=\"Why it exists\"}\nYards are not all worth the same. Ten yards from your own 5 to your own 15 mostly buys you room to\npunt; ten yards from the opponent's 12 to the 2 nearly turns a field goal into a touchdown. Coaches\nalways knew this (\"field position\"), but there was no common currency to compare a punt, a\nthird-down conversion and an interception. Expected points provide one: every situation gets a\npoint value, so every play can be scored by how much it changed that value.\n:::\n\n## From averages to a model\n\nIf the average works, why model at all? Because most situations are rare. First-and-10 at your own\n25 happened about two thousand times a season while it was the touchback spot; fourth-and-7 at the opponent's 38 with 1:40 left in the\nhalf happens a handful of times a decade. Average a handful of outcomes and you get noise. A model\nborrows strength from similar situations: it learns how value changes with each extra yard of field\nposition, each extra yard to go and each lost down, then applies that to situations it has seldom\nseen.\n\nThe standard approach, used by the open-source models behind nflverse, predicts the **probability of\neach of the seven next-score outcomes** and then takes the weighted average:\n\n$$\n\\text{EP} = 7\\,p_{\\text{TD}} + 3\\,p_{\\text{FG}} + 2\\,p_{\\text{Safety}} + 0\\,p_{\\text{None}}\n - 2\\,p_{\\text{Opp safety}} - 3\\,p_{\\text{Opp FG}} - 7\\,p_{\\text{Opp TD}}\n$$\n\nThe probabilities come from a **multinomial logistic regression**: a model that turns a list of\nsituation features into seven probabilities that always add up to 1. You do not need a statistics\nlibrary to fit one. The cell below does it in about thirty lines of NumPy. Four pieces are worth\nnaming before you read it:\n\n- **Features.** Yard line, down, distance and the last two minutes of a half. Distance goes in on a\n  log scale, because the difference between 1 and 3 yards to go matters more than between 11 and 13.\n  Inside the 10, \"distance\" is simply the yards to the goal line.\n- **Knots.** A straight line in yard line could not bend near the goal lines. So the features also\n  include \"how far past the 5, past the 10, past the 15 ...\" (`np.clip(y - k, 0, None)` for each\n  **knot** `k`). Each one lets the slope change at that spot, which turns a straight line into a\n  smooth bent one (a *piecewise-linear spline*).\n- **Softmax and log loss.** For each situation the model computes seven scores, one per outcome, and\n  the **softmax** turns them into seven probabilities that sum to 1. Fitting means choosing the\n  weights that make the outcomes that really happened as probable as possible. The **log loss**\n  (the average of −log of the probability given to the true outcome) is the number being pushed down.\n- **Standardising and Adam.** Each feature is rescaled to mean 0 and standard deviation 1 so that\n  no feature dominates just because of its units. Then 250 steps of gradient descent nudge the\n  weights downhill on the log loss. **Adam** is a common recipe for choosing each step's size from\n  the recent gradients; any careful step size would get to about the same place.\n\n::: {#ep-model .cell execution_count=5}\n``` {.python .cell-code}\nOUTCOMES = np.array([-7, -3, -2, 0, 2, 3, 7])\nNAMES = [\"Opp TD\", \"Opp FG\", \"Opp safety\", \"No score\", \"Safety\", \"FG\", \"TD\"]\n\n\ndef features(s):\n    \"\"\"Situation -> model features. s needs yardline_100, down, ydstogo\n    and half_seconds_remaining.\"\"\"\n    y = s[\"yardline_100\"].to_numpy() / 100\n    dn = s[\"down\"].to_numpy()\n    ytg = np.log(np.clip(s[\"ydstogo\"].to_numpy(), 1, None))\n    late = (s[\"half_seconds_remaining\"].to_numpy() <= 120).astype(float)\n    knots = (.05, .1, .15, .2, .3, .4, .5, .6, .75, .9)            # let value bend smoothly\n    cols = [np.ones_like(y), y] + [np.clip(y - k, 0, None) for k in knots]\n    cols += [(dn == k).astype(float) for k in (2, 3, 4)]          # down\n    cols += [y * (dn == k) for k in (2, 3, 4)]                    # down x field position\n    cols += [np.clip(y - .5, 0, None) * (dn == 4)]                # 4th down in own half\n    cols += [ytg] + [ytg * (dn == k) for k in (2, 3, 4)]          # distance, by down\n    cols += [late, late * y]                                      # end of the half\n    return np.column_stack(cols).astype(np.float32)\n\n\ndef softmax(z):\n    e = np.exp(z - z.max(axis=1, keepdims=True))\n    return e / e.sum(axis=1, keepdims=True)\n\n\nX = features(sit)\nY = (sit.next_score.to_numpy()[:, None] == OUTCOMES).astype(np.float32)\nmu, sd = X.mean(0), X.std(0)\nmu[0], sd[0] = 0, 1                       # leave the intercept alone\nXs = (X - mu) / sd\n\n# Fit by gradient descent on the log loss (Adam step sizes).\nW = np.zeros((X.shape[1], len(OUTCOMES)), dtype=np.float32)\nm, v = np.zeros_like(W), np.zeros_like(W)\nfor i in range(1, 251):\n    g = Xs.T @ (softmax(Xs @ W) - Y) / len(Xs)\n    m, v = 0.9 * m + 0.1 * g, 0.999 * v + 0.001 * g**2\n    W -= 0.05 * (m / (1 - 0.9**i)) / (np.sqrt(v / (1 - 0.999**i)) + 1e-8)\n\n\ndef ep_probs(down, ydstogo, yardline_100, late=False):\n    \"\"\"Next-score probabilities for situations (arrays broadcast together).\"\"\"\n    yl = np.atleast_1d(yardline_100).astype(float)\n    s = pd.DataFrame({\"yardline_100\": yl, \"down\": down,\n                      \"ydstogo\": np.minimum(ydstogo, yl),      # goal-to-go inside the 10\n                      \"half_seconds_remaining\": 60 if late else 900})\n    return softmax((features(s) - mu) / sd @ W)\n\n\ndef my_ep(down, ydstogo, yardline_100, late=False):\n    return ep_probs(down, ydstogo, yardline_100, late) @ OUTCOMES\n\n\nsit[\"my_ep\"] = softmax(Xs @ W) @ OUTCOMES\nr_ep = np.corrcoef(sit.my_ep, sit.ep)[0, 1]\nprint(f\"Correlation with nflverse EP: {r_ep:.3f}; \"\n      f\"mean absolute gap: {np.abs(sit.my_ep - sit.ep).mean():.2f} points\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCorrelation with nflverse EP: 0.983; mean absolute gap: 0.25 points\n```\n:::\n:::\n\n\nThirty lines of NumPy land within about a quarter of a point of nflverse's model on a typical play,\nwith a correlation of 0\\.98. The real model is better (more on that below), but\nnothing about expected points is magic. It is a probability model for \"who scores next,\" fitted to\na decade of football.\n\nThe probabilities are worth seeing on their own, because they explain the shape of the EP curve.\n\n::: {#cell-fig-ep-probs .cell execution_count=6}\n``` {.python .cell-code}\nyl = np.arange(99, 0, -1)\nP = ep_probs(1, 10, yl)                           # 900 seconds left in the half\nown25 = dict(zip(NAMES, ep_probs(1, 10, 75)[0]))\nnone_late = ep_probs(1, 10, 75, late=True)[0][NAMES.index(\"No score\")]\norder = [6, 5, 4, 3, 2, 1, 0]                     # TD at the bottom, Opp TD on top\ncolors = {6: style.SERIES[0], 5: \"#9ec5f4\", 4: \"#cde2fb\", 3: style.GRID,\n          2: \"#fbd3c2\", 1: \"#f5a27f\", 0: style.SERIES[1]}\nfig, ax = plt.subplots(figsize=(6.5, 3.6))\nax.stackplot(yl, *[P[:, k] for k in order], colors=[colors[k] for k in order],\n             labels=[NAMES[k] for k in order], edgecolor=style.SURFACE, linewidth=0.6)\nax.set_xlim(99, 1)\nax.set_ylim(0, 1)\nax.set_xticks([99, 75, 50, 25, 1], [\"Own 1\", \"Own 25\", \"50\", \"Opp 25\", \"Opp 1\"])\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\nax.set_ylabel(\"Probability of next score\")\nax.set_title(\"First-and-10: who scores next?\")\nax.grid(False)\nh, lab = ax.get_legend_handles_labels()\nax.legend(h[::-1], lab[::-1], loc=\"center left\", bbox_to_anchor=(1.01, 0.5), fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Next-score probabilities for first-and-10 (first-and-goal inside the 10) from the model above, with 15 minutes left in the half. The offense's touchdown chance (dark blue) grows steadily as the ball moves; its field-goal band (light blue) widens through the opponent's half but never overtakes the touchdown band; the opponent's chances (orange) shrink. EP is the weighted sum of these bands.](13-02-expected-points-and-success-rate_files/figure-html/fig-ep-probs-output-1.svg){#fig-ep-probs}\n:::\n:::\n\n\nTwo things jump out. First, at your own 25 the offense is more likely than the opponent to score\nnext, but not by much: its touchdown and field goal together come to\n55%, against 35%\nfor the opponent's. That narrow edge is why first-and-10 there is worth only about a point. Second,\nwith a full quarter left, \"no score\" is a thin band (10% at your own\n25): halves are long enough that somebody almost always scores. The chart is drawn at one clock\nvalue; the model's end-of-half feature changes the picture. With under two minutes left, \"no score\"\nat the same spot jumps to 63%, which is why a long gain as the half runs out\ncan be worth surprisingly little.\n\nNow the curve itself: EP by yard line, one line per down.\n\n::: {#cell-fig-ep-by-down .cell execution_count=7}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6.5, 3.8))\nfor k, dn in enumerate([1, 2, 3, 4]):\n    ep = my_ep(dn, 10, yl)\n    ax.plot(yl, ep, color=style.SERIES[k], lw=2, label=f\"{dn}{['st','nd','rd','th'][k]} & 10\")\nax.axhline(0, color=style.BASELINE, lw=1)\nax.set_xlim(100, 0)\nax.set_xticks([99, 75, 50, 25, 1], [\"Own 1\", \"Own 25\", \"50\", \"Opp 25\", \"Opp 1\"])\nax.set_ylabel(\"Expected points\")\nax.set_title(\"Each down you use up costs points\")\nax.legend(loc=\"upper left\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Expected points by field position for each down at 10 yards to go (goal-to-go inside the 10), from the model above. The gaps between the lines are the cost of a lost down at that spot. The 3rd-to-4th gap is widest from about midfield to the opponent's 40, where fourth-and-10 almost always means a punt from a promising spot; in field-goal range it narrows, because a kick is still likely to score.](13-02-expected-points-and-success-rate_files/figure-html/fig-ep-by-down-output-1.svg){#fig-ep-by-down}\n:::\n:::\n\n\nThe rules of thumb you will use in your head come straight from the model. One cell computes them\nall at midfield:\n\n::: {#rules-of-thumb .cell execution_count=8}\n``` {.python .cell-code}\nslope = (my_ep(1, 10, 30)[0] - my_ep(1, 10, 70)[0]) / 40            # per yard, between the 20s\ncost = {f\"{a}->{a + 1}\": my_ep(a, 10, 50)[0] - my_ep(a + 1, 10, 50)[0] for a in (1, 2, 3)}\nper_ytg = (my_ep(2, 6, 50)[0] - my_ep(2, 10, 50)[0]) / 4            # 2nd & 10 -> 2nd & 6\nfour_yd_run = my_ep(2, 6, 46)[0] - my_ep(1, 10, 50)[0]              # 1st & 10 at 50, gain 4\nfive_yd_run = my_ep(2, 5, 45)[0] - my_ep(1, 10, 50)[0]              # ... gain 5\nprint(f\"one yard of field position: {slope:+.3f}\")\nprint(\"one lost down, 10 to go:\", \", \".join(f\"{k} {v:.2f}\" for k, v in cost.items()))\nprint(f\"one yard less to go (2nd down, 6-10 to go): {per_ytg:+.3f}\")\nprint(f\"gain on 1st & 10 at midfield: 4 yards EPA {four_yd_run:+.2f}, 5 yards {five_yd_run:+.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\none yard of field position: +0.061\none lost down, 10 to go: 1->2 0.68, 2->3 0.97, 3->4 1.43\none yard less to go (2nd down, 6-10 to go): +0.069\ngain on 1st & 10 at midfield: 4 yards EPA -0.12, 5 yards +0.04\n```\n:::\n:::\n\n\nFour habits of the curve are worth memorising:\n\n- **Between the 20s, each yard of field position is worth about 0\\.06 points**\n  on first-and-10. Forty yards is worth about 2\\.5 points: most of a field\n  goal.\n- **A lost down costs more the later it is.** At midfield on 10 to go, first to second down costs\n  about 0\\.7, second to third about 1\\.0, and\n  third to fourth about 1\\.4. An incomplete pass on first down does not\n  \"cost nothing\"; it moves you from the first-down line to the second-down line.\n- **Each yard closer to the line to gain is also worth something**: about\n  0\\.07 points per yard of distance on second down, on top of the field-position\n  value. A gain moves the ball *and* shortens the distance, so it earns both. That is why a 4-yard\n  run on first-and-10 at midfield nets only about \\-0\\.12 despite costing a\n  down worth 0\\.68: 4 yards of field position plus 4 yards less to go pay\n  for most of it, and a 5-yard gain (\\+0\\.04) about breaks even.\n- **The curve bends at both ends.** Near your own goal line the risk of a safety and of a short field\n  for the opponent drags value down. Near the opponent's goal line the jump from a likely field goal\n  to a likely touchdown makes each yard worth more.\n\n::: {.callout-caution title=\"Common misconception\"}\n\"The fourth-down line shows what fourth down is worth.\" It shows what fourth down has been worth\n*given what coaches usually did*: the model learned from history, when most fourth downs ended in a\npunt or a field goal, and teams have gone for it more since about 2018 (in nflverse data, on about\n13% of fourth downs in 2016 and 23% in 2025). So the fourth-down curve\nbakes in the league's usual decision. Whether that decision was right is a win-probability question,\nanswered in [Win Probability and Decision Analysis](13-03-win-probability-and-fourth-down.qmd).\n:::\n\n### What the real model adds\n\nThe nflverse model was built by Ben Baldwin and Sebastian Carl for the **nflfastR** project in\n2020.[^nflfastr] It uses the same seven outcomes but a more flexible learner (gradient-boosted\ntrees, XGBoost) and more inputs: seconds left in the half, each team's timeouts, whether the\noffense is at home, roof type, and an \"era\" variable so that the 2000s and the 2020s can differ. It\nalso down-weights plays from lopsided games and plays that are several drives away from the next\nscore, so that the fit leans on the plays most connected to the outcome.\n\nDo the 2024 and 2025 kickoff changes break the model? Mostly not. EP stops counting at the next\nscore, so the kickoff that follows a score is outside it. The new touchback spots change *where*\ndrives start (far more of them now begin at the 35), not what first-and-10 at the 35 is worth.\n\nThe other thing to know before using nflverse EPA: it is credited to plays, not people. For a\ncompletion, nflverse splits the EPA into `air_epa` (the value up to the catch point) and `yac_epa`\n(the value added after the catch). That split is the usual first step in asking whether a 60-yard\ncatch-and-run belonged to the quarterback or the receiver.\n\nJust as important is what EP **leaves out**:\n\n- **The score.** EP asks who scores next, not who wins. A field goal when trailing by 4 with two\n  minutes left is worth the same 3 points as one in the first quarter. Win probability, the\n  score-aware cousin, is the subject of [Win Probability and Decision\n  Analysis](13-03-win-probability-and-fourth-down.qmd).\n- **Who is playing.** The Chiefs at their own 25 are worth more than an expansion team at its own\n  25, but EP gives them the same value.\n- **The play call.** EP knows the situation before the snap, not the [personnel](../../appendices/glossary.qmd#gl-personnel-grouping),\n  formation or coverage.\n\n::: {.callout-note title=\"Go deeper\"}\nBefore nflfastR, the reference open model was **nflscrapR** (2017-2019), by Maksim Horowitz, Ron\nYurko and Sam Ventura at Carnegie Mellon. Their paper fitted exactly the kind of multinomial\nlogistic regression above, then used it to build a wins-above-replacement measure for\nplayers (how many wins a player adds compared with a cheap backup who could replace\nhim).[^nflwar] Reading it after this section is a good exercise: you will recognise every step.\n:::\n\n## Where expected points came from\n\nThe first expected-points table was built by a working NFL quarterback. In 1971 **Virgil Carter**,\nthen with the Cincinnati Bengals, and **Robert Machol**, an operations-research professor at\nNorthwestern, published \"Operations Research on Football\" in the journal *Operations\nResearch*.[^carter] Carter asked every team's public-relations office for its play-by-play sheets\nfrom the first half of the 1969 season, coded 8,373 plays from 56 games, and averaged the next score\nafter a first-and-10 from each 10-yard strip of the field: exactly the first chart in this chapter,\ndone before personal computers. Carter had earned a master's degree at Northwestern while playing for\nthe Bears, and he thought about football the way an engineer would: as a problem with measurable\nstates. He is also remembered as the quarterback of Bill Walsh's early short-passing offense in\nCincinnati, the system that later became known as the West Coast offense.\n\nIn 1988 Bob Carroll, Pete Palmer and John Thorn's *The Hidden Game of Football* made the idea\npopular with a simple straight line: a first down at your own goal line is worth −2 points, at the\nopponent's goal line +6, and every yard in between is worth the same 0.08 points (so your own 25 is\nworth zero).[^hidden] The line was crude, but it gave fans a currency for field position.\n\nThe modern version arrived with the internet. Brian Burke, a former Navy F/A-18 pilot, built\nexpected-points and win-probability models on his Advanced NFL Stats site from 2007 and helped\npopularise EPA before joining ESPN's analytics group in 2015.[^burke] Then came the open-source turn:\nnflscrapR (2017) put a full EP model and every play since 2009 into R, and nflfastR (2020) rebuilt\nit to be faster and more accurate. Today the same numbers flow into Python through\n[nflverse](../../appendices/glossary.qmd#gl-nflverse), which is why you can reproduce every chart here.\n\n::: {.callout-caution title=\"Common misconception\"}\n\"EPA is a single official number.\" It is not. ESPN, Next Gen Stats, PFF and nflverse each run their\nown expected-points models, and their EPA for the same play can differ by a few tenths of a point.\nThe ideas are the same; the fitted numbers are not. When you compare EPA from two sources, check\nthat it is the same model, and in this book it is always nflverse's.\n:::\n\n## One play's EPA, worked by hand\n\nEPA is one subtraction:\n\n$$\n\\text{EPA} = \\text{EP}_{\\text{after}} - \\text{EP}_{\\text{before}}\n$$\n\nTwo rules handle the special cases. **If the play scores**, EP after is the points scored. For a\ntouchdown nflverse uses 7, not 6: an extra point is made almost every time, so the model books the\ntouchdown at its usual final value. The extra-point play then gets its own small EPA (a made kick is\nworth a few hundredths more than the 1 point already assumed; a miss costs about a point).\n**If the ball changes hands**, EP\nafter is the *negative* of the new offense's EP, because their gain is your loss. The three Super\nBowl LX plays from the opening of this chapter cover all three cases.\n\n::: {#cell-lx-plays .cell execution_count=9}\n``` {.python .cell-code}\nlx = raw[raw.game_id == \"2025_22_SEA_NE\"].sort_values(\"play_id\")\npicked = lx[lx.play_id.isin([2858, 3166, 3910])]\nmd_table(picked.assign(\n    situation=lambda t: t.down.astype(int).astype(str) + \" & \" + t.ydstogo.astype(int).astype(str),\n    ep_before=lambda t: t.ep, ep_after=lambda t: t.ep + t.epa)\n    [[\"qtr\", \"posteam\", \"situation\", \"yardline_100\", \"yards_gained\",\n      \"ep_before\", \"ep_after\", \"epa\"]])\n```\n\n::: {#lx-plays .cell-output .cell-output-display .cell-output-markdown execution_count=9}\n| qtr | posteam | situation | yardline_100 | yards_gained | ep_before | ep_after | epa |\n| ---: | :--- | :--- | ---: | ---: | ---: | ---: | ---: |\n| 3 | SEA | 3 & 12 | 81 | 8 | -1.59 | -1.70 | -0.11 |\n| 4 | SEA | 1 & 10 | 16 | 16 | 4.64 | 7.00 | 2.36 |\n| 4 | NE | 1 & 10 | 44 | 0 | 2.81 | -7.00 | -9.81 |\n:::\n:::\n\n\n::: {#cell-fig-epa-worked .cell execution_count=10}\n``` {.python .cell-code}\nfrom matplotlib.patches import FancyArrowPatch, Circle\nfrom gridiron import Field\n\nCASES = [\n    dict(title=\"SEA 3rd & 12 at own 19: Darnold to Kupp, 8 yards\",\n         los=29, togo=12, end=37, color=style.OFFENSE_DARK,\n         before=\"EP before: −1.59\\n(3rd & 12, own 19)\",\n         after=\"EP after: −1.70\\n(4th & 4, own 27)\",\n         sum=\"EPA = −1.70 − (−1.59) = −0.11\"),\n    dict(title=\"SEA 1st & 10 at NE 16: Darnold to Barner, 16-yard touchdown\",\n         los=94, togo=10, end=110, color=style.OFFENSE_DARK,\n         before=\"EP before: +4.64\\n(1st & 10, opp 16)\",\n         after=\"After: touchdown = +7\",\n         sum=\"EPA = 7 − 4.64 = +2.36\"),\n    dict(title=\"NE 1st & 10 at SEA 44: Maye intercepted by Nwosu, returned 45 yards for a TD\",\n         los=66, togo=10, end=55, color=style.DEFENSE_DARK, ret=10,\n         before=\"EP before: +2.81\\n(1st & 10, opp 44)\",\n         after=\"After: SEA touchdown = −7\\nfor New England\",\n         sum=\"EPA = −7 − 2.81 = −9.81\"),\n]\nfig, axes = plt.subplots(3, 1, figsize=(6.5, 7.6))\nfor ax, c in zip(axes, CASES):\n    Field(ax=ax, orient=\"horizontal\", los=c[\"los\"], window=(-c[\"los\"], 120 - c[\"los\"]),\n          to_go=c[\"togo\"], lateral=(9.5, 43.8))\n    yb = 26.7                                     # ball on the middle of the field\n    ax.add_patch(Circle((c[\"los\"], yb), 1.3, color=style.BALL, zorder=6))\n    if \"ret\" in c:   # pass picked off 11 yards BEHIND the line, then returned the other way\n        ax.add_patch(FancyArrowPatch((c[\"los\"], yb), (c[\"end\"], yb - 4), arrowstyle=\"-|>\",\n                     mutation_scale=10, color=style.OFFENSE, lw=1.4, ls=(0, (2, 2)), zorder=5))\n        ax.add_patch(FancyArrowPatch((c[\"end\"], yb - 4), (c[\"ret\"] - 4, yb - 4),\n                     arrowstyle=\"-|>\", mutation_scale=12, color=c[\"color\"], lw=2.6, zorder=5))\n        ax.text(c[\"end\"] - 1.5, yb - 3.2, \"picked off at NE 45,\\n11 yds behind the line\",\n                ha=\"right\", va=\"bottom\", fontsize=7, color=style.INK_2, zorder=8)\n    else:\n        ax.add_patch(FancyArrowPatch((c[\"los\"], yb), (c[\"end\"], yb), arrowstyle=\"-|>\",\n                     mutation_scale=12, color=c[\"color\"], lw=2.6, zorder=5))\n    box = dict(boxstyle=\"round,pad=0.3\", fc=style.SURFACE, ec=style.BASELINE, lw=0.6)\n    ax.text(c[\"los\"], 33.5, c[\"before\"], ha=\"center\", va=\"bottom\", fontsize=7.5,\n            color=style.INK, bbox=box, zorder=8)\n    # the \"after\" box sits at the spot where the play ended, between the yard numbers\n    ax_x, ax_y = (c[\"end\"], 23.0) if \"ret\" not in c else (30, 19.0)\n    ax.text(ax_x, ax_y, c[\"after\"], ha=\"center\",\n            va=\"top\", fontsize=7.5, color=style.INK, bbox=box, zorder=8)\n    ax.set_title(c[\"title\"], loc=\"left\", fontsize=9, fontweight=\"bold\", color=style.INK)\n    ax.text(0.99, 0.04, c[\"sum\"], transform=ax.transAxes, ha=\"right\", va=\"bottom\",\n            fontsize=9, fontweight=\"bold\", color=style.INK, zorder=9,\n            bbox=dict(boxstyle=\"round,pad=0.3\", fc=style.SURFACE, ec=style.INK_2, lw=0.8))\nfig.tight_layout(h_pad=1.6)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Three Super Bowl LX plays (February 8, 2026), each drawn with the offense moving right; the yellow line is the line to gain. Top: the catch stops 4 yards short of the yellow line, so third-and-12 becomes fourth-and-4 and the play loses value. Middle: a 16-yard touchdown is worth 7 minus the 4.64 the situation already promised. Bottom: the play-by-play credits Devon Witherspoon with both a hit on Drake Maye and the pass defensed, and the ball was intercepted 11 yards behind the line (so the dashed arrow runs backward), then returned for a touchdown: it costs the 2.81 New England had plus the 7 Seattle scored.](13-02-expected-points-and-success-rate_files/figure-html/fig-epa-worked-output-1.svg){#fig-epa-worked}\n:::\n:::\n\n\nWalk through the first one yourself, the way you will on Sunday. Before the snap Seattle has\nthird-and-12 at its own 19. That is a bad situation: most of the time the offense punts, and the\nmodel says it is worth about −1.6 points (the opponent is slightly more likely to score next). The\n8-yard catch leaves fourth-and-4 at the 27. The ball is 8 yards further on, but Seattle has also\nburned its last useful down; it will punt, and fourth-and-4 at the 27 is worth about −1.7. The\ndifference, −0.11, is the completion's EPA. That does not mean an incompletion would have been\nbetter: fourth-and-12 at the 19 is worse still, and the extra 8 yards improved the punt. But the\ncompletion did not improve on *the situation Seattle was already in*, and that is what EPA grades\nagainst. The question EPA asks is never \"did you gain yards?\" but \"are you better off than before\nthe snap?\"\n\nThe third play shows why turnovers dominate EPA. New England had first-and-10 in Seattle territory,\na situation worth +2.81. One throw later Seattle had 7 points. The swing is the sum of the two:\neverything New England was about to earn plus everything Seattle scored.\n\nAn interception without a touchdown return works the same way, and you can price it with the\nchapter's own model. Say a team with first-and-10 at midfield throws a pick and the return leaves the\nopponent first-and-10 at its own 45:\n\n::: {#int-arithmetic .cell execution_count=11}\n``` {.python .cell-code}\nbefore_int = my_ep(1, 10, 50)[0]          # your first-and-10 at midfield\nopp_after = my_ep(1, 10, 55)[0]           # their first-and-10 at their own 45\nprint(f\"EP before {before_int:+.2f}; EP after = -({opp_after:.2f}); \"\n      f\"EPA = {-opp_after - before_int:+.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEP before +2.65; EP after = -(2.37); EPA = -5.02\n```\n:::\n:::\n\n\nYou lose the value you had *and* hand the opponent a good starting spot. In the real data,\nnon-touchdown interceptions thrown from around midfield cost about three and a half to four points\non average, and no other common play moves the ledger as much.\n\nEPA also has a blind spot that these plays expose. When Nwosu scored, nflverse's win probability\ngave New England 3% before the snap; at the\nKupp catch, Seattle was already at 89%.\nEPA says the interception was the costliest play of the night; win probability says the game was\nalready decided. EP ignores the score by design, and that is the gap\n[Win Probability and Decision Analysis](13-03-win-probability-and-fourth-down.qmd) fills.\n\n## Why EPA beats yards\n\nYards per play is the stat broadcasts reach for first, and it is not useless. But it treats a yard\nas a yard. The cell below collects plays that gained **exactly 8 yards** in four different\nsituations, 2016-2025.\n\n::: {#cell-same-yards .cell execution_count=12}\n``` {.python .cell-code}\np8 = plays[plays.yards_gained == 8]\ncases = {\n    \"1st & 10, own 20-30 (leaves 2nd & 2)\":\n        (p8.down == 1) & (p8.ydstogo == 10) & p8.yardline_100.between(70, 80),\n    \"3rd & 10-12 (short of the sticks)\":\n        (p8.down == 3) & p8.ydstogo.between(10, 12) & (p8.yardline_100 > 20),\n    \"3rd & 5-7 (moves the chains)\":\n        (p8.down == 3) & p8.ydstogo.between(5, 7) & (p8.yardline_100 > 20),\n    \"Any down, ball on the 8 (touchdown)\": p8.yardline_100 == 8,\n}\nmd_table(pd.DataFrame([{\"8-yard gain on\": k, \"plays\": int(m.sum()),\n                        \"average EPA\": p8.loc[m, \"epa\"].mean()} for k, m in cases.items()]))\n```\n\n::: {#same-yards .cell-output .cell-output-display .cell-output-markdown execution_count=12}\n| 8-yard gain on | plays | average EPA |\n| :--- | ---: | ---: |\n| 1st & 10, own 20-30 (leaves 2nd & 2) | 1,183 | 0.46 |\n| 3rd & 10-12 (short of the sticks) | 287 | -0.32 |\n| 3rd & 5-7 (moves the chains) | 508 | 1.46 |\n| Any down, ball on the 8 (touchdown) | 405 | 2.25 |\n:::\n:::\n\n\nThe same 8 yards range from a loss of value to more than a point and a half. That is the first\nreason EPA beats yards: **context**. The second is **completeness**. Yards cannot price a turnover\n(an interception gains \"0 yards\"), barely register a sack, and ignore whether a gain came on\nfirst-and-10 or third-and-20. EPA prices all of them in the same unit, points.\n\nThe third reason is that EPA lines up with the scoreboard. Over all regular-season games from 2016\nto 2025, here is how well each per-game offensive stat tracks the points that team scored in the same\ngame, and how well the first nine weeks of a season predict points per game over the rest of it.\n\n::: {#cell-epa-vs-yards .cell execution_count=13}\n``` {.python .cell-code}\nscores = reg.drop_duplicates(\"game_id\")[[\"game_id\", \"season\", \"week\", \"home_team\",\n                                         \"away_team\", \"home_score\", \"away_score\"]]\nkeep = [\"game_id\", \"season\", \"week\", \"team\", \"pf\"]           # one row per team per game\npts = pd.concat([\n    scores.rename(columns={\"home_team\": \"team\", \"home_score\": \"pf\"})[keep],\n    scores.rename(columns={\"away_team\": \"team\", \"away_score\": \"pf\"})[keep]])\ngame = (plays.groupby([\"game_id\", \"posteam\"])\n        .agg(epa_play=(\"epa\", \"mean\"), yds_play=(\"yards_gained\", \"mean\"),\n             success=(\"success\", \"mean\"))\n        .reset_index().rename(columns={\"posteam\": \"team\"})\n        .merge(pts, on=[\"game_id\", \"team\"]))\nsame_game = game[[\"epa_play\", \"yds_play\", \"success\"]].corrwith(game.pf)\n\nearly = game[game.week <= 9].groupby([\"season\", \"team\"])[\n    [\"epa_play\", \"yds_play\", \"success\", \"pf\"]].mean()\nlate = game[game.week >= 10].groupby([\"season\", \"team\"]).pf.mean()\npredict = early.corrwith(late.reindex(early.index))\nmd_table(pd.DataFrame({\n    \"stat (offense)\": [\"EPA per play\", \"Yards per play\", \"Success rate\", \"Points per game\"],\n    \"same-game r with points\": [same_game.epa_play, same_game.yds_play, same_game.success, 1.0],\n    \"weeks 1-9 r with later points\": [predict.epa_play, predict.yds_play, predict.success,\n                                     predict.pf]}))\n```\n\n::: {#epa-vs-yards .cell-output .cell-output-display .cell-output-markdown execution_count=13}\n| stat (offense) | same-game r with points | weeks 1-9 r with later points |\n| :--- | ---: | ---: |\n| EPA per play | 0.78 | 0.49 |\n| Yards per play | 0.65 | 0.45 |\n| Success rate | 0.56 | 0.44 |\n| Points per game | 1.00 | 0.47 |\n:::\n:::\n\n\nTwo honest conclusions. **Descriptively**, EPA per play explains a game's points much better than\nyards per play (a correlation near 0\\.78 against\n0\\.65). **Predictively**, the edge is real but small: half a season\nof EPA per play predicts the second half's scoring a little better than yards per play and about as\nwell as points themselves. EPA is not a crystal ball. Its value is that it says *why* a team scored,\nplay by play, in a unit that adds up.\n\n## Success rate: the consistency half of the picture\n\nThe primer defined success as a play with positive EPA, which is the nflverse `success` column.\nYou will also meet an older, yardage-based definition that goes back to *The Hidden Game of Football*\nand was popularised by Football Outsiders: a play is successful if it gains **40% of the needed yards\non first down, 60% on second down, and all of them on third or fourth down**. (Football Outsiders\nalso used a 45% first-down threshold for some measures, so check which version a source means.)[^fo-sr]\nThe two agree on most plays, and the rules of thumb above say why: a 4-yard gain on first-and-10\nbuys 4 yards of field position *and* 4 yards less to go, which together pay for most of the down\n(the midfield example came out at \\-0\\.12, and 5 yards about breaks even).\nSo \"gain 40% on first down\" is close to \"don't lose expected points,\" set a little generously.\n\n::: {#success-defs .cell execution_count=14}\n``` {.python .cell-code}\nneed = np.select([plays.down == 1, plays.down == 2], [0.4, 0.6], 1.0) * plays.ydstogo\nold_success = plays.yards_gained >= need\nagree = (old_success == (plays.success == 1)).mean()\nprint(f\"The two definitions agree on {agree:.0%} of plays\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe two definitions agree on 92% of plays\n```\n:::\n:::\n\n\nMost of the disagreements are on first down: gains of 4 or 5 yards that pass the 40% test but come\nout slightly negative in EPA, because the 40% line sits a little below EP's break-even. Most of the\nrest go the other way, on second and third down: gains that fall short of the yardage target but\nstill improve the situation, often by moving a team into field-goal range. Turnovers are only a\nsmall share.\n\nYou will rarely hear a coach say \"success rate.\" The sideline words are **staying on schedule**\n(the idea from [Early Downs and Field Zones](../10-situational-football/10-01-early-downs-and-field-zones.qmd)),\n**winning first down** and **efficiency**. The 40/60/100 rule is a way of turning \"on schedule\" into a\nnumber: 4 of 10 yards on first down leaves a manageable second down.\n\nWhy keep a second efficiency number at all, when EPA per play already exists? Because they\nsummarise different shapes. **EPA per play is a mean**, and football outcomes are lumpy: a few huge\ngains and a few turnovers move a team's average more than dozens of ordinary snaps. **Success rate\nis a frequency**: how often did the offense stay on schedule? It ignores how big a success was (a\n4-yard gain on first-and-10 and a 70-yard touchdown both count as one). That makes it less sensitive\nto a few freak plays, but it also throws away the size of each play, and size is what produces\npoints. The table above already showed the cost: of the four stats, success rate was the weakest\nguide to a team's later scoring. The stability section below shows the benefit, and how small it is.\n\nThat lumpiness has a name you will hear on every broadcast. **[Explosive play rate](../../appendices/glossary.qmd#gl-explosive-play-rate)**\nis the share of plays that gain a big chunk, and the definition depends on who is counting. Coaching\nstaffs often chart **runs of 12+ yards and passes of 16+**; that is how the Raiders under Dennis Allen\n(2012) and the Cowboys under offensive coordinator Scott Linehan (2016) described it.[^explosive-coach]\nAnalysts more often use **10+ and 20+**, roughly the top tenth of runs and of passes, and other cut-offs\ncirculate too.[^explosive] This chapter uses 10+/20+; the cell computes both.\n\n::: {#explosives .cell execution_count=15}\n``` {.python .cell-code}\np25 = plays[plays.season == 2025].copy()\nfor name, run_cut, pass_cut in [(\"10+/20+\", 10, 20), (\"12+/16+\", 12, 16)]:\n    big = np.where(p25.kind == \"Designed run\", p25.yards_gained >= run_cut,\n                   p25.yards_gained >= pass_cut)\n    share = p25.loc[big, \"epa\"].sum() / p25.loc[p25.epa > 0, \"epa\"].sum()\n    print(f\"2025, {name}: {big.mean():.1%} of plays were explosive; \"\n          f\"they produced {share:.0%} of all positive EPA\")\np25[\"explosive\"] = np.where(p25.kind == \"Designed run\", p25.yards_gained >= 10,\n                            p25.yards_gained >= 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2025, 10+/20+: 8.9% of plays were explosive; they produced 37% of all positive EPA\n2025, 12+/16+: 10.5% of plays were explosive; they produced 44% of all positive EPA\n```\n:::\n:::\n\n\nOn either definition, about one play in ten produces well over a third of all the value offenses\ncreate. That is why explosive plays decide games, and also why a team's EPA per play can swing on two\nor three of them. Treat explosive play rate as a measure of *what happened* more than of *what will\nhappen*: as the stability chart below shows, it repeats from year to year less well than plain\nefficiency.\n\n## Run versus pass, honestly\n\nEvery season the same chart circulates: dropbacks average positive EPA, designed runs average\nnegative EPA, therefore teams should pass more. The first half of that is true.\n\n::: {#cell-fig-epa-dist .cell execution_count=16}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6.5, 3.5))\nedges = np.arange(-4, 4.01, 0.2)\nfor k, kind in enumerate([\"Dropback\", \"Designed run\"]):\n    raw_e = p25.loc[p25.kind == kind, \"epa\"]\n    e = raw_e.clip(-4, 3.999)\n    ax.hist(e, bins=edges, weights=np.full(len(e), 1 / len(e)), histtype=\"step\", lw=2,\n            color=style.SERIES[k],\n            label=f\"{kind}s: mean {raw_e.mean():+.2f}, median {raw_e.median():+.2f}, \"\n                  f\"success {p25.loc[p25.kind == kind, 'success'].mean():.0%}\")\nax.axvline(0, color=style.BASELINE, lw=1)\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\nax.set_xlabel(\"EPA on the play (plays beyond ±4 piled into the end bins)\")\nax.set_ylabel(\"Share of plays in each bin\")\nax.set_title(\"Dropbacks win on average; the typical play is a small loss either way\")\nax.legend(loc=\"upper center\", bbox_to_anchor=(0.5, -0.2), fontsize=8)\nplt.show()\nlg_mean, lg_median = p25.epa.mean(), p25.epa.median()\n```\n\n::: {.cell-output .cell-output-display}\n![EPA per play for 2025 regular-season dropbacks and designed runs, as the share of plays in each 0.2-point bin. Runs cluster tightly just below zero; dropbacks are spread wider in both directions (sacks and interceptions on the left, big completions on the right). The end bins at ±4 collect every play beyond ±4, which is why they spike. Dropbacks have the higher average and the higher success rate, but their median is no better than a run's.](13-02-expected-points-and-success-rate_files/figure-html/fig-epa-dist-output-1.svg){#fig-epa-dist}\n:::\n:::\n\n\nWhy are both medians *negative*? Because EPA is lopsided. Across all 2025 scrimmage plays, the\naverage EPA is close to zero (\\+0\\.01), as it should be for a model built to\ndescribe the average outcome. But the median play is \\-0\\.17: most snaps are\nincompletions, short gains and stuffs that each lose a little, and a smaller number of long gains\nand touchdowns win a lot and pay for them. So \"the typical play\" loses value for both runs and\ndropbacks. What separates the two piles is the right tail: dropbacks produce more of the big wins.\n\nThe second half, \"therefore pass more,\" needs care, because the two piles of plays were not run in\nthe same situations. Statisticians call this a **selection effect**: the plays were selected into\neach group for reasons that also affect their results. Four of them matter here.\n\n1. **What counts as a pass.** The dropback pile includes sacks (about −1.7 EPA each in 2025) and\n   scrambles (about +0.5), while the run pile includes designed quarterback runs, some of the best\n   runs in football. It also includes plays a coach would not file where the data does.\n   [**Screens**](../../appendices/glossary.qmd#gl-screen) are thrown, so they count as dropbacks, yet\n   coaches treat them as long handoffs, an extension of the run game. On an\n   [**RPO**](../../appendices/glossary.qmd#gl-rpo) (run-pass option) the label is whatever the\n   quarterback decided *after* the snap, so the run and pass piles are not clean play *calls*. And\n   [play-action](../../appendices/glossary.qmd#gl-play-action) passes are dropbacks that borrow their\n   value from the run game's look. Know what is in each pile before you compare them.\n2. **Down and distance.** Teams run most on short yardage, where runs succeed often, and pass most\n   on third-and-long, where everything is hard. Both of those flatter runs. Two smaller effects push\n   the other way: the few runs on third-and-long are often \"give-up\" draws that make runs look worse,\n   and passes on second-and-short lean heavily on play-action against defenses loaded for the run,\n   which makes passes look better.\n3. **Score and clock.** Leading teams run to shorten the game, often into defenses that know it.\n   Trailing teams pass into soft coverage that concedes underneath yards. The garbage-time filter\n   removes the worst of this.\n4. **The defense's choice.** Offenses run more against [light boxes](../../appendices/glossary.qmd#gl-light-box)\n   and pass more against [loaded](../../appendices/glossary.qmd#gl-loaded-box) ones; the defense has\n   already guessed. Neither average is \"the value of a run\" in a vacuum.\n\nThe fairest simple comparison holds the situation fixed. The next chart compares runs and dropbacks\nwithin the same down-and-distance buckets, using neutral game states from the last five seasons.\n\n::: {#cell-fig-run-pass-situation .cell execution_count=17}\n``` {.python .cell-code}\nq = neutral[neutral.season.between(2021, 2025)].copy()\nq[\"situation\"] = np.select(\n    [(q.down == 1) & (q.ydstogo == 10), (q.down == 2) & (q.ydstogo >= 7),\n     (q.down == 3) & (q.ydstogo >= 7), (q.down >= 2) & (q.ydstogo <= 2)],\n    [\"1st & 10\", \"2nd & 7+\", \"3rd & 7+\", \"2nd-4th & 1-2\"], \"other\")\nq = q[q.situation != \"other\"]\ntab = (q.groupby([\"situation\", \"kind\"]).agg(epa=(\"epa\", \"mean\"), sr=(\"success\", \"mean\"))\n       .unstack(\"kind\"))\nrun_share = q.groupby(\"situation\").kind.apply(lambda s: (s == \"Designed run\").mean())\norder = [\"1st & 10\", \"2nd & 7+\", \"3rd & 7+\", \"2nd-4th & 1-2\"]\nfig, axes = plt.subplots(1, 2, figsize=(6.5, 3.0), sharey=True)\nfor ax, (metric, label) in zip(axes, [(\"epa\", \"EPA per play\"), (\"sr\", \"Success rate\")]):\n    for k, kind in enumerate([\"Dropback\", \"Designed run\"]):\n        ax.scatter(tab.loc[order, (metric, kind)], range(len(order)), s=60,\n                   color=style.SERIES[k], edgecolor=style.SURFACE, zorder=3, label=kind)\n    for i, s in enumerate(order):\n        ax.plot(tab.loc[s, metric][[\"Dropback\", \"Designed run\"]], [i, i],\n                color=style.BASELINE, lw=1.5, zorder=2)\n    ax.set_xlabel(label)\n    if metric == \"epa\":\n        ax.axvline(0, color=style.BASELINE, lw=1)\n    else:\n        ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\naxes[0].set_yticks(range(len(order)),\n                   [f\"{s}  ({run_share[s]:.0%} run)\" for s in order])\naxes[0].invert_yaxis()\nh, lab = axes[0].get_legend_handles_labels()\nfig.legend(h, lab, loc=\"upper right\", ncol=2, fontsize=8, bbox_to_anchor=(0.99, 1.0))\nfig.suptitle(\"Same situation, run vs. dropback\", x=0.01, ha=\"left\",\n             fontweight=\"bold\", fontsize=11)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Average EPA and success rate for designed runs and dropbacks within the same situations, 2021-2025, neutral game states. The run percentage beside each situation is how often teams chose to run there. Dropbacks out-earn runs on early downs and third-and-long; in short yardage the gap disappears and runs succeed more often.](13-02-expected-points-and-success-rate_files/figure-html/fig-run-pass-situation-output-1.svg){#fig-run-pass-situation}\n:::\n:::\n\n\nHolding the situation fixed, the passing edge survives on early downs: on first-and-10 a dropback\nhas been worth roughly two-tenths of a point more than a run. On third-and-long it survives too,\nthough the give-up draws in that bucket exaggerate it. In **short yardage the gap closes**: runs and\ndropbacks earn about the same EPA, and runs succeed more often.\n\nPart of that short-yardage edge is one play. The run pile includes the\n[**quarterback sneak**](../../appendices/glossary.qmd#gl-qb-sneak) (and its pushed cousin, the\n[tush push](../../appendices/glossary.qmd#gl-tush-push)), which converts far more often than a\nhandoff. FTN's charting flags sneaks from 2022 on (`is_qb_sneak`), so the cell splits them out:\n\n::: {#cell-sneak-split .cell execution_count=18}\n``` {.python .cell-code}\nftn_sn = nfl().load_ftn_charting(list(range(2022, 2026))).to_pandas()\nsy = (neutral[neutral.season.between(2022, 2025) & (neutral.down >= 2) & (neutral.ydstogo <= 2)]\n      .merge(ftn_sn[[\"nflverse_game_id\", \"nflverse_play_id\", \"is_qb_sneak\"]], how=\"left\",\n             left_on=[\"game_id\", \"play_id\"], right_on=[\"nflverse_game_id\", \"nflverse_play_id\"]))\nsneak = sy.is_qb_sneak.fillna(False).astype(bool)\nsy[\"group\"] = np.where(sy.kind == \"Dropback\", \"Dropback\",\n                       np.where(sneak, \"QB sneak\", \"Other designed run\"))\nsneak_tab = sy.groupby(\"group\").agg(plays=(\"epa\", \"size\"), epa=(\"epa\", \"mean\"),\n                                    success=(\"success\", \"mean\"),\n                                    first_down=(\"first_down\", \"mean\"))\nmd_table(sneak_tab.reset_index())\n```\n\n::: {#sneak-split .cell-output .cell-output-display .cell-output-markdown execution_count=18}\n| group | plays | epa | success | first_down |\n| :--- | ---: | ---: | ---: | ---: |\n| Dropback | 2,787 | 0.04 | 0.57 | 0.58 |\n| Other designed run | 4,752 | 0.02 | 0.61 | 0.68 |\n| QB sneak | 742 | 0.37 | 0.78 | 0.82 |\n:::\n:::\n\n\nSneaks are only about one short-yardage run in seven, but they earn several times the EPA of other\nruns and convert most of the time. Take them out and the other runs earn about what dropbacks do,\nor a shade less, while still succeeding more often. That is the honest version of the argument.\nPassing is more valuable on average in most situations, and the league has moved that way for twenty\nyears, but the right mix depends on the situation, the personnel and what the defense is daring you\nto do.\n\n::: {.callout-caution title=\"Common misconception\"}\n\"You have to run the ball to make play-action work.\" Analysts testing this with play-by-play data,\nnotably Ben Baldwin, found that play-action's extra efficiency does not depend on how often or how\nwell a team has been running.[^pa] The coaching point behind that finding is that the fake has to\n*look like your real run game*: the same offensive-line footwork and the same backfield action.\nLinebackers are taught to read that action on every snap, and they react to it whatever the\nseason's yards per carry say. [Play-Action, Bootlegs, and Screens](../04-the-passing-game/04-05-play-action-boots-screens.qmd)\ncovers the mechanics.\n:::\n\n## Team offense versus team defense\n\nPut every team's offensive and defensive EPA per play on one chart and the season's shape appears.\n\n::: {#team-epa .cell execution_count=19}\n``` {.python .cell-code}\nteam = (neutral.groupby([\"season\", \"posteam\"])\n        .agg(off_epa=(\"epa\", \"mean\"), off_sr=(\"success\", \"mean\"), plays=(\"epa\", \"size\"))\n        .join(neutral.groupby([\"season\", \"defteam\"])\n              .agg(def_epa=(\"epa\", \"mean\"), def_sr=(\"success\", \"mean\"))\n              .rename_axis([\"season\", \"posteam\"]))\n        .reset_index().rename(columns={\"posteam\": \"team\"}))\nteam[\"net\"] = team.off_epa - team.def_epa\n```\n:::\n\n\n::: {#label-helper .cell execution_count=20}\n``` {.python .cell-code code-summary=\"A small label-placement helper (plotting plumbing)\"}\ndef label_points(ax, x, y, labels, fs=7.5):\n    \"\"\"Write each label right of its point, nudging it until it clears labels and markers.\"\"\"\n    ax.figure.canvas.draw()\n    T, k = ax.transData, ax.figure.dpi / 72\n    pts = T.transform(np.column_stack([x, y]))\n    w, h = np.array([len(s) for s in labels]) * fs * 0.62 * k, fs * 1.15 * k\n    placed = [(px - 4 * k, py, 8 * k) for px, py in pts]   # markers count as obstacles\n    for i in np.argsort(pts[:, 1]):                      # bottom to top\n        lx, ly = pts[i, 0] + 5 * k, pts[i, 1]\n        while any(abs(ly - py) < h and lx < px + pw and px < lx + w[i] for px, py, pw in placed):\n            ly += h / 4\n        placed.append((lx, ly, w[i]))\n        tx, ty = T.inverted().transform((lx, ly))\n        ax.text(tx, ty, labels[i], fontsize=fs, color=style.INK_2, va=\"center\", zorder=5)\n        if ly - pts[i, 1] > h * 0.8:                      # leader line if the label moved far\n            ax.plot([x[i], tx], [y[i], ty], color=style.BASELINE, lw=0.6, zorder=2)\n```\n:::\n\n\n::: {#cell-fig-team-scatter .cell execution_count=21}\n``` {.python .cell-code}\nt25 = team[team.season == 2025]\nfig, ax = plt.subplots(figsize=(6.5, 5.2))\nax.axvline(t25.off_epa.mean(), color=style.BASELINE, lw=1)\nax.axhline(t25.def_epa.mean(), color=style.BASELINE, lw=1)\nhi = t25.team.isin([\"SEA\", \"NE\"])\nax.scatter(t25.off_epa[~hi], t25.def_epa[~hi], s=34, color=style.SERIES[0],\n           edgecolor=style.SURFACE, linewidth=1, zorder=3)\nax.scatter(t25.off_epa[hi], t25.def_epa[hi], s=48, color=style.SERIES[1],\n           edgecolor=style.SURFACE, linewidth=1, zorder=4)\nax.invert_yaxis()\nax.set_xlabel(\"Offense: EPA per play gained →\")\nax.set_ylabel(\"Defense: EPA per play allowed (better ↑)\")\nax.set_title(\"2025: who was good at what\")\nfor txt, xy, ha in [(\"Good offense,\\ngood defense\", (0.98, 0.97), \"right\"),\n                    (\"Bad offense,\\nbad defense\", (0.02, 0.03), \"left\")]:\n    ax.text(*xy, txt, transform=ax.transAxes, ha=ha, va=\"top\" if xy[1] > .5 else \"bottom\",\n            fontsize=8, color=style.MUTED, style=\"italic\")\nlabel_points(ax, t25.off_epa.to_numpy(), t25.def_epa.to_numpy(),\n             [{\"LA\": \"LA (Rams)\"}.get(t, t) for t in t25.team])\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Offensive vs. defensive EPA per play, 2025 regular season, neutral game states. Right is better offense; up is better defense (the defensive axis is flipped so that allowing less EPA is higher). The grey lines are the league averages. Seattle's defense stands out at the top; New England, the other Super Bowl team (both in orange), is far right but sits on the average-defense line. LA is the Rams in nflverse's team codes (LAC is the Chargers).](13-02-expected-points-and-success-rate_files/figure-html/fig-team-scatter-output-1.svg){#fig-team-scatter}\n:::\n:::\n\n\nThe quadrants read like a season summary. Top-right teams were good at both. The Rams, Seahawks and\nPatriots finished first, second and third in **net EPA per play** (offensive EPA per play minus\ndefensive EPA per play allowed), but by different routes: the Rams were above average on both sides,\nSeattle got there mostly on defense, and New England almost entirely on offense, with a defense right\nat the league average. Bottom-left teams were bad at both.\nThe off-diagonal corners are the interesting ones: a team far right but low (good offense, bad\ndefense) plays shootouts; a team high but far left wins ugly. Here is the top and bottom of the same\nranking for 2024 and 2025. In the table, `off_epa` and `def_epa` are EPA per play gained and\nallowed, `net` is their difference, and `off_sr` and `def_sr` are the success rates gained and\nallowed (for defenses, lower is better).\n\n::: {#cell-team-rankings .cell execution_count=22}\n``` {.python .cell-code}\ndef top_bottom(season, n=5):\n    t = team[team.season == season].sort_values(\"net\", ascending=False)\n    t[\"rank\"] = t.net.rank(ascending=False).astype(int)     # rank among all 32 first\n    t = pd.concat([t.head(n), t.tail(n)])\n    return t[[\"season\", \"rank\", \"team\", \"off_epa\", \"def_epa\", \"net\", \"off_sr\", \"def_sr\"]]\n\nmd_table(pd.concat([top_bottom(2024), top_bottom(2025)]), digits=3)\n```\n\n::: {#team-rankings .cell-output .cell-output-display .cell-output-markdown execution_count=22}\n| season | rank | team | off_epa | def_epa | net | off_sr | def_sr |\n| ---: | ---: | :--- | ---: | ---: | ---: | ---: | ---: |\n| 2024 | 1 | BAL | 0.200 | -0.046 | 0.246 | 0.493 | 0.412 |\n| 2024 | 2 | MIN | 0.092 | -0.144 | 0.236 | 0.478 | 0.405 |\n| 2024 | 3 | BUF | 0.192 | -0.027 | 0.219 | 0.496 | 0.442 |\n| 2024 | 4 | PHI | 0.082 | -0.113 | 0.196 | 0.446 | 0.387 |\n| 2024 | 5 | DET | 0.166 | -0.013 | 0.179 | 0.513 | 0.423 |\n| 2024 | 28 | NYG | -0.128 | 0.063 | -0.192 | 0.401 | 0.452 |\n| 2024 | 29 | LV | -0.152 | 0.042 | -0.195 | 0.388 | 0.440 |\n| 2024 | 30 | NE | -0.087 | 0.109 | -0.196 | 0.425 | 0.490 |\n| 2024 | 31 | CAR | -0.023 | 0.178 | -0.201 | 0.414 | 0.521 |\n| 2024 | 32 | CLE | -0.172 | 0.063 | -0.235 | 0.360 | 0.434 |\n| 2025 | 1 | LA | 0.145 | -0.056 | 0.201 | 0.521 | 0.411 |\n| 2025 | 2 | SEA | 0.045 | -0.149 | 0.194 | 0.471 | 0.397 |\n| 2025 | 3 | NE | 0.185 | 0.009 | 0.176 | 0.501 | 0.471 |\n| 2025 | 4 | PHI | 0.027 | -0.139 | 0.166 | 0.435 | 0.410 |\n| 2025 | 5 | DEN | 0.044 | -0.106 | 0.150 | 0.439 | 0.370 |\n| 2025 | 28 | WAS | 0.013 | 0.169 | -0.155 | 0.445 | 0.495 |\n| 2025 | 29 | CIN | -0.038 | 0.149 | -0.187 | 0.451 | 0.492 |\n| 2025 | 30 | LV | -0.274 | -0.017 | -0.257 | 0.362 | 0.438 |\n| 2025 | 31 | NYJ | -0.157 | 0.158 | -0.315 | 0.400 | 0.458 |\n| 2025 | 32 | TEN | -0.195 | 0.123 | -0.318 | 0.364 | 0.465 |\n:::\n:::\n\n\n::: {.callout-note title=\"Film room: Seattle Seahawks 2025\"}\nSeattle's 2025 defense (head coach Mike Macdonald, defensive coordinator Aden Durde) allowed the\nfewest EPA per play in the league in neutral situations, and the Super Bowl is a good game to run\nthrough the ledger.[^lx] First, the offensive scrimmage plays for each team:\n\n::: {#cell-lx-ledger .cell execution_count=23}\n``` {.python .cell-code}\nlx_s = lx[lx.play_type.isin([\"pass\", \"run\"]) & lx.epa.notna()]\nmd_table(lx_s.groupby(\"posteam\").agg(plays=(\"epa\", \"size\"), total_epa=(\"epa\", \"sum\"),\n                                     epa_play=(\"epa\", \"mean\"), success=(\"success\", \"mean\"))\n         .reset_index())\n```\n\n::: {#lx-ledger .cell-output .cell-output-display .cell-output-markdown execution_count=23}\n| posteam | plays | total_epa | epa_play | success |\n| :--- | ---: | ---: | ---: | ---: |\n| NE | 67 | -20.73 | -0.31 | 0.40 |\n| SEA | 71 | -3.52 | -0.05 | 0.34 |\n:::\n:::\n\n\nThat looks wrong at first: the team that won 29-13 has *negative* offensive EPA and a lower success\nrate. The ledger explains itself once you remember what it counts. Seattle's points came from five\nJason Myers field goals (a Super Bowl record), one offensive touchdown and Nwosu's interception\nreturn. The field-goal plays and Michael Dickson's punts are special-teams plays, outside this\ntable, and the pick-six is booked as *New England's* offensive EPA (−9.81), not Seattle's. Seattle's\noffense did the modest job of reaching field-goal range; its defense and kicking won the game. A\nteam's offensive EPA measures its offense, not its scoreboard.\n:::\n\n::: {.callout-note title=\"Film room: Seattle Seahawks 2025, the five biggest plays\"}\nSort the same game's scrimmage plays by the size of their EPA, and keep the offense's win\nprobability (`wp`) beside each one:\n\n::: {#cell-lx-biggest .cell execution_count=24}\n``` {.python .cell-code}\nbig = lx_s.reindex(lx_s.epa.abs().sort_values(ascending=False).index).head(5)\nmd_table(big[[\"qtr\", \"posteam\", \"down\", \"ydstogo\", \"yardline_100\", \"yards_gained\", \"epa\", \"wp\"]])\n```\n\n::: {#lx-biggest .cell-output .cell-output-display .cell-output-markdown execution_count=24}\n| qtr | posteam | down | ydstogo | yardline_100 | yards_gained | epa | wp |\n| ---: | :--- | ---: | ---: | ---: | ---: | ---: | ---: |\n| 4 | NE | 1 | 10 | 44 | 0 | -9.81 | 0.03 |\n| 4 | NE | 2 | 3 | 56 | 0 | -5.44 | 0.07 |\n| 3 | NE | 3 | 6 | 56 | -7 | -4.37 | 0.12 |\n| 4 | NE | 1 | 10 | 35 | 35 | 3.38 | 0.03 |\n| 2 | SEA | 2 | 10 | 76 | 30 | 2.62 | 0.53 |\n:::\n:::\n\n\n**What to notice.** Three of the five are New England turnovers: the Nwosu return, a Julian Love\ninterception, and a Derick Hall strip-sack that Byron Murphy recovered. The fourth is New England's\n35-yard touchdown pass to Mack Hollins early in the fourth quarter, a big EPA gain that barely moved\nthe `wp` column (New England's win probability, about 3%). The fifth is Kenneth Walker III's 30-yard\nrun on second-and-10 early in the second quarter. Two snaps later, after an incompletion, he ran for\n29 more on the next second-and-10; those were Seattle's two biggest gains of the night, and both\nturned an ordinary down into a drive into scoring range.\n\nWhen you rewatch a game, sort its plays by absolute EPA like this: the top five usually *are* the\nstory of the game, and the win-probability column tells you which of them mattered for the result.\n:::\n\n::: {.callout-note title=\"Film room: Seattle Seahawks 2025, how the defense did it\"}\nHow did Seattle's defense produce those plays? The charting data shows a plan built on two deep\nsafeties and four rushers:\n\n::: {#lx-coverage .cell execution_count=25}\n``` {.python .cell-code}\nTWO_HIGH = [\"COVER_2\", \"2_MAN\", \"COVER_4\", \"COVER_6\"]\npart = nfl().load_participation([2025]).to_pandas()\nkeys = dict(left_on=[\"game_id\", \"play_id\"], right_on=[\"nflverse_game_id\", \"play_id\"])\ncov = reg[(reg.season == 2025) & (reg[\"pass\"] == 1)].merge(part, **keys)\ncov = cov[cov.defense_coverage_type.notna()\n          & ~cov.defense_coverage_type.isin([\"BLOWN\", \"COMBO\", \"PREVENT\"])]\nteam_2h = cov.groupby(\"defteam\").defense_coverage_type.apply(lambda c: c.isin(TWO_HIGH).mean())\nsb = lx[(lx[\"pass\"] == 1) & (lx.defteam == \"SEA\")].merge(part, **keys)\nsb_cov = sb.defense_coverage_type.dropna()\nsb_cov = sb_cov[sb_cov != \"COMBO\"]\nprint(f\"2025 season: two-high on {team_2h['SEA']:.0%} of Seattle's labelled dropbacks \"\n      f\"(league {cov.defense_coverage_type.isin(TWO_HIGH).mean():.0%}; \"\n      f\"rank {int(team_2h.rank(ascending=False)['SEA'])} of 32)\")\nprint(f\"Super Bowl: two-high on {sb_cov.isin(TWO_HIGH).mean():.0%} of New England's dropbacks; \"\n      f\"four or fewer rushers on {(sb.number_of_pass_rushers <= 4).sum()} \"\n      f\"of {sb.number_of_pass_rushers.notna().sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2025 season: two-high on 52% of Seattle's labelled dropbacks (league 43%; rank 3 of 32)\nSuper Bowl: two-high on 73% of New England's dropbacks; four or fewer rushers on 48 of 57\n```\n:::\n:::\n\n\nTwo deep safeties take away the explosive throw; a four-man rush that still gets home (six sacks in\nthe game) means the quarterback has to hold the ball against seven defenders in coverage. That is\nthe split-safety trend NFL Next Gen Stats tied to Seattle's title run.[^sea-cov] Sacks then cost New\nEngland one to two points of EPA each, and every extra second Maye held the ball was another chance\nfor a turnover.\n:::\n\n::: {.callout-note title=\"Film room: Baltimore Ravens 2024\"}\nIn 2024 Baltimore had the league's most efficient offense by EPA per play in neutral situations\n(narrowly ahead of Buffalo), and\nit is a useful counterexample to \"running is always worse.\" The Ravens were one of only about a quarter of\nteams whose designed runs averaged *positive* EPA in neutral situations, with Derrick Henry carrying\nthe ball and Lamar Jackson's designed runs and keeps forcing defenses to account\nfor the quarterback.[^ravens]\n**What to notice:** compare Baltimore's designed-run EPA per play in the printout below with the\nleague's; then ask why.\nPart of the answer is talent, and part is selection: defenses that must respect a quarterback run\ncannot load the box against the back.\n\n::: {#ravens-2024 .cell execution_count=26}\n``` {.python .cell-code}\nr24 = neutral[neutral.season == 2024]\nrush = r24[r24.kind == \"Designed run\"].groupby(\"posteam\").epa.mean()\nleague_run = r24.loc[r24.kind == \"Designed run\", \"epa\"].mean()\nprint(f\"BAL designed-run EPA/play 2024: {rush['BAL']:+.3f} \"\n      f\"(rank {int(rush.rank(ascending=False)['BAL'])} of 32; league {league_run:+.3f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBAL designed-run EPA/play 2024: +0.049 (rank 4 of 32; league -0.060)\n```\n:::\n:::\n\n\n:::\n\n## Player metrics: CPOE and RYOE\n\nTeam EPA mixes everyone's work together. To evaluate one player you want to strip out the parts he\ndid not control. Two expected-value metrics do that for the most visible players.\n\n**[CPOE](../../appendices/glossary.qmd#gl-cpoe)** (completion percentage over expected), taught in\n[Quarterback Play](../04-the-passing-game/04-07-quarterback-play.qmd), compares a quarterback's\ncompletion rate with what a model expects given each throw's depth, location and situation. A 9-yard\nout to a covered receiver is harder than a 2-yard checkdown, and CPOE gives credit for the hard\nones. In nflverse it comes with every pass as the `cpoe` column, in percentage points: +3 means three\nmore completions per hundred throws than the model expected. CPOE does not fully separate the\nquarterback from his receivers. A dropped ball counts as an incompletion against him, and receivers\nwho get open make throws look easier, so the \"expected\" rate already contains some of their work.\n\n**[RYOE](../../appendices/glossary.qmd#gl-ryoe)** (rush yards over expected) does the same job for a\nrunning back, and it needs [tracking data](../../appendices/glossary.qmd#gl-tracking-data): the location,\nspeed and direction of all 22 players at the handoff.\n[**Next Gen Stats**](../../appendices/glossary.qmd#gl-next-gen-stats) (NGS), the league's own\ntracking-data and analytics group, predicts how many yards an average back would gain from that exact\npicture (how much space, how many defenders in front, how fast they are closing) and subtracts it from\nwhat the back actually gained. The model grew out of the 2020\n[**Big Data Bowl**](../../appendices/glossary.qmd#gl-big-data-bowl), the NFL's annual public\nanalytics competition on tracking data ([Tracking Data and the Big Data\nBowl](13-05-tracking-data-and-big-data-bowl.qmd) covers it). The winning entry that year, by\nAustrian data scientists Philipp Singer and Dmitry Gordeev, predicted rushing yards from tracking\nframes.[^ryoe] The idea is the cleanest in football analytics: *expected* rushing yards belong mostly\nto the blockers and the play call, *over expected* mostly to the runner.\n\n::: {#cell-ryoe-2025 .cell execution_count=27}\n``` {.python .cell-code}\nngs = nfl().load_nextgen_stats(seasons=list(SEASONS), stat_type=\"rushing\").to_pandas()\nrb = ngs[(ngs.week == 0) & (ngs.season_type == \"REG\") & (ngs.rush_attempts >= 100)].copy()\nrb[\"exp_ypc\"] = rb.expected_rush_yards / rb.rush_attempts\nshow = (rb[rb.season == 2025]\n        .sort_values(\"rush_yards_over_expected_per_att\", ascending=False)\n        .rename(columns={\"player_display_name\": \"player\", \"team_abbr\": \"team\",\n                         \"rush_attempts\": \"att\", \"avg_rush_yards\": \"ypc\",\n                         \"rush_yards_over_expected_per_att\": \"ryoe_att\"}))\ncols = [\"player\", \"team\", \"att\", \"ypc\", \"exp_ypc\", \"ryoe_att\"]\nmd_table(pd.concat([show[cols].head(6), show[cols].tail(4)]))\n```\n\n::: {#ryoe-2025 .cell-output .cell-output-display .cell-output-markdown execution_count=27}\n| player | team | att | ypc | exp_ypc | ryoe_att |\n| :--- | :--- | ---: | ---: | ---: | ---: |\n| Rhamondre Stevenson | NE | 130 | 4.64 | 3.30 | 1.33 |\n| James Cook | BUF | 309 | 5.25 | 4.11 | 1.13 |\n| Derrick Henry | BAL | 307 | 5.20 | 3.99 | 1.05 |\n| J.K. Dobbins | DEN | 153 | 5.05 | 3.83 | 1.04 |\n| Devon Achane | MIA | 238 | 5.67 | 4.54 | 1.04 |\n| Jordan Mason | MIN | 159 | 4.77 | 3.68 | 0.94 |\n| Christian McCaffrey | SF | 311 | 3.86 | 4.35 | -0.54 |\n| R.J. Harvey | DEN | 146 | 3.70 | 4.18 | -0.63 |\n| Alvin Kamara | NO | 131 | 3.60 | 4.35 | -0.77 |\n| Bucky Irving | TB | 173 | 3.40 | 4.17 | -0.84 |\n:::\n:::\n\n\nRead across a row: yards per carry (`ypc`) is what the broadcast shows; expected yards per carry\n(`exp_ypc`) is the space the line and the play call provided; RYOE per attempt (`ryoe_att`) is the\ndifference. A back with a modest yards per carry behind a poor line can grade well, and a back with a\nfine yards per carry behind a great line can grade poorly. Christian McCaffrey sits near the bottom in\n2025: his blocking promised about 4.4 yards a carry and he averaged under 3.9. That is a real\nfinding about his running that season, and it says nothing about his catches, his pass protection or\nhis ball security, none of which RYOE counts.\n\nThe split is cleaner in idea than in practice. \"Expected\" is fixed at the moment of the handoff, so\neverything the blocking does *afterwards* is booked as the runner's: a guard climbing to the second\nlevel, a receiver's crack or stalk block downfield, a cutback lane on an outside-zone run that opens\nfour yards later. So is the back's vision in pressing a hole to set up a block, which coaches would\ncall his skill. Add the noise of a few hundred carries, and RYOE turns out to repeat only weakly from\nseason to season (the stability chart below). Treat one season of RYOE as a hint about a runner and\nseveral seasons as evidence. The table includes 100-carry backs only; below that it is mostly noise.\n\n### What a good number looks like\n\nEvery metric in this chapter needs a scale before it means anything. Here is the spread across team\nand player seasons from 2016-2025, using the same filters as the rest of the chapter:\n\n::: {#cell-scale-card .cell execution_count=28}\n``` {.python .cell-code}\nqb_seasons = (plays[plays.kind == \"Dropback\"].groupby([\"season\", \"passer_id\"])\n              .agg(epa=(\"epa\", \"mean\"), cpoe=(\"cpoe\", \"mean\"), att=(\"pass_attempt\", \"sum\")))\nqb_seasons = qb_seasons[qb_seasons.att >= 250]\nscales = {\"Team offense EPA/play (neutral)\": team.off_epa,\n          \"Team offense success rate (neutral)\": team.off_sr * 100,\n          \"QB EPA per dropback (250+ att)\": qb_seasons.epa,\n          \"QB CPOE, points (250+ att)\": qb_seasons.cpoe,\n          \"RB RYOE per carry (100+ carries)\": rb.rush_yards_over_expected_per_att}\ncard = pd.DataFrame({k: v.quantile([0.1, 0.5, 0.9]).to_numpy() for k, v in scales.items()},\n                    index=[\"poor (10th pct)\", \"average (median)\", \"very good (90th pct)\"]).T\nmaye = qb_seasons.cpoe.rank(ascending=False).loc[(2025, \"00-0039851\")]   # Drake Maye\nnext_best = qb_seasons.cpoe.nlargest(2).iloc[1]\nmd_table(card.reset_index(names=\"metric\"))\n```\n\n::: {#scale-card .cell-output .cell-output-display .cell-output-markdown execution_count=28}\n| metric | poor (10th pct) | average (median) | very good (90th pct) |\n| :--- | ---: | ---: | ---: |\n| Team offense EPA/play (neutral) | -0.11 | 0.00 | 0.13 |\n| Team offense success rate (neutral) | 38.83 | 43.69 | 48.71 |\n| QB EPA per dropback (250+ att) | -0.10 | 0.06 | 0.20 |\n| QB CPOE, points (250+ att) | -3.34 | 0.91 | 4.66 |\n| RB RYOE per carry (100+ carries) | -0.51 | 0.12 | 0.88 |\n:::\n:::\n\n\nSuccess rate is shown in percent. Read the table as \"a team at \\+0\\.13 EPA per play is a\ntop-tenth offense; one at \\-0\\.11 is a bottom-tenth one.\" On that scale Drake Maye's 2025 CPOE of +10.8 ranks\nnumber 1 among the decade's 328 qualifying\nquarterback seasons, and the next-best was \\+7\\.7.\n\n## Signal and noise\n\nEverything so far computed averages. The hard part of football analytics is knowing when an average\nmeans something. Football is the noisiest of the major sports to measure: few games, few plays per\ngame, and outcomes that depend on 22 people at once.\n\n### Sample size\n\nA single play's EPA has a standard deviation of about 1.4 points, while the true difference between\nan average offense and a very good one is about a tenth of a point per play. You are trying to\nmeasure a 0.1 signal with a 1.4 ruler. Averaging helps, but slowly: the uncertainty shrinks with the\nsquare root of the number of plays.\n\n::: {#noise .cell execution_count=29}\n``` {.python .cell-code}\nseason_team = neutral.groupby([\"season\", \"posteam\"]).epa.agg([\"mean\", \"size\"])\nsd_play = neutral.epa.std()\nn_season = season_team[\"size\"].mean()\nnoise_var = sd_play**2 / n_season                   # sampling noise in a season average\ntrue_sd = np.sqrt(season_team[\"mean\"].var() - noise_var)  # spread of real team quality\nn_even = sd_play**2 / true_sd**2                    # plays until noise = signal\nn_game = neutral.groupby([\"game_id\", \"posteam\"]).size().mean()\nprint(f\"per-play SD {sd_play:.2f}; neutral plays per game {n_game:.0f}, per season {n_season:.0f}\")\nprint(f\"true spread of team offenses: SD {true_sd:.3f} EPA/play\")\nprint(f\"plays before signal = noise: {n_even:.0f} (about {n_even / n_game:.0f} games)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nper-play SD 1.39; neutral plays per game 43, per season 703\ntrue spread of team offenses: SD 0.081 EPA/play\nplays before signal = noise: 293 (about 7 games)\n```\n:::\n:::\n\n\n::: {#cell-fig-sample-size .cell execution_count=30}\n``` {.python .cell-code}\nn = np.arange(20, 1001)\nfig, ax = plt.subplots(figsize=(6.5, 3.4))\nax.plot(n, sd_play / np.sqrt(n), color=style.SERIES[0], lw=2, label=\"Chance wobble (1 SE)\")\nax.axhspan(0, true_sd, color=style.SERIES[1], alpha=0.15, lw=0)\nax.axhline(true_sd, color=style.SERIES[1], lw=2, label=\"Real spread of offenses (1 SD)\")\nfor x, lab in [(n_game, \"1 game\"), (n_game * 4, \"4 games\"), (n_season, \"a season\")]:\n    ax.axvline(x, color=style.BASELINE, lw=1, ls=(0, (3, 2)))\n    ax.text(x + 8, 0.29, lab, fontsize=8, color=style.INK_2, va=\"top\")\nax.set_xlim(0, 1000)\nax.set_ylim(0, 0.3)\nax.set_xlabel(\"Neutral-situation offensive plays\")\nax.set_ylabel(\"EPA per play\")\nax.set_title(\"A game is a small sample\")\nax.legend(loc=\"upper center\", bbox_to_anchor=(0.5, -0.2), ncol=2, fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![How much a team's EPA per play can wander by chance (one standard error, blue) as plays accumulate, against how much real offenses differ (orange band, one standard deviation of team quality). One game's average is mostly noise; only after several games does signal match noise.](13-02-expected-points-and-success-rate_files/figure-html/fig-sample-size-output-1.svg){#fig-sample-size}\n:::\n:::\n\n\nAfter one game, a team's EPA per play can be off by more than twice the whole spread between average\nand elite offenses. After about 293 neutral plays, roughly\n7 games, chance and real quality contribute equally; even a full\nseason's number is still noticeably blurred. The practical rules: treat one game as a story, a month\nas a hint, and a season as evidence; and prefer metrics that use more plays (all dropbacks rather\nthan only third downs).\n\n### Year-over-year stability\n\nThe second test of a metric is whether it repeats. **[Year-over-year stability](../../appendices/glossary.qmd#gl-year-over-year-stability)**\nis the correlation between a team's (or player's) number one season and the same number the next.\nHigh stability does not prove a metric measures skill (a team's schedule or coaching staff can\ncarry over too), but low stability is a strong sign that the metric is mostly luck, or that it\nmeasures something that changes every year.\n\n::: {#stability .cell execution_count=31}\n``` {.python .cell-code}\ndef yoy(df, key, col):\n    \"\"\"Correlation of a metric with itself one season later, same team or player.\"\"\"\n    nxt = df.assign(season=df.season - 1)\n    m = df.merge(nxt, on=[\"season\", key], suffixes=(\"\", \"_next\"))\n    return m[col].corr(m[col + \"_next\"]), len(m)\n\n# Teams (neutral situations)\np_all = plays.assign(explosive=np.where(plays.kind == \"Designed run\",\n                                        plays.yards_gained >= 10, plays.yards_gained >= 20))\ntm = team.copy()\ntm[\"explosive\"] = (p_all.groupby([\"season\", \"posteam\"]).explosive.mean()\n                   .reindex(pd.MultiIndex.from_frame(tm[[\"season\", \"team\"]])).to_numpy())\n# Fumble-recovery rate: share of ALL fumbles in a team's games that it recovered\nfum = reg[(reg.fumble == 1) & reg.fumble_recovery_1_team.notna()]\nfr = pd.concat([fum.assign(team=fum[side]) for side in (\"posteam\", \"defteam\")])\nfr = (fr.assign(rec=fr.fumble_recovery_1_team == fr.team)\n      .groupby([\"season\", \"team\"]).agg(rate=(\"rec\", \"mean\"), n=(\"rec\", \"size\")).reset_index())\n# Quarterbacks (250+ attempts) and running backs (100+ carries)\ndb = plays[plays.kind == \"Dropback\"]\nqb = (db.groupby([\"season\", \"passer_id\"])\n      .agg(epa=(\"epa\", \"mean\"), cpoe=(\"cpoe\", \"mean\"), att=(\"pass_attempt\", \"sum\"),\n           ints=(\"interception\", \"sum\")).reset_index())\nqb = qb[qb.att >= 250].assign(int_rate=lambda t: t.ints / t.att)\n\nrows = [(\"Team\", \"Offense EPA/play\", *yoy(tm, \"team\", \"off_epa\")),\n        (\"Team\", \"Offense success rate\", *yoy(tm, \"team\", \"off_sr\")),\n        (\"Team\", \"Defense EPA/play\", *yoy(tm, \"team\", \"def_epa\")),\n        (\"Team\", \"Defense success rate\", *yoy(tm, \"team\", \"def_sr\")),\n        (\"Team\", \"Explosive play rate\", *yoy(tm, \"team\", \"explosive\")),\n        (\"Team\", \"Fumble-recovery rate\", *yoy(fr, \"team\", \"rate\")),\n        (\"QB\", \"EPA per dropback\", *yoy(qb, \"passer_id\", \"epa\")),\n        (\"QB\", \"CPOE\", *yoy(qb, \"passer_id\", \"cpoe\")),\n        (\"QB\", \"Interception rate\", *yoy(qb, \"passer_id\", \"int_rate\")),\n        (\"RB\", \"Expected yards per carry\", *yoy(rb, \"player_gsis_id\", \"exp_ypc\")),\n        (\"RB\", \"Yards per carry\", *yoy(rb, \"player_gsis_id\", \"avg_rush_yards\")),\n        (\"RB\", \"RYOE per carry\", *yoy(rb, \"player_gsis_id\", \"rush_yards_over_expected_per_att\"))]\nstab = pd.DataFrame(rows, columns=[\"who\", \"metric\", \"r\", \"pairs\"])\n```\n:::\n\n\n::: {#cell-fig-stability .cell execution_count=32}\n``` {.python .cell-code}\ns = stab.iloc[::-1].reset_index(drop=True)\ncolors = {\"Team\": style.SERIES[0], \"QB\": style.SERIES[2], \"RB\": style.SERIES[1]}\nfig, ax = plt.subplots(figsize=(6.5, 4.4))\nax.barh(s.index, s.r, color=[colors[w] for w in s.who], height=0.62,\n        edgecolor=style.SURFACE, linewidth=2)\nfor i, r in s.iterrows():\n    ax.text(max(r.r, 0) + 0.01, i, f\"{r.r:.2f}\", va=\"center\", fontsize=8, color=style.INK_2)\nax.set_yticks(s.index, [f\"{w}: {m}\" for w, m in zip(s.who, s.metric)], fontsize=8.5)\nax.axvline(0, color=style.BASELINE, lw=1)\nax.set_xlim(-0.05, 0.6)\nax.set_xlabel(\"Correlation with the same metric the next season\")\nax.set_title(\"What repeats from one season to the next\")\nax.grid(axis=\"y\", visible=False)\nfrom matplotlib.patches import Patch\nax.legend(handles=[Patch(color=c, label=k) for k, c in colors.items()],\n          loc=\"lower right\", fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Year-over-year correlation of each metric with itself, 2016-2025 (team metrics in neutral situations; quarterbacks with 250+ attempts and running backs with 100+ carries in both seasons). Offense repeats better than defense; success rate repeats about as well as EPA (a hair better on offense); fumble recovery does not repeat at all. For running backs, the blocking-driven part (expected yards) repeats better than the runner's own part (RYOE).](13-02-expected-points-and-success-rate_files/figure-html/fig-stability-output-1.svg){#fig-stability}\n:::\n:::\n\n\nFour lessons from one chart:\n\n- **Offense is more stable than defense.** An offense's results lean heavily on one player, the\n  quarterback, who usually returns and whose level is among the most stable things in football.\n  A defense's results depend more on turnovers and on which quarterbacks it happened to face. Expect\n  defensive rankings to churn.\n- **Success rate repeats about as well as EPA per play, no better to speak of.** Ignoring the size of\n  each play makes it less sensitive to a few explosive plays and turnovers, but the gain in\n  steadiness is tiny, and the earlier table showed what it costs: success rate was the weakest guide\n  to later scoring. Use EPA per play as the main number and success rate as a check on how a team got\n  there. Explosive play rate repeats less well than either.\n- **Interception rate is far less stable than overall quarterback efficiency.** Interceptions are\n  rare, and whether a defender catches a catchable ball is partly chance (more on that below).\n- **For running backs, what the back is given repeats better than what he adds.** Expected yards per\n  carry (the blocking and the play call) repeats best; RYOE repeats worst of the three, for the reasons\n  given in the RYOE section. A runner's yards per carry is mostly his offensive line and scheme, which\n  is one reason the NFL pays running backs\n  less than it once did ([Building a Roster](../14-the-business-of-scheme/14-01-building-a-roster.qmd)\n  picks this up).\n\n### Opponent adjustment\n\nA team that plays the four best defenses in October will look worse than it is. **[Opponent\nadjustment](../../appendices/glossary.qmd#gl-opponent-adjustment)** corrects for that. The simplest\nversion is a back-and-forth: estimate every defense's quality, subtract each opponent's quality from\neach play an offense ran, recompute the offenses, use them to re-estimate the defenses, and repeat\nuntil the numbers settle.\n\n::: {#cell-opp-adjust .cell execution_count=33}\n``` {.python .cell-code}\ns25 = neutral[neutral.season == 2025]\nlg = s25.epa.mean()\noff_q = s25.groupby(\"posteam\").epa.mean() - lg       # start from raw ratings\ndef_q = s25.groupby(\"defteam\").epa.mean() - lg\nfor _ in range(25):\n    new_off = (s25.epa - s25.defteam.map(def_q)).groupby(s25.posteam).mean() - lg\n    new_def = (s25.epa - s25.posteam.map(off_q)).groupby(s25.defteam).mean() - lg\n    off_q, def_q = new_off, new_def\nadj = pd.DataFrame({\"raw_off\": s25.groupby(\"posteam\").epa.mean() - lg, \"adj_off\": off_q,\n                    \"raw_def\": s25.groupby(\"defteam\").epa.mean() - lg, \"adj_def\": def_q})\nadj[\"change_off\"] = adj.adj_off - adj.raw_off\nmoves = adj.reindex(adj.change_off.abs().sort_values(ascending=False).index).head(6)\ntop = moves.index[0]\nmd_table(moves.reset_index(names=\"team\"), digits=3)\n```\n\n::: {#opp-adjust .cell-output .cell-output-display .cell-output-markdown execution_count=33}\n| team | raw_off | adj_off | raw_def | adj_def | change_off |\n| :--- | ---: | ---: | ---: | ---: | ---: |\n| TEN | -0.201 | -0.140 | 0.117 | 0.123 | 0.061 |\n| CLE | -0.224 | -0.276 | -0.094 | -0.080 | -0.052 |\n| IND | 0.075 | 0.126 | -0.004 | -0.006 | 0.051 |\n| MIA | 0.017 | -0.034 | 0.044 | 0.052 | -0.050 |\n| SF | 0.072 | 0.113 | 0.102 | 0.089 | 0.041 |\n| NE | 0.178 | 0.138 | 0.002 | 0.050 | -0.040 |\n:::\n:::\n\n\nEvery column is EPA per play relative to the 2025 league average. `raw_off` is the offense as\nmeasured; `adj_off` is the offense after subtracting the quality of the defenses it faced; `raw_def`\nand `adj_def` are the same for its defense (negative is good); `change_off` is adjusted minus raw.\nA positive `change_off` means the offense faced tougher-than-average defenses, so it was better than\nits raw number; a negative one means it had an easy schedule. The biggest mover in 2025,\nTEN, went from \\-0\\.201 raw to\n\\-0\\.140 adjusted: its offense\nwas better than it looked.\n\nIn a 17-game season the adjustment is real but modest: the biggest moves are around five\nhundredths of a point per play, about half the spread between an average and a good offense, and the\noverall order barely changes. It matters most early in a season, for teams with lopsided schedules,\nand for defenses (which face a narrower set of quarterbacks). DVOA, QBR and most betting models\ninclude an adjustment like this one; raw nflverse EPA does not.\n\n### Turnover luck\n\nTurnovers are the biggest plays in EPA, and a large part of them is chance. The clearest case is\nfumbles. Forcing fumbles is a skill and so is holding on to the ball, but **who recovers a loose ball\nbouncing on the turf** is close to a coin flip. That is **[turnover luck](../../appendices/glossary.qmd#gl-turnover-luck-fumble-recovery-rate)**.\n\n::: {#cell-fig-fumble-luck .cell execution_count=34}\n``` {.python .cell-code}\nnxt = fr.assign(season=fr.season - 1)\npair = fr.merge(nxt, on=[\"season\", \"team\"], suffixes=(\"\", \"_next\"))\nr_fr = pair.rate.corr(pair.rate_next)\nfig, ax = plt.subplots(figsize=(5.2, 4.6))\nax.scatter(pair.rate, pair.rate_next, s=18, color=style.SERIES[0], alpha=0.7,\n           edgecolor=style.SURFACE, linewidth=0.6)\nax.axhline(0.5, color=style.BASELINE, lw=1)\nax.axvline(0.5, color=style.BASELINE, lw=1)\nfit = np.polyfit(pair.rate, pair.rate_next, 1)\nxs = np.array([0.2, 0.8])\nax.plot(xs, np.polyval(fit, xs), color=style.SERIES[1], lw=2,\n        label=f\"Best-fit line (r = {r_fr:.2f})\")\nfor a in (ax.xaxis, ax.yaxis):\n    a.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\nax.set_xlim(0.2, 0.8)\nax.set_ylim(0.2, 0.8)\nax.set_xlabel(\"Fumble-recovery rate, season N\")\nax.set_ylabel(\"Fumble-recovery rate, season N+1\")\nax.set_title(\"Falling on the ball is a coin flip\")\nax.legend(loc=\"upper left\", fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Each dot is a team: its share of all fumbles in its games that it recovered, one season (x) against the next (y), 2016-2025. The cloud has no slope. A team that recovered 70% of fumbles last year should expect about 50% this year.](13-02-expected-points-and-success-rate_files/figure-html/fig-fumble-luck-output-1.svg){#fig-fumble-luck}\n:::\n:::\n\n\nWith a correlation of 0\\.07, last year's recovery rate tells you essentially\nnothing about this year's. A team's **turnover margin** (takeaways minus giveaways) is a big driver of\nits record, and the part of it that comes from loose balls bouncing its way will not repeat. That is\nwhy analysts flag \"turnover-luck\" teams as candidates to *regress to the mean*: to drift back toward\naverage next season.\n\nInterceptions have a luck component too, though a smaller one. A defender who gets his hands on a\nball sometimes drops it; a perfectly thrown ball is sometimes tipped into a linebacker's arms. FTN's\ncharting marks every throw it judges **interception-worthy**, so for 2022 onward you can compare a\nquarterback's interceptions with his interception-worthy throws.\n\n::: {#cell-int-worthy .cell execution_count=35}\n``` {.python .cell-code}\nftn = nfl().load_ftn_charting([2025]).to_pandas()\nx = (plays[(plays.season == 2025) & (plays.kind == \"Dropback\")]\n     .merge(ftn[[\"nflverse_game_id\", \"nflverse_play_id\", \"is_interception_worthy\"]],\n            left_on=[\"game_id\", \"play_id\"], right_on=[\"nflverse_game_id\", \"nflverse_play_id\"]))\niw = (x.groupby(\"passer\").agg(dropbacks=(\"epa\", \"size\"), interceptions=(\"interception\", \"sum\"),\n                              int_worthy=(\"is_interception_worthy\", \"sum\"))\n      .query(\"dropbacks >= 400\").astype(int))\niw[\"gap\"] = iw.interceptions - iw.int_worthy\nrisky_rank = (iw.int_worthy / iw.dropbacks).rank(ascending=False)     # 1 = riskiest thrower\nmd_table(pd.concat([iw.sort_values(\"gap\").head(4), iw.sort_values(\"gap\").tail(3)])\n         .reset_index())\n```\n\n::: {#int-worthy .cell-output .cell-output-display .cell-output-markdown execution_count=35}\n| passer | dropbacks | interceptions | int_worthy | gap |\n| :--- | ---: | ---: | ---: | ---: |\n| C.Williams | 633 | 7 | 18 | -11 |\n| B.Nix | 669 | 11 | 21 | -10 |\n| C.Ward | 615 | 7 | 15 | -8 |\n| J.Allen | 547 | 10 | 18 | -8 |\n| J.Goff | 619 | 8 | 9 | -1 |\n| B.Young | 536 | 11 | 11 | 0 |\n| G.Smith | 519 | 17 | 14 | 3 |\n:::\n:::\n\n\nNearly every quarterback threw more interception-worthy balls than he had interceptions; defenders\ndrop a lot of them. But the gap varies widely. A quarterback whose interceptions ran well below his\ninterception-worthy throws in 2025 (Caleb Williams, by FTN's charting) benefited from dropped\npicks and is a good bet to throw more interceptions next year *on the same decisions*. One at the\nbottom of the table, with more interceptions than interception-worthy throws (Geno Smith, with the\nRaiders in 2025), is the opposite case: his rate of interception-worthy throws ranked only\n11 of 24 by FTN's charting, yet the\ndefense caught more than the charting expected. Some of that is bad luck; some may be the charting\nitself, which is one person's judgement of each throw. This is the reason some analysts look at quarterback EPA with\ninterceptions down-weighted: the decision is skill, the catch is partly chance. FTN's labels are one\ncharter's judgement, so treat them as evidence, not truth.[^ftn]\n\n## The broadcast metrics, placed on a map\n\nYou now have the tools to judge any football metric with three questions: **what does it measure,\ncan you rebuild it, and when does it fool you?** Here is where the metrics you hear on broadcasts sit.\n\n::: {#cell-fig-metric-map .cell execution_count=36}\n``` {.python .cell-code}\nMETRICS = [  # name, x (team -> player), y (open -> proprietary), source\n    (\"Explosive play rate\", 0.07, 0.93, \"Box score\"),\n    (\"Success rate\", 0.12, 0.76, \"Play-by-play model\"),\n    (\"EPA per play\", 0.22, 0.86, \"Play-by-play model\"),\n    (\"Passer rating\", 0.50, 0.95, \"Box score\"),\n    (\"ANY/A\", 0.48, 0.80, \"Box score\"),\n    (\"CPOE\", 0.66, 0.66, \"Play-by-play model\"),\n    (\"RYOE\", 0.80, 0.44, \"Tracking data\"),\n    (\"QBR\", 0.56, 0.25, \"Play-by-play model\"),\n    (\"DVOA\", 0.18, 0.30, \"Play-by-play model\"),\n    (\"ESPN win rates\\n(pass rush, run stop)\", 0.83, 0.20, \"Tracking data\"),\n    (\"PFF grades\", 0.88, 0.06, \"Human charting\"),\n]\nSRC = {\"Box score\": (style.SERIES[3], \"s\"), \"Play-by-play model\": (style.SERIES[0], \"o\"),\n       \"Tracking data\": (style.SERIES[2], \"D\"), \"Human charting\": (style.SERIES[1], \"^\")}\nfig, ax = plt.subplots(figsize=(6.5, 4.8))\nax.axhspan(0.55, 1.02, color=style.SERIES[0], alpha=0.06, lw=0)\nax.axhspan(0, 0.55, color=style.SERIES[1], alpha=0.06, lw=0)\nax.axhline(0.55, color=style.BASELINE, lw=1, ls=(0, (4, 3)))\nfor name, x, y, src in METRICS:\n    c, mk = SRC[src]\n    ax.scatter(x, y, s=70, color=c, marker=mk, edgecolor=style.SURFACE, linewidth=1.2, zorder=3)\n    ax.text(x + 0.025, y, name, fontsize=8, color=style.INK, va=\"center\", ha=\"left\")\nax.set_xlim(0, 1.12)\nax.set_ylim(0, 1.02)\nax.set_xticks([0.05, 0.5, 0.95], [\"whole offense\", \"quarterback\", \"one player's\\nown share\"])\nax.set_yticks([0.27, 0.78], [\"closed:\\nnumbers only\", \"open:\\nrebuildable\"])\nax.tick_params(axis=\"y\", length=0)\nax.set_xlabel(\"What it credits\")\nax.set_title(\"A map of football metrics\")\nax.grid(False)\nax.legend(handles=[plt.Line2D([], [], ls=\"\", marker=mk, color=c, markersize=8, label=k)\n                   for k, (c, mk) in SRC.items()],\n          loc=\"upper center\", bbox_to_anchor=(0.5, -0.17), ncol=4, fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Where the common football metrics sit. Left to right: from crediting the whole offense to isolating one player. The two bands are a yes/no split: open formulas you can recompute from public data (top) versus closed metrics (bottom), whose numbers you can often download (nflverse ships RYOE, ESPN publishes QBR) but whose model or grading you cannot rebuild. Height within a band only keeps labels apart. Shape and color show the raw material each is built from.](13-02-expected-points-and-success-rate_files/figure-html/fig-metric-map-output-1.svg){#fig-metric-map}\n:::\n:::\n\n\nThe map is a simplification (QBR is built on expected points, DVOA on success-style values, PFF\ngrades on human judgement), but it captures the two questions that matter most when someone quotes a\nnumber at you: *whose* performance does it try to measure, and *can anyone check it*?\n\n### Passer rating\n\n**[Passer rating](../../appendices/glossary.qmd#gl-passer-rating)** is the oldest number on the map\nand still the one on the scoreboard graphic. The NFL adopted it in 1973, from a committee headed by\nDon Smith of the Pro Football Hall of Fame with Seymour Siwoff of the Elias Sports Bureau and Don\nWeiss of the league office.[^rating] The problem they faced was that the league crowned its passing\nleader by ranking passers against each other in several categories and adding up the ranks, and the\ncategories kept changing, so a rating depended on who else threw that year and could not be compared\nacross seasons. Their answer was to put four rates on fixed scales, each anchored so that an average\npasser of 1960-1970 scored 1.0 per part, and cap each part so that no single stat could run away\nwith the total. The formula is short enough to write in code:\n\n::: {#passer-rating .cell execution_count=37}\n``` {.python .cell-code}\ndef passer_rating(cmp, att, yds, td, ints):\n    clip = lambda v: np.clip(v, 0, 2.375)          # each part is capped at 0 and 2.375\n    a = clip((cmp / att - 0.3) * 5)                # completion percentage\n    b = clip((yds / att - 3) * 0.25)               # yards per attempt\n    c = clip(td / att * 20)                        # touchdown rate\n    d = clip(2.375 - ints / att * 25)              # interception rate\n    return (a + b + c + d) / 6 * 100               # perfect = 158.3\n\n\ndef any_a(yds, td, ints, sack_yds, att, sacks):\n    \"\"\"Adjusted net yards per attempt (sack_yds as a positive number of yards lost).\"\"\"\n    return (yds + 20 * td - 45 * ints - sack_yds) / (att + sacks)\n\n\natt_rows = plays[(plays.pass_attempt == 1) & (plays.sack == 0)]\nlg = att_rows.groupby(\"season\").agg(cmp=(\"complete_pass\", \"sum\"), att=(\"pass_attempt\", \"sum\"),\n                                     yds=(\"passing_yards\", \"sum\"), td=(\"pass_touchdown\", \"sum\"),\n                                     ints=(\"interception\", \"sum\"))\nleague_rating = passer_rating(lg.cmp, lg.att, lg.yds, lg.td, lg.ints)\nprint(\"League passer rating:\", league_rating.round(1).to_dict())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLeague passer rating: {2016: 89.6, 2017: 87.2, 2018: 93.3, 2019: 90.7, 2020: 94.0, 2021: 91.1, 2022: 89.4, 2023: 89.3, 2024: 92.7, 2025: 91.8}\n```\n:::\n:::\n\n\nThe odd numbers come from simple arithmetic. An average passer scores 1.0 on each of the four parts,\n4.0 in all; the formula divides by 6 and multiplies by 100, so an average passer of that era rates\n4 / 6 × 100 = 66.7. Each part is capped at 2.375, so the most any passer can reach is\n4 × 2.375 / 6 × 100 = 158.3, the \"perfect\" rating.\n\nThe real virtue of passer rating is that **it is open**: anyone can compute it from a box score, and\nit does correlate with EPA. The design was sensible in 1973, and its limits are now easy to see:\n\n- **The scale has drifted.** It was built so that an average passer would rate about 66.7. The\n  league as a whole now rates around 92, because completion\n  rates rose and interception rates fell. A rating of 90 was elite in the 1970s and is roughly average\n  now.\n- **It ignores sacks, scrambles and runs**, so it cannot see a quarterback who takes drive-killing\n  sacks or one who adds value with his legs.\n- **It ignores situation.** A 6-yard completion on third-and-10 helps a passer rating; it does not\n  help the team.\n\n### ANY/A\n\n**[ANY/A](../../appendices/glossary.qmd#gl-any-a)**, adjusted net yards per attempt, fixes the worst\ngaps with a box-score formula: count sacks as attempts and their lost yards as negative yards, add a\nbonus for touchdowns and a penalty for interceptions. Its weights trace to *The Hidden Game of\nFootball*, and the version used today (20 yards per touchdown, 45 per interception) is the one Pro\nFootball Reference publishes.[^anya] Those weights are rough exchange rates between yards and points,\nthe same idea as EPA without the situation. At *The Hidden Game*'s 0.08 points per yard, 45 yards is\nabout 3.6 points, close to the three and a half to four points this chapter measured for a typical\ninterception; 20 yards is about 1.6 points, roughly the gap between a touchdown's 7 and a\nfirst-and-goal close to the goal line. ANY/A is the best box-score quarterback stat and tracks\nEPA per dropback closely. Distrust it in the same places you distrust yards: it does not know the\ndown, the distance or the score.\n\n::: {#cell-qb-metrics .cell execution_count=38}\n``` {.python .cell-code}\nqbbox = (att_rows.groupby([\"season\", \"passer_id\", \"passer\"])\n         .agg(cmp=(\"complete_pass\", \"sum\"), att=(\"pass_attempt\", \"sum\"),\n              yds=(\"passing_yards\", \"sum\"), td=(\"pass_touchdown\", \"sum\"),\n              ints=(\"interception\", \"sum\")).reset_index())\nsk = (db[db.sack == 1].groupby([\"season\", \"passer_id\"])\n      .agg(sacks=(\"sack\", \"sum\"), sack_yds=(\"yards_gained\", lambda s: -s.sum())))\nqbm = (qbbox.merge(sk.reset_index(), on=[\"season\", \"passer_id\"], how=\"left\").fillna(0)\n       .merge(qb[[\"season\", \"passer_id\", \"epa\", \"cpoe\"]], on=[\"season\", \"passer_id\"]))\nqbm[\"rating\"] = passer_rating(qbm.cmp, qbm.att, qbm.yds, qbm.td, qbm.ints)\nqbm[\"any_a\"] = any_a(qbm.yds, qbm.td, qbm.ints, qbm.sack_yds, qbm.att, qbm.sacks)\ncorr = qbm[[\"epa\", \"any_a\", \"rating\", \"cpoe\"]].corr()[\"epa\"]\nprint(\"Correlation with EPA per dropback (QB seasons, 250+ attempts, 2016-2025):\",\n      corr.drop(\"epa\").round(2).to_dict())\nq25 = qbm[qbm.season == 2025].copy()\nq25[\"rating_rank\"] = q25.rating.rank(ascending=False).astype(int)\nq25[\"epa_rank\"] = q25.epa.rank(ascending=False).astype(int)\ngap = q25.assign(g=q25.rating_rank - q25.epa_rank).sort_values(\"g\")\nhi_rating, hi_epa = gap.iloc[0], gap.iloc[-1]      # rated better than EPA; EPA better than rating\nmd_table(q25.sort_values(\"epa\", ascending=False)\n         [[\"passer\", \"att\", \"rating\", \"any_a\", \"cpoe\", \"epa\", \"rating_rank\", \"epa_rank\"]].head(10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCorrelation with EPA per dropback (QB seasons, 250+ attempts, 2016-2025): {'any_a': 0.93, 'rating': 0.87, 'cpoe': 0.7}\n```\n:::\n\n::: {#qb-metrics .cell-output .cell-output-display .cell-output-markdown execution_count=38}\n| passer | att | rating | any_a | cpoe | epa | rating_rank | epa_rank |\n| :--- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n| D.Maye | 492 | 113.48 | 8.26 | 10.78 | 0.32 | 1 | 1 |\n| J.Love | 438 | 101.41 | 7.41 | 5.53 | 0.26 | 6 | 2 |\n| M.Stafford | 594 | 109.74 | 8.29 | 1.54 | 0.22 | 2 | 3 |\n| B.Purdy | 284 | 100.48 | 7.00 | 7.23 | 0.21 | 9 | 4 |\n| J.Goff | 576 | 105.84 | 7.53 | 1.78 | 0.18 | 3 | 5 |\n| J.Allen | 459 | 102.37 | 6.85 | 3.51 | 0.17 | 5 | 6 |\n| D.Prescott | 597 | 100.02 | 7.16 | 2.20 | 0.17 | 10 | 7 |\n| P.Mahomes | 500 | 89.98 | 6.25 | 0.34 | 0.17 | 23 | 8 |\n| D.Jones | 382 | 100.70 | 7.33 | 2.30 | 0.16 | 7 | 9 |\n| M.Jones | 286 | 98.40 | 6.73 | 3.68 | 0.13 | 13 | 10 |\n:::\n:::\n\n\nAmong quarterback seasons since 2016, ANY/A tracks EPA per dropback most closely, then passer\nrating, then CPOE, which is the most different by design (it measures accuracy, not results). The\ndisagreements are the useful part. Among the 33 qualifying 2025 quarterbacks, the one\nwhose passer rating flattered him most was L\\.Jackson (rating rank\n4, EPA rank 19); the one the\nrating undersold most was P\\.Mahomes (rating rank 23,\nEPA rank 8). A quarterback with a high rating but middling EPA per dropback is usually\ntaking sacks, or completing passes that fall short of the sticks; one with high EPA but a modest\nrating is often adding value the rating cannot see, with his legs or on third down.\n\n### QBR\n\n**[QBR](../../appendices/glossary.qmd#gl-qbr)** (ESPN's Total QBR) was introduced by ESPN in 2011 to\ndo what passer rating could not: credit everything a quarterback does, in context.[^qbr] It is built on\nexpected points, divides credit for each play between the quarterback and his teammates (a\nscreen that a receiver turns into a long touchdown is not all the quarterback's), includes runs,\nsacks and penalties, adjusts for the defenses faced, and uses win probability to give less credit\nfor plays when the game is already out of reach, so a throw in a blowout counts for less than the\nsame throw in a close game. (The first version also gave extra credit for \"clutch\" plays; ESPN\ndropped that.) It runs from 0 to 100, with 50 about average.\n\nQBR is closer to EPA than any other broadcast number, and its ideas are sound. The trouble is that\nit is **proprietary**: the credit-division model and the weights are ESPN's, so you cannot reproduce\nit or check why a game graded the way it did. Use it as a well-built opinion; distrust it on single\ngames, where the win-probability weighting can make the same performance grade very differently.\n\n### DVOA\n\n**[DVOA](../../appendices/glossary.qmd#gl-dvoa)**, Defense-adjusted Value Over Average, was created by\nAaron Schatz at Football Outsiders in the early 2000s and has been published by FTN since August\n2023, when Schatz moved there and Football Outsiders shut down.[^dvoa] Like EPA, it scores every play against what an average team would\ndo in the same situation; unlike nflverse EPA, it starts from success-style values rather than\nexpected points, and it **adjusts for opponents**. Results are percentages: +20% on offense means 20%\nbetter than average; on defense, *negative* is good. DVOA's strengths are its long history and its\nopponent adjustment. Its weakness is that the exact baselines and adjustments are not public, so\nit cannot be rebuilt, and early in a season FTN also publishes DAVE, a version that blends DVOA with\nthe preseason projection, so check which one is being quoted.\n\n### PFF grades\n\n**[PFF grades](../../appendices/glossary.qmd#gl-pff-grade)** come from Pro Football Focus, founded in\nEngland in 2004 by Neil Hornsby.[^pff] PFF's analysts watch every player on every snap and grade each\none, roughly from −2 to +2 in half-point steps, for how well he did his job regardless of the\nplay's result; the season's grades are then scaled to 0-100. That is the opposite of EPA's design.\nEPA measures outcomes and divides credit poorly; grades measure individual process and can credit a\nguard who won his block on a play that lost yards.\n\nTheir weakness is the mirror image: grades are **human judgements**, made without knowing each\nplayer's exact assignment, and the scale-up from play grades to a season grade is proprietary.\nDifferent good analysts would grade some plays differently. Use grades for positions that have no\nbox-score stats (offensive line, coverage), and treat a one-game grade as one opinion.\n\n### ESPN's win rates\n\nESPN Analytics publishes four **win rates** built from NFL Next Gen Stats tracking data: the pass\nrates were introduced in 2018 and the run rates in 2020, both designed by Brian Burke.[^winrates] [Pass rush win rate](../../appendices/glossary.qmd#gl-pass-rush-win-rate) (taught in\n[The Pass Rush](../07-pressure/07-01-pass-rush.qmd)) asks whether a rusher beats his block within 2.5\nseconds; **pass block win rate** asks the reverse (did the blocker hold his man for 2.5 seconds). **[Run stop win\nrate](../../appendices/glossary.qmd#gl-run-stop-win-rate)** (RSWR) does the same for run defense: a\ndefender \"wins\" if he defeats his block to fill his gap, penetrates the line, or forces the runner to\nbounce, or if he makes a tackle within 3 yards of the line of scrimmage even while blocked; **run\nblock win rate** is the blocker's side of the same contest. The tracking data makes the measurement\nobjective, and the fixed 2.5-second clock takes the quarterback out of the pass-rush number: a\nquarterback who holds the ball for five seconds would otherwise hand every rusher a \"win,\" and one who\nthrows in two would hide a rusher who was about to get home.\n\nThe caveats: the exact rules for a run-stop \"win\" are ESPN's, the metrics are published as\nleaderboards rather than play-level data, and a win is not a result (a defender can win his block\nand still be out of position). They are best for comparing linemen with each other, the place where\nbox-score stats like sacks and tackles are weakest.\n\n### Explosive play rate\n\nLast, the simplest, defined earlier in this chapter: open, easy to compute, a poor predictor, and\nalways worth checking for which cut-offs a source used.\n\n::: {.callout-important title=\"Why it exists\"}\nEvery metric on the map exists because the one before it missed something. Passer rating replaced\na confusing set of rankings; ANY/A added sacks and touchdowns; EPA added situation; QBR and DVOA added\nopponents and credit-sharing; win rates and grades went after the players who never touch the ball.\nEach fix costs something: usually openness, sometimes objectivity. The trade is always the same:\n**the more a metric tries to isolate one player in context, the more modelling or judgement it needs,\nand the harder it is to check.**\n:::\n\n::: {.callout-tip title=\"Watch for it\"}\n**EPA in your head.** You do not need a laptop to keep an expected-points ledger. Memorise these\nanchors for first-and-10 (nflverse's EP, the curve in the first chart):\n\n| First-and-10 at | Own 10 | Own 25 | Midfield | Opp 20 | Goal at the 1 |\n|---|---:|---:|---:|---:|---:|\n| Expected points | 0\\.1 | 1\\.1 | 2\\.6 | 4\\.5 | 6\\.3 |\n\nThen, on each snap:\n\n- **Before the snap**, find the anchor nearest the ball and adjust: add about\n  0\\.06 per yard toward the opponent's goal; subtract about\n  0\\.7 for second down, about\n  1\\.7 in all for third down and about\n  3\\.1 for fourth down; then subtract\n  about 0\\.07 for each yard of distance beyond 10 (or add it back for each\n  yard under 10).\n- **After the play**, estimate the new situation the same way. If the ball changed hands, flip the\n  sign of the new offense's EP. If it scored, use the points.\n- **Subtract.** Was it positive (a success) or negative? Was it big (more than about +1.5 or below\n  −1.5)? Most plays land between −1 and +1; turnovers and touchdowns are the outliers.\n- **Notice the \"empty yards\"**: completions short of the sticks on third down, and long gains as\n  the half's clock runs out (when \"no score\" becomes the likeliest outcome), both of which EPA\n  scores near zero or below.\n- **When a broadcast quotes a stat**, place it on the map: whose performance, open or proprietary,\n  and is the sample big enough to mean anything?\n\nAfterwards, check your guesses with the model: load the game's play-by-play, sort by EPA, and see how\nyour mental ledger compares. Add one line per play you tracked to your prediction log: quarter and\nclock, the situation, your EP before and after, the model's EPA, and whether you had the sign\nright ([Film Study and Charting](../15-capstone/15-02-film-study-and-charting.qmd) scores it).\n:::\n\n## Predict the play\n\nThe pictures use the course's position letters: on offense X, Z and H are wide receivers, Y and U\ntight ends, F the fullback and T the tailback; on defense E is an end, T a tackle, N a nose tackle,\nS, M and W the strong-side, middle and weak-side linebackers, C a cornerback, $ the nickel back, D the\ndime back, and FS and SS the safeties.\n\n::: {#drill-helpers .cell execution_count=39}\n``` {.python .cell-code}\nfrom gridiron import Play, offense, defense, routes as r\n\n\ndef situation_diagram(off, dfn, los, to_go, title, lateral=\"auto\", width_in=5.2, setup=None):\n    \"\"\"A pre-snap picture with the line to gain in yellow; `setup(p)` can add routes and notes.\"\"\"\n    p = Play(off, dfn, los=los, to_go=to_go, title=title)\n    if setup:\n        setup(p)\n    p.draw(lateral=lateral, width_in=width_in)\n    plt.show()\n```\n:::\n\n\n::: {.callout-tip title=\"Predict the play\"}\n**Third-and-9 at your own 30, second quarter, tie game.** The offense comes out in an empty\nbackfield with five receivers spread across the field; the defense answers with six defensive backs\nand two deep safeties. The quarterback completes a quick out to the left slot (H) for **7 yards**,\nand the defender over him tackles him short of the line to gain. Before reading on: what is EP before\nthe snap, roughly what is the EPA of that completion, and is it a success? Why would the defense\n*want* this throw?\n\n::: {#cell-fig-drill-empty .cell execution_count=40}\n``` {.python .cell-code}\ndef empty_setup(p):\n    p.route(\"H\", r.quick_out(8.5, 4))           # H starts 1.5 yds off the line: catch at +7\n    p.dropback(1.0)\n    p.pass_to(\"H\", t=1.6)\n    p.drop(\"DB\", (7.0, -12.0))\n    p.highlight(\"H\", \"DB\")\n    p.note(\"caught at +7\", at=(3.5, -14.5))\n\n\noff = offense(\"gun_empty\")\ndime = [q.moved(w=2.5) if q.key == \"MIKE\" else q for q in defense(\"dime\", \"two_high\", off)]\nsituation_diagram(off, dime, los=40, to_go=9, title=\"3rd & 9, own 30\",\n                  lateral=(-19, 19), width_in=6.2, setup=empty_setup)\n```\n\n::: {.cell-output .cell-output-display}\n![Third-and-9 at the offense's own 30: empty backfield (five receivers) against a six-defensive-back dime look with two deep safeties. H runs a quick out and catches it 7 yards downfield; the dime back (D) rallies from his underneath zone to tackle him short of the yellow line to gain. Every receiver has a defender over him, and both safeties stay deep.](13-02-expected-points-and-success-rate_files/figure-html/fig-drill-empty-output-1.svg){#fig-drill-empty}\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n\n::: {#drill-empty-answer .cell execution_count=41}\n``` {.python .cell-code}\nbefore = neutral[(neutral.down == 3) & neutral.ydstogo.between(8, 10)\n                 & neutral.yardline_100.between(65, 75)]\nshort = before[before.yards_gained.between(6, 8) & (before.yards_gained < before.ydstogo)]\nprint(f\"Model EP, 3rd & 9 at own 30: {my_ep(3, 9, 70)[0]:+.2f}; \"\n      f\"after, 4th & 2 at own 37: {my_ep(4, 2, 63)[0]:+.2f}\")\nprint(f\"Real plays: EP before (3rd & 8-10, own 25-35) {before.ep.mean():+.2f}; \"\n      f\"EPA of 6-8 yard gains short of the sticks {short.epa.mean():+.2f} ({len(short):,} plays, \"\n      f\"{(short.epa > 0).mean():.0%} positive)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel EP, 3rd & 9 at own 30: -0.17; after, 4th & 2 at own 37: -0.50\nReal plays: EP before (3rd & 8-10, own 25-35) +0.06; EPA of 6-8 yard gains short of the sticks -0.44 (191 plays, 4% positive)\n```\n:::\n:::\n\n\nThe situation is worth about zero before the snap (a little below on this chapter's model, a little\nabove on the real plays in that bucket): third-and-9 is converted well under half the time, and the\nlikely result is a punt. The 7-yard out leaves fourth-and-2 at the 37,\na situation where most teams still punt, so the play's EPA is **negative** and it is **not a\nsuccess**, even though it \"gained 7.\" (Many fourth-down models now rate going for it there as close\nto a toss-up; that is a win-probability question, and [Win Probability and Decision\nAnalysis](13-03-win-probability-and-fourth-down.qmd) takes it up. The EP model prices the punt that\nteams have usually chosen.) The handful of short gains with positive EPA are oddities, such as a\ndefensive penalty tacked on after the catch.\n\nThe two-deep, six-DB shell is one sensible answer: it keeps everything in front and rallies to\ntackle short of the sticks, which is exactly what happened in the picture. It is the conservative\nchoice. Against an empty backfield, defenses also like to bring a five-man pressure or play\n[Cover 1](../../appendices/glossary.qmd#gl-cover-1) man, because the quarterback has no back to help\nprotect; which one a team prefers is a tendency you can chart\n([Tendencies: PROE, Personnel, Motion, and Coverage](13-04-tendencies-proe-and-charting.qmd)).\nThis is the most common \"empty yards\" play on any broadcast.\n:::\n:::\n\n::: {.callout-tip title=\"Predict the play\"}\n**Second-and-1 at midfield, first quarter.** The offense brings in two tight ends and a fullback and\nlines up under center in an I-formation; the defense answers with a base 4-3 front and rolls its\nstrong safety down beside the tight end, eight men in the box. Which is the offense more likely to\ncall? Is that the \"wrong\" call by EPA, and is the gap between running and passing here as large as on\nfirst-and-10?\n\n::: {#cell-fig-drill-short .cell execution_count=42}\n``` {.python .cell-code}\ndef short_setup(p):\n    p.highlight(\"SS\")\n    p.note(\"8th man\", at=(8.5, 6.0))\n\n\noff = offense(\"i_form_22\")\nbase = [q.moved(d=5.0, w=-9.0) if q.key == \"LCB\" else q\n        for q in defense(\"4-3_over\", \"single_high\", off)]\nsituation_diagram(off, base, los=60, to_go=1, title=\"2nd & 1, midfield\",\n                  lateral=(-17, 17), setup=short_setup)\n```\n\n::: {.cell-output .cell-output-display}\n![Second-and-1 at midfield: 22 personnel in an I-formation (two tight ends, fullback and tailback) against a base 4-3 Over front with the strong safety (highlighted) rolled down to the tight-end side: four linemen, three linebackers and the safety make eight in the box. The left corner sits outside the U tight end as the force player; one safety stays deep.](13-02-expected-points-and-success-rate_files/figure-html/fig-drill-short-output-1.svg){#fig-drill-short}\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n\n::: {#cell-drill-short-answer .cell execution_count=43}\n``` {.python .cell-code}\ns21 = neutral[(neutral.down == 2) & (neutral.ydstogo == 1)]\ndisplay(md_table(s21.groupby(\"kind\").agg(plays=(\"epa\", \"size\"), epa=(\"epa\", \"mean\"),\n                                         success=(\"success\", \"mean\")).reset_index()))\nt31 = neutral[(neutral.down == 3) & (neutral.ydstogo == 1) & neutral.season.between(2021, 2025)]\nprint(f\"Third-and-1 converted {t31.first_down.mean():.0%} of the time (2021-2025, neutral)\")\nfpa = ftn_sn[[\"nflverse_game_id\", \"nflverse_play_id\", \"is_play_action\"]]\npa = (neutral[(neutral.kind == \"Dropback\") & neutral.season.between(2022, 2025)]\n      .merge(fpa, left_on=[\"game_id\", \"play_id\"],\n             right_on=[\"nflverse_game_id\", \"nflverse_play_id\"]))\npa_21 = pa.loc[(pa.down == 2) & (pa.ydstogo == 1), \"is_play_action\"].mean()\nprint(f\"Play-action on 2nd-and-1 dropbacks, 2022-2025: {pa_21:.0%} \"\n      f\"(all dropbacks {pa.is_play_action.mean():.0%})\")\n```\n\n::: {#drill-short-answer .cell-output .cell-output-display .cell-output-markdown}\n| kind | plays | epa | success |\n| :--- | ---: | ---: | ---: |\n| Designed run | 3,215 | -0.01 | 0.50 |\n| Dropback | 904 | 0.05 | 0.55 |\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nThird-and-1 converted 70% of the time (2021-2025, neutral)\nPlay-action on 2nd-and-1 dropbacks, 2022-2025: 44% (all dropbacks 27%)\n```\n:::\n:::\n\n\n**Run** is the likely call: teams run on roughly three out of four second-and-1 snaps, and heavy\npersonnel makes it likelier still. Is it the wrong call? The table says dropbacks earn a little more,\nbut apply this chapter's own lesson before you believe it. Passes on second-and-1 are a selected\ngroup, often called *because* the defense has loaded the box, as in the picture above: in FTN's\ncharting (2022-2025) about 44% of them used play-action, against\n27% of all dropbacks. Their edge is the edge of a\ncounter-punch thrown at the right moment, not proof that passing should be the default, and it is a\nsmall fraction of the two-tenths of a point dropbacks earn on first-and-10.\n\nNotice also how *hard* success is here: second-and-1 is already a good situation, so a run that\nmerely moves the chains barely raises EP, and about half of all runs end with negative EPA. That is\nwhy coaches call this a \"free\" down: even if a shot downfield falls incomplete, third-and-1 still\nconverts about 70% of the time. So the prediction is \"run,\"\nand the moment to watch for is the play-action shot that the run makes possible ([Constraint Theory\nand Sequencing](../08-the-chess-match/08-02-constraint-theory-and-sequencing.qmd)).\n:::\n:::\n\n::: {.callout-tip title=\"Predict the play\"}\n**First-and-goal at the 1.** The offense is in a jumbo goal-line set; the defense has everyone\nwithin a couple of yards of the line. Three possible outcomes: (a) a 1-yard touchdown run, (b) the\nback is stuffed for no gain, (c) the back fumbles and the defense recovers in the end zone for a\ntouchback. Rank them by EPA, and guess how large each is.\n\n::: {#cell-fig-drill-goal .cell execution_count=44}\n``` {.python .cell-code}\noff = [q.moved(label=\"H\") if q.key == \"W\" else q for q in offense(\"goal_line\")]\ngoal_d = []\nfor q in defense(\"46\", \"zero\", off):\n    if q.pos == \"CB\":\n        q = q.moved(d=2.0, w=np.sign(q.w) * 8.5)\n    elif q.key == \"MIKE\":                            # second level: 1-2 yards deep in the\n        q = q.moved(d=2.3)                           # end zone, ready to fill downhill\n    elif q.key == \"SS\":\n        q = q.moved(d=2.3, w=-3.5)\n    elif q.key == \"FS\":\n        q = q.moved(d=3.0, w=0.0)\n    goal_d.append(q)\nsituation_diagram(off, goal_d, los=109, to_go=1,\n                  title=\"1st & goal at the 1\", lateral=(-11, 11), width_in=6.0)\n```\n\n::: {.cell-output .cell-output-display}\n![First-and-goal at the 1: a goal-line formation (three tight ends, with the wing labelled H, plus fullback and tailback) against a 46-style goal-line defense: six men on the line, both outside linebackers set to the tight-end side, and the middle linebacker, safeties and corners all within about two yards of the goal line, ready to fill downhill. The line to gain is the goal line.](13-02-expected-points-and-success-rate_files/figure-html/fig-drill-goal-output-1.svg){#fig-drill-goal}\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n\n::: {#drill-goal-answer .cell execution_count=45}\n``` {.python .cell-code}\nep_goal = my_ep(1, 1, 1)[0]\nep_2nd = my_ep(2, 1, 1)[0]\nep_opp_tb = my_ep(1, 10, 80)[0]      # opponent's ball on their own 20 after the touchback\nprint(f\"EP before: {ep_goal:+.2f}\")\nprint(f\"(a) TD:      EPA = 7 - {ep_goal:.2f} = {7 - ep_goal:+.2f}\")\nprint(f\"(b) stuffed: EPA = {ep_2nd:.2f} - {ep_goal:.2f} = {ep_2nd - ep_goal:+.2f}\")\nprint(f\"(c) fumble:  EPA = -{ep_opp_tb:.2f} - {ep_goal:.2f} = {-ep_opp_tb - ep_goal:+.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEP before: +6.42\n(a) TD:      EPA = 7 - 6.42 = +0.58\n(b) stuffed: EPA = 5.91 - 6.42 = -0.51\n(c) fumble:  EPA = -0.79 - 6.42 = -7.21\n```\n:::\n:::\n\n\nThe touchdown earns surprisingly little, because first-and-goal at the 1 already \"owns\" most of a\ntouchdown. The stuff costs about as much as the touchdown gains: second-and-goal at the 1 is still\nan excellent situation. The fumble is a disaster of a different order: the offense throws away more\nthan six expected points *and* hands the opponent the ball at their 20, a swing of about seven.\n(The ball goes to the 20 because a touchback after a turnover is still spotted there; only\n*kickoff* touchbacks moved to the 30 and then the 35.) It is the clearest example of why ball\nsecurity on the goal line matters more than an extra half-yard of push, and why one goal-line\nfumble can erase a short-yardage back's whole season of EPA.\n:::\n:::\n\n## Takeaways\n\n- **Expected points is a probability model for the next score**: seven possible outcomes, each with\n  a probability that depends on down, distance, field position and the clock. You can fit a decent one\n  in thirty lines of NumPy; nflverse's model adds time, timeouts, venue and era. It values situations\n  for an *average* team, which is what lets EPA measure the difference.\n- **EPA is EP after minus EP before**, with scores counted as points and changes of possession flipped.\n  In your head: about 0.06 a yard, a growing cost for each lost down, and a little for each yard of\n  distance. It beats yards because it prices context, sacks and turnovers in one unit, though its\n  predictive edge over simpler stats is smaller than its descriptive one, and it ignores the score.\n- **Run-versus-pass averages are riddled with selection effects.** Hold the situation fixed and\n  dropbacks still out-earn runs on early downs and third-and-long, while in short yardage the gap\n  closes and runs succeed more often, partly thanks to the quarterback sneak.\n- **Respect the noise.** A play's EPA varies by about 1.4 points; a game is a small sample; several\n  games pass before signal matches noise. Offense repeats better than defense, success rate about as\n  well as EPA, and fumble recovery not at all. Adjust for opponents when schedules are lopsided.\n- **For players, separate what they were given from what they added**: CPOE for quarterbacks' accuracy,\n  RYOE for runners, and a skeptical eye on interceptions, which carry real luck.\n- **Place every broadcast metric on the map**: what it credits, whether it is open, and how much\n  modelling or judgement sits inside it. Passer rating and ANY/A are open but blind to context; QBR,\n  DVOA, PFF grades and ESPN win rates add context or isolate players at the cost of being proprietary.\n\n## Connections\n\n**Builds on:** the EPA primer in [Downs, Distance, and Field\nPosition](../01-foundations/01-02-downs-distance-and-field-position.qmd) and the data skills in [Working with\nnflverse Data in Python](13-01-nflverse-in-python.qmd). CPOE is introduced in [Quarterback\nPlay](../04-the-passing-game/04-07-quarterback-play.qmd), pass rush win rate in [The Pass\nRush](../07-pressure/07-01-pass-rush.qmd).\n\n**Sets up:**\n\n- [Win Probability and Decision Analysis](13-03-win-probability-and-fourth-down.qmd): the score-aware\n  cousin of EP, and the fourth-down and two-point decisions built on both.\n- [Tendencies: PROE, Personnel, Motion, and Coverage](13-04-tendencies-proe-and-charting.qmd): expected pass\n  rate, the same \"over expected\" idea applied to play-calling.\n- [Tracking Data and the Big Data Bowl](13-05-tracking-data-and-big-data-bowl.qmd): the tracking frames\n  behind RYOE and the win rates.\n- [Building a Roster](../14-the-business-of-scheme/14-01-building-a-roster.qmd): positional value, and why\n  stability numbers like these shape what teams pay for.\n- Appendix G, the Metrics and Data Atlas, gives each metric in this chapter a one-card summary.\n\n**If you want to go deeper:** Ben Baldwin's write-up of the nflfastR expected-points, win-probability\nand completion-probability models on Open Source Football;[^nflfastr] Yurko, Ventura and Horowitz's\nnflWAR paper;[^nflwar] *The Hidden Game of Football* by Carroll, Palmer and Thorn for the history; and\nthe public method notes from FTN (DVOA), ESPN (QBR and win rates) and PFF (grading) before trusting\nany of their numbers.\n\n[^lx]: Super Bowl LX, February 8, 2026, Levi's Stadium: Seattle 29, New England 13. Play-level details\n    (Darnold to Kupp on third-and-12; the Nwosu interception return; Derick Hall's strip-sack) are from the\n    nflverse play-by-play for game `2025_22_SEA_NE`. Summary: <https://en.wikipedia.org/wiki/Super_Bowl_LX>.\n    Seattle's 2025 staff (HC Mike Macdonald, DC Aden Durde) per the course fact sheet and\n    <https://en.wikipedia.org/wiki/2025_Seattle_Seahawks_season>.\n[^sea-cov]: NFL.com (Next Gen Stats), \"The coverage that turned the Seahawks into Super Bowl winners and\n    is taking the NFL by storm\": <https://www.nfl.com/news/the-coverage-that-turned-the-seahawks-into-super-bowl-winners-and-is-taking-the-nfl-by-storm>.\n    Seattle's and the game's coverage shares are this chapter's calculation from nflverse participation\n    data (coverage labels charted by FTN for 2023 on); six sacks per the course fact sheet and the\n    game's play-by-play.\n[^nflverse]: nflverse play-by-play, participation, Next Gen Stats and FTN charting data, loaded with\n    nflreadpy (<https://github.com/nflverse/nflreadpy>) and cached in `data/cache/`. Seasons 2016-2025, regular\n    season; data retrieved October 2026. nflverse revises past seasons occasionally, so re-running the\n    code can move the last decimal place.\n[^nflfastr-guide]: nflfastR, \"A beginner's guide to nflfastR\" (filters on `rush == 1 | pass == 1`;\n    EPA is computed on penalty plays; exclude `play_type == \"no_play\"` to match official stats):\n    <https://nflfastr.com/articles/beginners_guide.html>.\n[^nflfastr]: Ben Baldwin, \"nflfastR EP, WP, and CP models,\" Open Source Football, 2020 (feature list,\n    XGBoost, and the drive-distance and score-differential weights):\n    <https://www.opensourcefootball.com/posts/2020-09-28-nflfastr-ep-wp-and-cp-models/>; nflfastR\n    documentation: <https://www.nflfastr.com/>.\n[^nflwar]: Ronald Yurko, Samuel Ventura and Maksim Horowitz, \"nflWAR: A reproducible method for offensive\n    player evaluation in football,\" *Journal of Quantitative Analysis in Sports* 15, no. 3 (2019): 163-183,\n    <https://doi.org/10.1515/jqas-2018-0010>; preprint <https://arxiv.org/abs/1802.00998>.\n[^carter]: Virgil Carter and Robert E. Machol, \"Technical Note: Operations Research on Football,\"\n    *Operations Research* 19, no. 2 (1971): 541-544, <https://doi.org/10.1287/opre.19.2.541> (8,373 plays\n    from the first 56 games of 1969). On Carter's master's degree, the PR-office data and Bill Walsh:\n    ESPN, \"Ex-Bengals QB Virgil Carter's legacy of EPA,\"\n    <https://www.espn.com/nfl/story/_/id/40276150/nfl-epa-analytics-virgil-carter-cincinnati-bengals>;\n    <https://en.wikipedia.org/wiki/Virgil_Carter>.\n[^hidden]: Bob Carroll, Pete Palmer and John Thorn, *The Hidden Game of Football* (New York: Warner Books,\n    1988). The straight-line values (−2 at your own goal line to +6 at the opponent's) as summarised in\n    cfbfastR, \"College Football Expected Points Model Fundamentals, Part III\":\n    <https://cfbfastr.sportsdataverse.org/articles/college-football-expected-points-model-fundamentals-part-iii.html>.\n[^burke]: ESPN Front Row, \"Former Navy pilot Brian Burke joins ESPN as senior analytics specialist,\" June\n    2015: <https://www.espnfrontrow.com/2015/06/former-navy-pilot-brian-burke-joins-espn-as-senior-analytics-specialist/>;\n    ESPN Press Room bio (F/A-18 carrier pilot; founded Advanced NFL Stats in 2007):\n    <https://espnpressroom.com/us/bios/brian-burke/>.\n[^touchback]: NFL, \"NFL owners vote to make dynamic kickoff permanent, adjust ball spot on touchbacks to\n    35-yard line\" (2025): <https://www.nfl.com/news/nfl-owners-vote-to-make-dynamic-kickoff-permanent-adjust-ball-spot-on-touchbacks-to-35-yard-line>.\n[^fo-sr]: Aaron Schatz, \"Football Outsiders stats explainer,\" ESPN.com, October 25, 2007 (success rate at\n    40/60/100%; defensive \"stops\" at 45/60/100%): <https://www.espn.com.au/nfl/news/story?id=3079031>. The\n    thresholds' origin in *The Hidden Game of Football*: Steelers Depot, \"Looking at the Steelers'\n    success/failure play rates by down\" (2012),\n    <https://steelersdepot.com/2012/10/looking-at-the-steelers-success-failure-play-rates-by-down>.\n[^explosive]: Analysts' cut-offs compared (and a 10-yard run / 25-yard pass alternative proposed) in\n    Sam Hoppen, \"How should we define an explosive play?\":\n    <https://samhoppen.substack.com/p/how-should-we-define-an-explosive>.\n[^explosive-coach]: NBC Sports Bay Area, \"Of the Raiders and explosive plays\" (October 2012; Dennis\n    Allen: 16+ yards passing, 12+ rushing, \"That's the way we look at it here\"):\n    <https://www.nbcsportsbayarea.com/nfl/of-the-raiders-and-explosive-plays/1325433/>; David Helman,\n    \"Scott Linehan looking to get greedy for more explosive plays,\" DallasCowboys.com, September 16,\n    2016 (runs of 12+ and passes of 16+):\n    <https://dallascowboys.com/news/scott-linehan-looking-to-get-greedy-for-more-explosive-plays-413426>.\n[^pa]: Ben Baldwin, guest column on play-action and the running game, Football Outsiders, February 2018\n    (play-by-play charting, 2011-2017); Josh Hermsmeyer, \"Can NFL Coaches Overuse Play-Action? They\n    Haven't Yet,\" FiveThirtyEight, 2018 (linebackers bite on the fake regardless of how often it is run).\n    Summary of both: <https://en.wikipedia.org/wiki/Play-action_pass>.\n[^ravens]: 2024 Ravens rushing figures from nflverse play-by-play (this chapter's code); season context at\n    Pro Football Reference: <https://www.pro-football-reference.com/teams/rav/2024.htm>.\n[^ryoe]: NFL Next Gen Stats Analytics, \"Next Gen Stats: Intro to Expected Rushing Yards\" (2020):\n    <https://www.nfl.com/news/next-gen-stats-intro-to-expected-rushing-yards>; NFL Football Operations,\n    \"2020 Big Data Bowl results\": <https://operations.nfl.com/updates/the-game/2020-big-data-bowl-results>.\n[^ftn]: FTN charting data (2022+) via nflverse, field `is_interception_worthy`; licence CC-BY-SA 4.0.\n    Dictionary: <https://nflreadr.nflverse.com/articles/dictionary_ftn_charting.html>.\n[^rating]: Pro Football Hall of Fame, \"NFL's Passer Rating\" (committee of Don Smith, Seymour Siwoff and\n    Don Weiss; standards from all qualified passers since 1960; adopted 1973):\n    <https://www.profootballhof.com/news/nfl-s-passer-rating/>; Pete Palmer, \"Palmer Method,\" *The Coffin\n    Corner* 7, no. 1 (1985), on the pre-1973 ranking systems:\n    <https://profootballresearchers.com/archives/Website_Files/Coffin_Corner/07-01-214.pdf>.\n[^anya]: Pro Football Reference glossary, \"Adjusted Net Yards per Pass Attempt\" (PFR notes it now uses 20\n    yards per touchdown rather than the book's 10):\n    <https://www.pro-football-reference.com/about/glossary.htm>; Carroll, Palmer and Thorn (1988).\n[^qbr]: ESPN, \"How is Total QBR calculated? We explain our quarterback rating,\" September 8, 2016:\n    <https://www.espn.com/blog/statsinfo/post/_/id/123701/how-is-total-qbr-calculated-we-explain-our-quarterback-rating>.\n    Opponent adjustment: <https://en.wikipedia.org/wiki/Total_quarterback_rating>.\n[^dvoa]: FTN, \"DVOA explainer\": <https://ftnfantasy.com/nfl/dvoa-explainer>; on Football Outsiders'\n    closure (September 2023) and Schatz joining FTN (August 2023): <https://en.wikipedia.org/wiki/Football_Outsiders>.\n[^pff]: Pro Football Focus, \"PFF grades: how they work\" (−2 to +2 in 0.5 increments, converted to 0-100):\n    <https://www.pff.com/grades>; founding (2004, Neil Hornsby, UK): <https://en.wikipedia.org/wiki/Pro_Football_Focus>.\n[^winrates]: Brian Burke, \"We created better pass-rusher and pass-blocker stats: How they work,\" ESPN,\n    October 5, 2018:\n    <https://www.espn.com/nfl/story/_/id/24892208/creating-better-nfl-pass-blocking-pass-rushing-stats-analytics-explainer-faq-how-work>;\n    Brian Burke, \"Introducing new NFL run-blocking and run-stopping stats,\" ESPN, September 8, 2020:\n    <https://www.espn.com/nfl/story/_/id/29813062/introducing-new-nfl-run-blocking-run-stopping-stats-how-run-block-win-rate-run-stop-win-rate-work>.\n\n",
    "supporting": [
      "13-02-expected-points-and-success-rate_files"
    ],
    "filters": [],
    "includes": {}
  }
}