"""Regenerate the book's chapter list in _quarto.yml from planning/chapters.yml.

Only chapters whose .qmd exists are listed, so the site builds at any stage.

planning/chapters.yml:
    parts:
      - title: "Part 1 — Foundations"
        dir: 01-foundations
        chapters: [01-01-what-a-play-really-is, 01-02-downs-distance-and-the-field]
"""

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
BEGIN, END = "    # CHAPTERS-BEGIN", "    # CHAPTERS-END"


def main():
    spec = yaml.safe_load((ROOT / "planning/chapters.yml").read_text())
    lines = [BEGIN + " (generated by scripts/gen_toc.py from planning/chapters.yml)"]
    n = 0
    for part in spec["parts"]:
        files = [f"chapters/{part['dir']}/{c}.qmd" for c in part["chapters"]]
        files = [f for f in files if (ROOT / f).exists()]
        if not files:
            continue
        lines.append(f'    - part: "{part["title"]}"')
        lines.append("      chapters:")
        lines += [f"        - {f}" for f in files]
        n += len(files)
    lines.append(END)
    q = (ROOT / "_quarto.yml").read_text().splitlines()
    i = next(k for k, l in enumerate(q) if l.startswith(BEGIN))
    j = next(k for k, l in enumerate(q) if l.startswith(END))
    q[i:j + 1] = lines
    (ROOT / "_quarto.yml").write_text("\n".join(q) + "\n")
    print(f"{n} chapters listed")


if __name__ == "__main__":
    main()
